/** Every user-facing string of the UI. No literal UI text lives anywhere else. */
export const strings = {
  agents: {
    heading: 'Agents', intro: 'Persistent agents, shared conversations and team missions.', back: 'Back to chat',
    profiles: 'Agents', groups: 'Groups', teams: 'Teams', missions: 'Missions', attention: 'Needs attention',
    list: 'List', scene: 'Studio view', create: 'Create', edit: 'Configure', save: 'Save', cancel: 'Cancel', close: 'Close',
    search: 'Find an agent, group, team or mission', empty: 'Nothing here yet. Create your first entry.', select: 'Choose an entry to see its activity.',
    name: 'Name', domain: 'Domain', instructions: 'Instructions', identityHint: 'The identity and memory stay when you change its model.',
    model: 'Model and account', noAccount: 'Add a provider account in Settings before creating an agent.', permissions: 'Permissions',
    ask: 'Ask before actions', edits: 'Allow edits', plan: 'Plan only', full: 'Full access', deny: 'Do not ask',
    noApprovals: 'This provider has no interactive tool approval channel. Its launch permissions apply; business decisions remain available.',
    tools: 'Collaboration tools', messages: 'Messages', memory: 'Memory', artifacts: 'Results', decisions: 'Decisions',
    members: 'Members', responsibility: 'Responsibility', description: 'Description', project: 'Project', noProject: 'No project',
    team: 'Team', noTeam: 'No team', group: 'Discussion group', noGroup: 'No associated group',
    mode: 'Who responds', mentions: 'Selected recipients', round: 'One response per member', autonomous: 'Take turns automatically',
    maxTurns: 'Maximum turns', perAgent: 'Turns per agent', modeHint: 'Each new message starts an allowance. Replies keep the same allowance. Automatic exchanges stop at either limit.',
    paused: 'Paused', pause: 'Pause', resume: 'Resume', archive: 'Archive', active: 'Active', archived: 'Archived',
    objective: 'Objective', expectedResult: 'Expected result', minutes: 'Total execution minutes', tokens: 'Token limit, blank for none',
    finishMission: 'Finish mission', reopenMission: 'Reopen mission',
    conversation: 'Conversation', activity: 'Activity', send: 'Send', message: 'Write a message', recipients: 'Recipients', everyone: 'Let the group rule choose',
    noMessages: 'Start a conversation. It stays separate from this agent’s other groups and missions.', user: 'You', noWork: 'No execution yet.',
    openRun: 'Open execution', requested: 'Requested', executed: 'Executed', noUsage: 'Usage not reported',
    pending: 'Queued', running: 'Working', waiting: 'Waiting for a decision', done: 'Done', cancelled: 'Cancelled', interrupted: 'Interrupted', error: 'Failed', review: 'Ready for review', open: 'Open', assigned: 'Assigned', accepted: 'Accepted',
    included: 'Included in execution', processed: 'Processed', failed: 'Failed', limited: 'Exchange limit reached',
    reconcile: 'Review and resume', reconcileHint: 'Inspect the execution and files first. Describe what is already done and what can continue.', reconcileNote: 'What did you verify?',
    answer: 'Answer', answerPlaceholder: 'Your decision and instructions', noAttention: 'No decisions or interruptions need your attention.',
    task: 'Task', tasks: 'Tasks', addTask: 'Add task', acquire: 'Assign', dependencies: 'Wait for tasks', approve: 'Accept result', revise: 'Request changes', reject: 'Reject', feedback: 'Feedback for the next attempt',
    result: 'Result', verification: 'Verification reported by the agent', workspace: 'Workspace', copyPath: 'Copy path', noResults: 'Submitted results will appear here.',
    resources: 'Resources', addResource: 'Add resource', directory: 'Directory', url: 'URL', value: 'Value', read: 'Read', write: 'Write',
    resourceHint: 'Access declarations guide the agent. The provider’s permissions still control filesystem actions.',
    addMemory: 'Add memory', text: 'Text', scope: 'Scope', sources: 'Sources', ownerMemory: 'Added by you',
    searchKnowledge: 'Search memory and resources', expiresAt: 'Expires at, optional', expired: 'Expired', expireMemory: 'Expire now',
    engine: 'Background work', concurrency: 'Concurrent agents', engineHint: 'Closing this page leaves work running on the connected core.',
    kebacc: 'External kebacc experiment', kebaccHint: 'Use the external kebacc-switcher plugin for Antigravity CLI. Boite does not switch or rotate these accounts.',
    experimentOff: 'Enable the experiment in background settings first.', backgroundSettings: 'Background settings',
    sceneHint: 'Characters are agents, tables are groups, rooms are teams. Click one to open it.',
    sceneLabel: 'Live agent studio', sceneEmpty: 'Create agents and groups to populate the studio.',
    idle: 'Available', offline: 'Agents could not be loaded from this machine. Reconnect or update its core.', retry: 'Retry',
    stale: 'Connection lost. This is the last received state. Work may still be running on the host.',
    readOnly: 'Configuration is managed by the owner of this core.', history: 'History',
    stopEngine: 'Stop this core', stopEngineBody: 'Stops all work on this core and disconnects its clients. Started work will need review before resuming. Reopen Boite on the host to start the core again.',
  },
  speech: {
    heading: 'Voice', description: 'Dictate into any conversation. Review the text before sending.',
    start: 'Dictate', stop: 'Finish dictation', listening: 'Listening', opening: 'Waiting for microphone', transcribing: 'Transcribing',
    private: 'On this core only', cloud: 'Transcribed by your API provider', retry: 'Retry transcription',
    live: 'Live preview', previewFailed: 'Live preview paused. Finish to transcribe the full recording.',
    local: 'Local', api: 'API', localHint: 'Whisper runs on the machine hosting this conversation. Your phone uses the same model without downloading it.',
    apiHint: 'Audio goes from this core to your chosen provider. Keys stay on this core.',
    setup: 'Dictation is not set up on this machine yet. Open Voice settings to set it up in one click.', ownerSetup: 'Ask the owner to configure Voice on this core.',
    unsupported: 'Voice needs a newer Boite on {machine}', unsupportedHint: 'This machine runs a Boite version without the voice engine. Update Boite there, then open Voice again.',
    unsupportedDictation: 'Dictation needs a newer Boite on {machine}. Update Boite there, then try again.',
    notReady: 'Not set up yet',
    statusReady: 'Ready to dictate', statusReadyLocal: 'Press the microphone beside Send in any conversation. Whisper runs on this machine and the audio never leaves it.',
    statusReadyApi: 'Press the microphone beside Send in any conversation. {provider} transcribes the audio.',
    statusSetup: 'Dictation is not set up', statusSetupLocal: 'One download of about 200 MB, the Whisper Small model and its engine. After that, dictation runs on this machine without any account.',
    statusSetupModel: 'Downloads the Whisper Small model, about 190 MB. This machine also needs whisper-cli on PATH, or its path under Local paths.',
    statusKey: 'Add an API key', statusKeyHint: 'Paste a {provider} key below, or choose Local to dictate without any account.',
    statusFailed: 'The download did not finish', statusBroken: 'Voice settings could not be read', repair: 'Save to repair',
    setUp: 'Set up dictation', tryAgain: 'Try again', engine: 'Engine', installed: 'Installed', saveKeys: 'Save keys', savePaths: 'Save paths',
    phoneHint: 'Dictation uses the voice engine on the connected machine.',
    https: 'Microphone access needs HTTPS or localhost. Open the secure pairing link for this core.',
    denied: 'Microphone permission was denied. Allow it in your browser or system settings, then try again.',
    noMicrophone: 'No microphone was found. Connect one and try again.', microphoneBusy: 'The microphone is unavailable. Check whether another app is using it.',
    silence: 'No speech was detected. Try again closer to the microphone.', failed: 'Could not record audio. Try again.',
    model: 'Whisper Small', modelHint: 'Multilingual, quantized. About 190 MB. Loaded only while transcribing, using up to four CPU threads.',
    remove: 'Remove download', ready: 'Ready', missing: 'Not installed',
    downloading: 'Downloading', runtimeHint: 'Install whisper-cli on this core or set its absolute path below. The model download works on all platforms.',
    advanced: 'Local paths', executable: 'Whisper executable', modelPath: 'Model file', pathHint: 'Leave empty to use the managed download or whisper-cli on PATH.',
    provider: 'Transcription provider', groq: 'Groq', openrouter: 'OpenRouter', groqModel: 'Whisper Large V3 Turbo',
    groqKey: 'Groq API key', openrouterKey: 'OpenRouter API key', keySaved: 'Key saved. Leave blank to keep it.', keyEmpty: 'Paste an API key', clearKey: 'Remove key',
    fallback: 'Try the other API provider if the first fails', fallbackHint: 'Requires both keys. Local mode never sends audio to an API.',
    language: 'Language', languageHint: 'Leave empty for automatic detection, or enter a two-letter code such as en or fr.',
    saved: 'Saved', ownerOnly: 'The owner manages this core\'s voice engine. You can dictate from any conversation once it is ready.',
    privacy: 'Recordings stay in memory while you dictate. Local temporary audio is deleted after transcription. Nothing is sent as a message until you press Send.',
    limit: 'Up to two minutes per dictation. Switching conversations or leaving the app cancels recording.',
  },
  phone: {
    preparing: 'The app is still preparing offline files. Reload and try again.',
    settingsOffline: 'Settings have not been downloaded yet. Reconnect and open Settings again.',
    dialogOffline: 'This dialog has not been downloaded yet. Reconnect and open it again.',
    heading: 'Phone app', publicUrl: 'Public HTTPS address', urlPlaceholder: 'https://boite.example.com',
    publicUrlHint: 'Use the HTTPS origin configured on your reverse proxy. New pairing links use this address. The proxy must forward the page and /rpc to this core.',
    install: 'Install Boite', installed: 'Boite is running as an installed app.',
    installHint: 'On iPhone, open Share in Safari, then Add to Home Screen. On Android, use Install app or Add to Home screen in the browser menu.',
    httpsRequired: 'This connection uses HTTP. Open Boite through HTTPS to enable offline files and notifications.',
    ownOrigin: 'Open this machine’s own pairing link to enable notifications for it.',
    pairFirst: 'Open a device pairing link before enabling notifications.',
    unsupported: 'This browser does not support push here. On iPhone, add Boite to the Home Screen and open it from its icon.',
    pushHint: 'Receive a notification when an agent finishes, fails or needs your answer, including while Boite is closed.',
    enable: 'Enable notifications', disable: 'Disable notifications', test: 'Send test notification',
    enabled: 'Notifications enabled for this device.', testSent: 'The push service accepted the test notification.',
    denied: 'Notifications were not allowed. You can change this in the browser or device settings.',
    subscriptionFailed: 'The browser did not return a complete push subscription.'
  },
  mobile: {
    settingsDevice: 'This phone', settingsDeviceHint: 'Preferences saved on this device.',
    settingsPhone: 'App & notifications', settingsPhoneHint: 'Installation and alerts from your connected machine.',
    settingsMachinesHint: 'Connect, switch or disconnect a remote machine.',
    settingsAppearanceHint: 'Theme and accent for this phone.',
    settingsRemoteHint: 'Providers, projects and server administration are managed from the desktop app.',
    settingsBack: 'Back to settings',
    navigation: 'Navigation', threads: 'Conversations', activity: 'Activity', project: 'Choose project',
    activityHint: 'Running agents and requests waiting for you.', threadsHint: 'Your conversations across machines.',
    search: 'Find a conversation', unread: 'Unread', noActivity: 'No agents need your attention.', noThreads: 'No matching conversations.'
  },
  machines: {
    heading: 'Machines', local: 'This PC', projects: 'Projects', recent: 'Recent',
    dynamic: 'All machines', recentHint: 'Most recent user message first',
    intro: 'Connect machines to see their projects and threads together. Each machine runs its own agents and files.',
    label: 'Machine name', icon: 'Machine icon', icons: { desktop: 'Desktop', laptop: 'Laptop', server: 'Server', rack: 'Server rack', cloud: 'Cloud', cpu: 'Processor' }, link: 'Pairing link', add: 'Add machine', adding: 'Connecting', connect: 'Connect',
    addHint: 'On the other machine, open Settings, General, Phones and other devices, create a pairing link and paste it here. Turn on Full control there to manage its accounts and settings from this one.',
    labelOptional: 'Name (optional)', labelPlaceholder: 'Build server',
    remove: 'Disconnect', open: 'Open machine', invalidUrl: 'Machine URL must be an HTTP or HTTPS URL without credentials, query or fragment.',
    duplicate: 'This machine is already connected.', noPr: 'No PR', refreshPr: 'Refresh pull request',
    prUnavailable: 'Pull request unavailable', manual: 'Connect with URL and token',
    filter: 'Filter machines', all: 'All machines',
    timeout: 'Machine did not answer within 12 seconds. Check its address and browser origins, then reconnect.',
    browserOrigins: 'Allowed browser origins',
    browserOriginsHint: 'For a browser or phone viewing several machines, add the origin that serves Boite on each remote machine. One exact http(s) origin per line. Desktop connections need no extra origin.',
    agentLinks: 'Agent links', agentLinksHint: 'Let agents on two connected owner machines find each other. Each core exchanges its public signing key and address. No owner token or private key is shared.',
    agentLinksRefresh: 'Refresh agent links', linkAgents: 'Link agents', linkedAgents: 'Linked agent cores', availableAgentLinks: 'Available connections',
    noAgentLinks: 'No other connected owner machine is available.', unlinkAgent: 'Revoke on this machine',
    reciprocalLink: 'Mutual trust', oneSidedLink: 'Trusted on this machine only', publicIdentityHint: 'Set the public HTTPS address of each core in General settings before linking different PCs. Both cores must reach each other. Loopback HTTP works only on the same PC.',
  },
  app: {
    name: 'Boite',
    /** The tag the title bar shows when the core is the dev install. */
    channelDev: 'Dev',
    channelDevTitle: 'The dev channel, on its own data directory',
    loading: 'Starting',
    noEndpointTitle: 'No core to connect to',
    noEndpointBody:
      'Open the pairing link from the desktop app, or set the core URL and token in Settings.',
    openSettings: 'Open settings'
  },

  titlebar: {
    minimize: 'Minimize',
    maximize: 'Maximize',
    restore: 'Restore',
    close: 'Close',
    quitHold: 'Hold Ctrl+Q to quit',
    quitHoldHint: 'or press it twice'
  },

  connection: {
    machine: 'Machine',
    local: 'This PC',
    current: 'Current machine',
    machines: 'machines connected',
    oneMachine: 'machine connected',
    issues: 'need attention',
    manage: 'Manage machines',
    folder: 'Folder',
    browse: 'Browse folders',
    nativeBrowse: 'Choose in Windows Explorer',
    parent: 'Parent folder',
    emptyFolder: 'No subfolders',
    unavailable: 'Could not connect',
    idle: 'Not connected',
    connecting: 'Connecting',
    ready: 'Connected',
    closed: 'Disconnected',
    label: 'Connection'
  },

  threadStatus: {
    idle: 'idle',
    queued: 'queued',
    running: 'running',
    waiting: 'waiting for you',
    error: 'error'
  },

  firstRun: {
    heading: 'Open a project',
    body: 'Pick the folder an agent will work in. Threads live inside it.',
    deviceBody: 'Projects are opened from the app the core runs in. The ones it holds show up here.',
    pick: 'Choose a folder',
    dropHint: 'or drop a folder anywhere in this window',
    typePath: 'Or type the path',
    pathPlaceholder: 'Absolute path of the folder',
    add: 'Open'
  },

  drop: {
    title: 'Drop to add a project',
    body: 'Each folder becomes a project. Files are refused.'
  },

  sidebar: {
    search: 'Search threads',
    newThread: 'New thread',
    newThreadIn: 'New thread in {project}',
    addProject: 'Add a project',
    noProjects: 'No project yet.',
    noThreads: 'No thread yet.',
    noMatch: 'Nothing matches.',
    unread: 'Unread',
    collapse: 'Hide sidebar',
    expand: 'Show sidebar',
    resize: 'Resize the sidebar, double-click to reset',
    loadTitle: 'Live load',
    settings: 'Settings',
    projectMenu: 'Project actions',
    copyPath: 'Copy path',
    copied: 'Copied',
    importSession: 'Import a Claude Code session',
    removeProject: 'Remove from Boite',
    removeProjectTitle: 'Remove {project} from Boite?',
    removeProjectBody: 'Its threads go with it. Files on disk stay where they are.',
    remove: 'Remove',
    threadMenu: 'Thread actions',
    open: 'Open',
    rename: 'Rename',
    retitle: 'Regenerate title',
    retitling: 'Writing a title',
    pin: 'Pin',
    unpin: 'Unpin',
    pinned: 'Pinned',
    archive: 'Archive',
    draft: 'New thread'
  },

  palette: {
    placeholder: 'Search threads, or type a command',
    threads: 'Threads',
    commands: 'Commands',
    empty: 'Nothing matches.',
    hint: 'Enter to open, Esc to close',
    newThread: 'New thread',
    addProject: 'Add a project',
    importSession: 'Import a Claude Code session',
    settings: 'Open settings',
    appearance: 'Appearance settings',
    providers: 'Providers and accounts',
    pair: 'Pair a phone',
    sidebar: 'Toggle the sidebar',
    panel: 'Toggle the right panel',
    trace: 'Show the trace',
    changes: 'Show the changes',
    files: 'Show the files',
    tasks: 'Show the tasks',
    pin: 'Pin this thread',
    unpin: 'Unpin this thread',
    rename: 'Rename this thread',
    retitle: 'Regenerate the title of this thread',
    archive: 'Archive this thread',
    themeDark: 'Theme: dark',
    themeLight: 'Theme: light',
    themeSystem: 'Theme: system'
  },

  /** The import dialog: the sessions Claude Code kept for a project's folder. */
  imports: {
    title: 'Import a session into {project}',
    intro: 'Claude Code sessions started in this folder. One becomes a thread with its history, and the next turn continues it.',
    loading: 'Looking for sessions',
    empty: 'No Claude Code session for this folder.',
    imported: 'Imported',
    importing: 'Importing',
    close: 'Close'
  },

  /** The composer's slash menu: the agent's own commands over Boite's. */
  slash: {
    label: 'Commands',
    agent: 'Agent',
    app: 'Boite',
    empty: 'No command matches',
    model: 'Change the model',
    effort: 'Change the reasoning effort',
    mode: 'Change the permission mode'
  },

  activity: {
    goal: 'Goal',
    loop: 'Loop',
    tasks: 'Tasks',
    taskCount: '{done}/{total} tasks',
    showTasks: 'Show tasks',
    goalDescription: 'Keep working toward an objective',
    loopDescription: 'Repeat a task a set number of times or on a schedule',
    goalUsage: 'Use /goal followed by an objective.',
    loopUsage: 'Use /loop 2 prompt for two iterations, or /loop 5m prompt for a schedule. Choose 1 to 1000 iterations.',
    intervalError: 'Loop intervals must be between 1 second and 24 hours.',
    noAttachments: 'Send images in a message before starting a goal or loop.',
    active: 'Active',
    paused: 'Paused',
    complete: 'Complete',
    pause: 'Pause',
    resume: 'Resume',
    remove: 'Remove',
    finish: 'Mark complete',
    every: 'Every {interval}',
    iterations: '{count} runs',
    iteration: 'Iteration {count}',
    iterationOf: 'Iteration {count} of {total}',
    history: 'Iteration history',
    noHistory: 'No completed iterations yet',
    allTasksDone: 'All tasks completed',
    waitingTasks: 'Waiting for next task',
    stopped: 'Stopped',
    running: 'Running',
    done: 'Done',
    error: 'Failed',
    pending: 'Pending',
    in_progress: 'In progress',
    completed: 'Completed'
  },

  /** The composer's `@` menu: the project's files, the picked one written in as `@path`. */
  mention: {
    label: 'Files',
    empty: 'No file matches',
    more: '{count} more, keep typing'
  },

  notify: {
    done: 'Done',
    failed: 'Failed',
    needsYou: 'Needs your answer'
  },

  permissionMode: {
    default: 'Ask',
    acceptEdits: 'Auto decide',
    bypassPermissions: 'Yolo',
    plan: 'Plan',
    dontAsk: 'Auto-deny'
  },

  permissionModeLong: {
    default: 'Ask before every tool call',
    acceptEdits: 'Accept edits, ask for the rest',
    bypassPermissions: 'Run everything without asking',
    plan: 'Plan only, no changes',
    dontAsk: 'Deny anything that would need asking'
  },

  thread: {
    contextDetails: 'Context',
    contextInput: 'Input',
    contextCache: 'Cached input',
    contextOutput: 'Output',
    contextUsed: 'Used',
    contextFree: 'Available',
    contextNoBreakdown: 'This agent does not report a breakdown.',
    contextNoReading: 'No measurement received from this agent yet.',
    contextMeasured: 'Last measurement',
    none: 'No thread open',
    noneBody: 'Pick one on the left, or start a new one.',
    trace: 'Trace',
    traceHint: 'Processes this thread launched',
    /** The header's button: it shows or hides the panel, whatever surface is in it. */
    panel: 'Panel',
    panelHint: 'The workbench beside this thread',
    cwd: 'Working directory',
    model: 'Model',
    defaultModel: 'Default model',
    renamePlaceholder: 'Thread title',
    /** The draft's own heading, the project's name in the dropdown after it. */
    startIn: 'Start a thread in',
    start: 'Start a thread',
    inWorktree: 'in a worktree',
    inProject: 'in',
    using: 'using',
    onEffort: 'on {effort} effort',
    draftMode: {
      default: 'with approval requests',
      acceptEdits: 'with edits allowed',
      bypassPermissions: 'with all permissions',
      plan: 'in plan mode',
      dontAsk: 'with automatic denial of approval requests'
    },
    changeProject: 'Change project',
    /** The header badge of a thread working in its own worktree; the title says where. */
    branchHint: 'Working in a worktree on this branch',
    /** The context meter's tooltip: `{tokens}` and `{window}` formatted, `{percent}` whole. */
    contextHint: 'Context: {tokens} of {window} tokens ({percent}%) as of the last request',
    contextHintNoWindow: 'Context: {tokens} tokens as of the last request; the agent named no window'
  },

  chat: {
    accepted: 'Request accepted',
    responseStarted: 'Agent activity received',
    working: 'Working',
    writing: 'Writing',
    stopped: 'Stopped',
    toolCall: '1 tool call',
    toolCount: '{count} tool calls',
    inputTokens: '{count} input tokens',
    outputTokens: '{count} output tokens',
    you: 'You',
    assistant: 'Agent',
    system: 'System',
    toolInput: 'Input',
    toolOutput: 'Output',
    toolDocuments: 'Documents',
    /** The chip on a folded card: `1 diff`, `2 diffs`, `1 doc`, `3 docs`. */
    documentChip: {
      diff: '{count} diff',
      diffs: '{count} diffs',
      doc: '{count} doc',
      docs: '{count} docs'
    },
    documentImage: 'What the tool produced',
    /** An image the user sent with the prompt, when it came with no name. */
    imagePart: 'Image sent with the prompt',
    diffHidden: '{count} unchanged lines',
    diffAdded: '+{count}',
    diffRemoved: '-{count}',
    noOutput: 'No output',
    /** Under an expanded tool input that opened cut to six lines. */
    showAll: 'Show all',
    toolStatus: {
      running: 'running',
      done: 'done',
      error: 'error',
      denied: 'denied'
    },
    thinking: 'Thinking',
    thinkingShow: 'Show the reasoning',
    thinkingHide: 'Hide the reasoning',
    /** The divider a compaction draws: `{pre}` and `{post}` formatted token counts. */
    compaction: 'Context compacted, {pre} to {post} tokens',
    compactionNoPost: 'Context compacted from {pre} tokens',
    compactionUnknown: 'Context compacted',
    compactionManual: 'by hand',
    permissionHeading: 'Wants to use',
    allow: 'Allow',
    deny: 'Deny',
    allowed: 'Allowed',
    denied: 'Denied',
    questionHeading: 'Asks you',
    questionTextLabel: 'Your own answer',
    questionTextPlaceholder: 'Type an answer',
    questionAnswer: 'Answer',
    questionAnswered: 'Answered',
    questionCancelled: 'The turn ended before this was answered',
    streaming: 'writing',
    jumpToLatest: 'Jump to latest',
    /** The one line at the top of the timeline while an older page is being fetched. */
    loadingOlder: 'Loading earlier messages',
    outline: 'Messages in this conversation',
    messageGroup: 'Browse {count} messages',
    earlierMessages: 'Load earlier messages',
    /** The rail's own chevrons: they move its window over the conversation without moving the timeline. */
    outlineEarlier: 'Show earlier messages in the rail',
    outlineLater: 'Show later messages in the rail',
    goToMessage: 'Go to message {number}: {text}',
    copy: 'Copy',
    copied: 'Copied',
    error: 'Error'
  },

  coordination: {
    options: 'Advanced settings',
    heading: 'Communication settings', off: 'Off', brief: 'Brief', team: 'Team',
    summaryOff: 'Other agents cannot contact this thread.', summaryBrief: 'Short handoffs with up to 6 sends and 2 wake turns each hour.',
    summaryTeam: 'Team coordination with up to 40 sends and 12 wake turns each hour.',
    ownerOnly: 'Only the owner can change coordination. This device can inspect the directory and exchanges.',
    resources: 'Resources and responsibilities', resourcesPlaceholder: 'What this agent owns, can answer, or should avoid',
    remote: 'Across projects and machines', remoteHint: 'Share this thread\'s title and declared resources with opted-in agents in other projects and trusted machines. Both threads must enable this.',
    pause: 'Pause coordination', resume: 'Resume coordination', paused: 'Paused',
    sends: '{used} of {limit} sends this hour', wakes: '{used} of {limit} wake turns this hour', receives: 'Recipients accept up to {limit} letters each hour.',
    directory: 'Authorized contacts', refresh: 'Refresh', directoryEmpty: 'No opted-in thread in this project is available.', unavailable: 'Unavailable contacts',
    exchanges: 'Agent exchanges', noExchanges: 'No agent exchange yet.', details: 'Show exchange',
    from: 'From {title} on {machine}', to: 'To {title}', reply: 'Reply to {id}',
    receivedFrom: 'Received from', sentTo: 'Your agent sent to', incoming: 'Incoming', outgoing: 'Outgoing',
    receivedStatus: 'Received',
    noReceipt: 'Delivered means submitted to the recipient agent. Agent protocols provide no read receipt.',
    warning: 'Coordination warning',
    status: {
      queued: 'Queued in the outbox', received: 'Received by the recipient core', delivered: 'Submitted to the recipient agent',
      uncertain: 'Submission outcome uncertain. Boite will not replay it.', expired: 'Expired', rejected: 'Rejected'
    },
    bubbleStatus: {
      queued: 'Waiting', received: 'Waiting', delivered: 'Sent', uncertain: 'Unconfirmed', expired: 'Expired', rejected: 'Failed'
    }
  },

  composer: {
    options: 'Message options',
    switchTitle: 'Switch a {tokens} token thread to {provider}?',
    switchBody: '{provider} starts a new session and receives excerpts of the opening and of the most recent exchanges, about 20k tokens. The rest is lost to it. Compacting first changes nothing.',
    switchConfirm: 'Switch',
    switchCancel: 'Stay on {provider}',
    placeholder: 'Message {provider} in {project}',
    placeholderNoProject: 'Message the agent',
    send: 'Send',
    stop: 'Stop',
    queued: 'Sent when the current turn ends',
    picker: 'Provider and model',
    models: 'Models',
    searchModels: 'Search models',
    noModels: 'No model matches',
    legacyModels: 'Legacy models',
    refreshModels: 'Refresh models',
    probing: "Reading the agent's models",
    notInstalled: 'Not installed on this machine',
    installInSettings: 'Install in Settings',
    reasoning: 'Reasoning',
    effortTitle: 'Reasoning effort',
    speed: 'Response speed',
    standardSpeed: 'Standard speed',
    effortHint: 'Drag or use the arrow keys to choose a level.',
    favorites: 'Favorites',
    favorite: 'Add to favorites',
    unfavorite: 'Remove from favorites',
    favoritesEmpty: 'Star a model to find it here.',
    favoriteUnavailable: 'This favorite is no longer offered by the account. Choose another model.',
    compact: 'Compact context',
    compactBusy: 'Wait for the current turn to finish',
    compactUnavailable: 'This agent has not advertised context compaction',
    compactNoSession: 'Send a message before compacting',
    contextUnknown: 'Context usage not reported',
    newBadge: 'new',
    lockedHint: 'A thread keeps its provider and account',
    mode: 'Permissions',
    model: 'Model',
    unavailable: 'not installed',
    noAccount: 'no account',
    noProvider: 'No provider',
    hint: 'Enter to send, Shift+Enter for a new line',
    /** The draft's worktree switch, off and on. */
    worktree: 'Worktree',
    worktreeOff: 'Start in a git worktree on its own branch',
    worktreeOn: 'Starts in a git worktree on its own branch',
    /** Images sent with the prompt: the strip above the box and what refuses one. */
    attach: 'Attach files',
    editQueued: 'Edit this pending message, or press Up in the empty composer',
    attachReadError: '{name} could not be read.',
    attachRemove: 'Remove {name}',
    attachAlt: 'Attached file',
    attachUnnamed: 'the attachment',
    attachFormat: '{name} is {type}, and an image must be one of {formats}.',
    attachTooLarge: '{name} is too big: a file may weigh {max} at most.',
    attachTooMany: 'A turn carries at most {max} files, so {name} was left out.',
    attachNoImages: '{provider} takes no images: send the prompt without them.'
  },

  /** The panel on the right of the chat: its tab strip, its launcher, its surfaces. */
  rightPanel: {
    label: 'Panel',
    toggle: 'Show or hide the panel',
    resize: 'Resize the panel, double-click to reset',
    maximize: 'Maximize the panel',
    restore: 'Restore the panel',
    newSurface: 'Open a surface',
    scrollLeft: 'Scroll the tabs left',
    scrollRight: 'Scroll the tabs right',
    close: 'Close',
    closeTab: 'Close {title}',
    closeOthers: 'Close others',
    closeToRight: 'Close to the right',
    closeAll: 'Close all',
    trace: 'Trace',
    traceHint: 'Processes this thread launched',
    browser: 'Browser',
    browserHint: 'A page beside the thread',
    changes: 'Changes',
    changesHint: 'What the working tree has that HEAD does not',
    files: 'Files',
    filesHint: "The thread's working directory",
    file: 'File',
    tasks: 'Tasks',
    tasksHint: "The goal, the agent's tasks and the project's todos",
    desktopOnly: 'Only in the desktop app',
    ownerOnly: "Only in the owner's app",
    launcher: 'Open a surface in this panel',
    untitled: 'Browser'
  },

  /** The changes surface: `git status` of the thread's working directory. */
  changes: {
    clean: 'Working tree clean',
    noBranch: 'No branch',
    ahead: '{count} ahead',
    behind: '{count} behind',
    count: '{count} changed',
    oneCount: '1 changed',
    staged: 'Staged',
    stagedShort: 'S',
    binary: 'Binary file, nothing to show line by line',
    truncated: 'This file was cut short: the diff below is not the whole file.',
    pick: 'Pick a file to see its diff',
    loading: 'Reading the working tree',
    renamedFrom: 'Renamed from {path}',
    status: {
      added: 'Added',
      modified: 'Modified',
      deleted: 'Deleted',
      renamed: 'Renamed',
      copied: 'Copied',
      untracked: 'Untracked',
      conflict: 'Conflict'
    }
  },

  /** The tasks surface: the thread's activity, the agent's tasks, the project's todos. */
  tasks: {
    goalSection: 'Goal and loop',
    noActivity: 'No goal and no loop on this thread',
    nextRun: 'Next run {time}',
    iterations: '{count} iterations',
    agentSection: 'Agent tasks',
    noTasks: 'The agent has reported no task list',
    todoSection: 'Project todos',
    noTodos: 'No todo on this project',
    addPlaceholder: 'Add a todo',
    add: 'Add',
    // The chip on a claimed card. Short enough to leave the card's own text
    // readable on a narrow panel; the whole sentence is its tooltip.
    awaiting: 'Awaiting you',
    awaitingHint: 'This card waits on your confirmation',
    markOpen: 'Move back to open',
    markClaimed: 'Mark it waiting on you',
    markDone: 'Confirm it is done',
    removeTodo: 'Remove this todo',
    collapse: 'Fold this section',
    expand: 'Unfold this section'
  },

  /** The file tree and the file viewer, the two surfaces reading the working directory. */
  files: {
    tree: 'Files of the working directory',
    noRoot: 'No working directory',
    filter: 'Filter',
    filterHint: 'Narrow the rows already loaded',
    reading: 'Reading this directory',
    empty: 'This directory is empty',
    noMatch: 'No loaded row matches',
    failed: 'This directory could not be read. {reason}',
    capped: 'Only the first {count} entries of this directory are listed.',
    expandRow: 'Unfold this directory',
    collapseRow: 'Fold this directory',
    openRow: 'Open this file',
    // The viewer and the editor, one file per tab.
    readFailed: 'This file could not be read. {reason}',
    writeFailed: 'This file could not be saved. {reason}',
    readingFile: 'Reading this file',
    noFile: 'This tab carries no path',
    truncated: 'This file was cut short at its size limit, so what is below is not the whole file and cannot be saved.',
    readOnly: "Saving a file is the owner's, so this one opens read only.",
    save: 'Save',
    saving: 'Saving',
    unsaved: 'Unsaved changes',
    discardOne: 'Close {name} without saving?',
    discardMany: 'Close {count} files without saving?',
    discardBody: 'What was typed since the last save is lost.',
    discardConfirm: 'Close without saving',
    editorLabel: 'File contents',
    lineOf: 'Line {line}',
    zoomIn: 'Zoom in',
    zoomOut: 'Zoom out',
    fit: 'Fit',
    actual: '1:1',
    natural: '{width} x {height}',
    picture: 'The picture of this file',
    download: 'Download this file',
    binary: 'Nothing here reads as text.'
  },

  browser: {
    back: 'Back',
    forward: 'Forward',
    reload: 'Reload',
    urlPlaceholder: 'Search or enter URL',
    openExternal: 'Open in the system browser',
    slotEmpty: 'The page opens here once the shell provides the webview'
  },

  trace: {
    exact: 'All child processes tracked',
    limited: 'Limited process tracking',
    finished: 'Finished',
    parent: 'Parent PID',
    cpuTime: 'CPU time',
    currentMemory: 'Memory now',
    active: 'active',
    recorded: 'recorded',
    exe: 'Executable',
    pid: 'PID',
    started: 'Started',
    duration: 'Duration',
    cpu: 'CPU',
    memory: 'Peak memory',
    io: 'I/O',
    exit: 'Exit',
    live: 'live',
    empty: 'This thread has launched no process yet.',
    modeLabel: 'Trace mode'
  },

  protection: {
    intro: 'Keep agents from interrupting your work and control what they use.',
    quiet: 'Peace and quiet',
    limits: 'Resource limits',
    tasks: 'Task manager',
    windows: 'Focus, audio and resource limits apply on the Windows host.',
  },
  resources: {
    heading: 'Protection',
    empty: 'No thread is using anything right now.',
    live: 'Live processes',
    totals: 'Totals',
    processes: 'processes',
    killTree: 'Kill tree',
    killConfirm: 'Kill every process of this thread?',
    killConfirmYes: 'Kill',
    killConfirmNo: 'Cancel',
    killed: 'Killed'
  },

  /** A provider whose files Boite downloads itself. */
  install: {
    action: 'Install',
    update: 'Update',
    retry: 'Try again',
    repair: 'Reinstall',
    cancel: 'Cancel',
    remove: 'Uninstall',
    removeTitle: 'Uninstall {provider}?',
    removeBody: 'The files Boite downloaded go with it. Your accounts stay, and it can be installed again later.',
    removeConfirm: 'Uninstall',
    removeCancel: 'Keep',
    absent: 'Not installed · {size}',
    downloading: 'Downloading · {percent}',
    verifying: 'Checking the download',
    extracting: 'Unpacking',
    upToDate: 'Installed by Boite · version {version}',
    updateAvailable: 'Version {installed} · {available} is available',
    progress: 'Download progress'
  },

  accounts: {
    heading: 'Providers',
    login: 'Sign in',
    loginStarting: 'Starting the sign-in',
    loginOpen: 'Open the sign-in page',
    loginHint: 'Finish in your browser. This row turns ready on its own.',
    loginInputPlaceholder: 'Paste the code the page gives you, if it gives one',
    loginRedirectPlaceholder: 'On another device? Paste the localhost address the page ends on',
    loginSend: 'Send',
    loginCancel: 'Cancel',
    remove: 'Remove',
    removeTitle: 'Remove {account}?',
    removeBody: 'This signs the account out of Boite and deletes its files. Accounts used by a thread cannot be removed.',
    removeDefaultBody: 'Boite stops using this login. It stays signed in on your computer. Accounts used by a thread cannot be removed.',
    status: {
      unknown: 'unknown',
      ok: 'ok',
      unauthenticated: 'not signed in',
      error: 'error'
    }
  },

  usage: {
    heading: 'Usage',
    note: 'On a subscription this cost is an API equivalent, not money spent.',
    thread: 'Thread',
    input: 'Input',
    output: 'Output',
    cacheRead: 'Cache read',
    cacheWrite: 'Cache write',
    cost: 'API equivalent',
    total: 'Total',
    empty: 'No token spent yet.',
    today: 'today',
    intro: 'What the agents spent through Boite, per day, provider and model. Tokens include cache reads and writes.',
    range: 'Range',
    days: '{days} days',
    metric: 'Measure',
    metrics: { tokens: 'Tokens', cost: 'API cost', turns: 'Turns' },
    totalOf: {
      tokens: 'Tokens, last {days} days',
      cost: 'API equivalent, last {days} days',
      turns: 'Turns, last {days} days'
    },
    summary: '{turns} turns · {tokens} tokens · {cost} API equivalent',
    overview: 'Overview',
    chart: 'Per day',
    chartLabel: '{metric} per day and provider. Use the arrow keys to read each day.',
    share: '{percent} of the total',
    breakdown: 'Breakdown',
    byModel: 'By model',
    byDay: 'By day',
    model: 'Model',
    day: 'Day',
    turns: 'Turns',
    tokens: 'Tokens',
    cache: 'Cache',
    noPrice: 'no price',
    defaultModel: 'Default model',
    other: 'Other',
    threads: 'Top threads',
    threadTurns: '{turns} turns',
    untitled: 'Untitled thread',
    archived: 'Archived',
    emptyRange: 'No turn finished in the last {days} days.',
    unpriced: '{providers} report no price, so their turns add nothing to the cost.',
    unreported: '{count} turns reported no usage. They count as turns only.',
    limits: 'Limits',
    limitsIntro: 'Subscription windows as each provider last reported them.',
    limitsOwner: 'Subscription limits are read on the computer that runs Boite. Open this page there to see them.',
    limitsEmpty: 'No provider reports a limit yet. Connect one in Providers.',
    notMonitored: 'Not monitored: {accounts}',
    refresh: 'Refresh usage',
    loading: 'Reading usage',
    failed: 'Could not read usage: {error}',
    phoneHint: 'Tokens and API cost per day, provider and model on the connected machine.'
  },

  settings: {
    heading: 'Settings',
    modelDefaults: 'Default models',
    modelDefaultsHint: 'Model and reasoning effort for new threads, per provider. Saved on this device. Existing threads keep their choices.',
    modelDefaultUnavailable: '{provider} does not offer the default model {model} on this account. Choose an available model in the picker or change the default in Settings.',
    tabs: {
      general: 'General',
      appearance: 'Appearance',
      keyboard: 'Keyboard',
      accounts: 'Providers',
      plugins: 'Plugins',
      usage: 'Usage',
      resources: 'Protection',
      experiments: 'Experiments'
    },
    back: 'Back to threads',
    projects: 'Projects',
    projectsHint: 'Right-click a project in the sidebar to remove it from Boite.',
    projectsDevice: 'Folders are added and removed from the app the core runs in.',
    theme: 'Theme',
    accent: 'Accent colour',
    accentHint: 'Reasoning, buttons, links and focus indicators',
    accentCustom: 'Custom accent colour',
    accentNames: ['Blue', 'Violet', 'Rose', 'Orange', 'Amber', 'Green', 'Teal'],
    themeSystem: 'System',
    themeDark: 'Dark',
    themeLight: 'Light',
    themeGrain: 'Grain',
    experiments: {
      intro: 'These are unfinished. They may change shape or leave in a later build.'
    },
    material: 'Window material',
    materialHint: 'What Windows draws behind the window',
    materialAcrylic: 'Acrylic',
    materialMica: 'Mica',
    materialSolid: 'Solid',
    connection: 'Connection',
    localCore: 'This app runs on the core it started on this computer.',
    coreAt: 'Connected to the core at {url}.',
    pairingLink: 'Pairing link',
    pairingLinkPlaceholder: 'http://host:port/?grant=',
    pair: 'Pair',
    pairHint:
      'Paste a link minted by the other core, from its own Settings or with boite-core pair --owner on the machine it runs on. The key it becomes stays on this computer.',
    useLocal: "Use this computer's core",
    useLocalHint: 'The remembered cores below stay remembered.',
    environments: 'Remembered cores',
    environmentsHint: 'Paired or connected cores stay here. Switching back needs no new link: the key stays until revoked there or forgotten here.',
    envCurrent: 'current',
    envSwitch: 'Switch',
    envForget: 'Forget',
    manual: 'Core URL and token',
    coreUrl: 'Core URL',
    token: 'Token',
    connect: 'Connect',
    scheduler: 'Scheduler',
    maxConcurrentTurns: 'Max concurrent turns',
    perAccountConcurrency: 'Per account concurrency',
    warmProcessMinutes: 'Warm process minutes',
    listenOnLan: 'Listen on the LAN so a phone can pair',
    listenOnLanHint: 'Takes effect the next time the core starts, and a --host or --lan flag wins over it',
    agentCpuCapPercent: 'CPU cap for all agents, percent of the machine (0 = none, Windows)',
    threadMemoryCapMb: 'Memory cap per thread tree, MB (0 = none, Windows)',
    background: 'Background',
    closeToTray: 'Keep Boite running when the window closes',
    closeToTrayHint: 'Off by default. Enable to hide to the notification area and keep turns running. Quit always stops Boite.',
    notifications: 'Notify me when a thread finishes or asks something',
    notificationsHint: 'A toast for a thread you are not looking at, or when Boite is not the window in front. This machine only.',
    notificationsDenied: 'Notifications are blocked for Boite on this system; allow them in its settings.',
    focusGuard: 'Keep agent windows out of the foreground',
    focusGuardHint: 'Windows an agent opens are sent behind Boite instead of taking your focus',
    muteAgents: 'Mute agent audio',
    muteAgentsHint: 'Sounds an agent process plays never reach your speakers',
    save: 'Save',
    saved: 'Saved',
    core: 'Core',
    version: 'Version',
    protocol: 'Protocol',
    os: 'OS',
    pid: 'PID',
    dataDir: 'Data directory',
    endpoint: 'Endpoint',
    noCore: 'Not connected to a core.',
    pairing: {
      heading: 'Phones and other devices',
      intro: 'A pairing link opens Boite on another device with a key of its own. It works once and for ten minutes.',
      mint: 'New pairing link',
      copy: 'Copy link',
      expires: 'Works once, until {time}',
      qr: 'The pairing link as a QR code',
      scan: 'Scan the code with the phone, or open the link on it.',
      lanHint: 'The core listens on this machine only: turn on the LAN switch above, then restart it, before a phone can reach this link.',
      devices: 'Paired devices',
      noDevices: 'No device paired yet.',
      thisDevice: 'this device',
      lastSeen: 'seen {when}',
      revoke: 'Revoke',
      revokeTitle: 'Revoke this device?',
      revokeBody: 'It disconnects now and its key opens nothing any more. Pair it again with a new link.',
      paired: 'This device is paired with a key of its own. Pairing links are made from the desktop app.',
      owner: 'Full control',
      ownerHint:
        'For another computer of yours: its key drives this core as you do, accounts, projects and settings included. Leave it off for a phone.',
      ownerTag: 'full control',
      pasteOwner: 'Paste it in Settings, General, on the other computer.'
    }
  },

  /** The Keyboard settings page: the table, the file, and the commands the palette has no word for. */
  keyboard: {
    heading: 'Shortcuts',
    intro: 'Click a shortcut and press the keys you want instead. The change applies at once, on every window of this machine.',
    search: 'Filter commands',
    groups: { general: 'General', surfaces: 'Side panel', thread: 'Thread and composer', theme: 'Theme' },
    record: 'Press the keys',
    change: 'Change the shortcut',
    reset: 'Back to the default',
    resetAll: 'Reset all',
    clear: 'Remove the shortcut',
    conflict: '{chord} already runs "{command}". Move it here?',
    replace: 'Move it here',
    needsModifier: 'Hold Ctrl, Alt or Win with the key. A key alone, or with Shift only, is typing.',
    noMatch: 'No command matches.',
    file: 'Edit the file by hand',
    fileHint:
      'A JSON object of command ids to chords, "mod+shift+k" style, or null to take a key away. mod is Ctrl here and Cmd on a Mac. Only the entries you name change; the rest keep their default.',
    example: 'Example',
    command: 'Command',
    id: 'Id',
    chord: 'Chord',
    none: 'Not set',
    custom: 'changed',
    problems: 'Refused',
    problemsHint: 'These lines of the file were not applied. Fix them and save; the rest of the file is in use.',
    commands: {
      palette: 'Open the command palette',
      browser: 'Open the browser surface',
      changes: 'Open the changes surface',
      files: 'Open the file tree',
      tasks: 'Open the tasks surface',
      closeSurface: 'Close the active surface',
      stash: 'Stash the composer text, or take it back',
      sendAndDraft: 'Send and open a new draft',
      pin: 'Pin or unpin this thread'
    }
  },

  experiments: {
    themeGrain: {
      title: 'Grain theme',
      hint: 'A grainy ground fading from light grey at the top left to black at the bottom right'
    },
    sessionImport: {
      title: 'Claude Code session import',
      hint: 'Turn a session started in the terminal into a thread, from the project menu and the palette'
    }
  },

  quotas: {
    trayHeading: 'Usage',
    trayIntro: 'Subscription limits',
    names: { claude: 'Claude', codex: 'Codex', antigravity: 'Antigravity', grok: 'Grok', opencode: 'OpenCode Go' },
    off: 'Off',
    noReading: 'Unavailable',
    notConnected: 'Not connected',
    autoConnect: 'Uses your connected account',
    cliSource: 'Antigravity CLI account',
    cliHint: 'Uses the account signed in through agy on this computer. Install Antigravity CLI 1.1.11 or later and sign in once, then enable monitoring below. Separate from Boite’s isolated Antigravity accounts.',
    connectHint: 'Connect {provider} once in Providers. Usage appears here automatically.',
    connect: 'Connect account',
    noReset: 'Reset time not reported',
    heading: 'Provider quotas',
    intro: 'Subscription limits reported by your providers. Separate from tokens used in Boite.',
    remaining: '{percent}% left',
    resets: 'Resets {time}',
    checked: 'Updated {time}',
    stale: 'Last successful reading',
    empty: 'Connect a provider to see its subscription limits.',
    unsupported: 'This provider does not expose subscription quotas here.',
    disabled: 'Quota monitoring is off for this account.',
    loading: 'Reading provider limits',
    monitor: 'Monitor subscription quotas',
    providers: 'Manage providers',
    unavailable: 'No quota reading available.',
    refresh: 'Refresh quotas',
    quit: 'Quit Boite',
  },
  harnessUpdates: {
    heading: 'Agent updates',
    intro: 'Each machine checks its own agents every six hours and updates them where they run.',
    auto: 'Update agents automatically',
    autoHint: 'This machine updates an agent as soon as none of its threads is running, with nobody connected',
    check: 'Check now',
    checking: 'Checking',
    available: (name: string, version: string) => `${name} ${version} is available`,
    availableShort: 'Update available',
    installed: (version: string) => `Installed: ${version}`,
    on: (machine: string) => `On ${machine}`,
    update: 'Update',
    skip: 'Skip',
    retry: 'Try again',
    updating: (name: string) => `Updating ${name}`,
    updatingHint: 'Its threads stay as they are. The next turn starts the new version.',
    failed: (name: string) => `${name} did not update`,
    upToDate: 'Up to date',
    unknown: 'Checks by itself',
    runUpdater: 'Run its updater',
    skipped: (version: string) => `${version} skipped`,
    unskip: 'Offer it again',
    none: 'No agent on this machine has an updater Boite can run.',
    route: { managed: 'Installed by Boite', self: 'Your own install' }
  },
  providerSettings: {
    heading: 'Providers',
    intro: 'Install an agent, sign in, done. An agent already signed in on this computer is picked up on its own.',
    step: {
      installing: 'Installing',
      install: 'Not installed',
      repair: 'Installed files are missing',
      manual: 'Not installed',
      'signing-in': 'Signing in',
      'sign-in': 'Not signed in',
      external: 'Not signed in',
      ready: 'Ready'
    },
    readyMore: '{identity} and {count} more',
    accountsCount: '{count} accounts',
    thenSignIn: 'Sign-in starts when the download finishes.',
    manualHint: '{provider} comes with its own installer. Run it, then come back: Boite finds it on its own.',
    externalHint: '{provider} signs in from its own app. Sign in there, then check again.',
    setup: 'Install guide',
    refresh: 'Check again',
    details: 'Details',
    isolated: 'Signed in through Boite',
    default: 'Your command-line login',
    reconnect: 'Sign in again',
    check: 'Check',
    models: '{count} models available',
    addAccount: 'Add another account',
    useCli: 'Use my command-line login',
    executable: 'Runs from',
    accounts: 'Accounts',
    noAccounts: 'No account yet.',
    installation: 'Installation',
    version: 'Version'
  },
  plugins: {
    heading: 'Plugins',
    intro: 'Plugins add features to Boite. Each one is a program that runs on the machine hosting your core, downloaded over https and checked against the SHA-256 its manifest publishes.',
    installedHeading: 'Installed',
    installedEmpty: 'No plugin installed yet. Install a recommended one or add one from a git URL.',
    recommendedHeading: 'Recommended',
    recommendedAllInstalled: 'Every recommended plugin is installed.',
    recommendedBy: 'Recommended by Boite',
    install: 'Install',
    update: 'Update to {version}',
    retry: 'Try again',
    reinstall: 'Reinstall',
    remove: 'Uninstall',
    stateInstalled: 'Installed',
    stateAvailable: 'Not installed',
    stateInstalling: 'Downloading and checking',
    stateError: 'Install failed',
    stateRejected: 'Refused by Boite',
    updateAvailable: '{version} available',
    source: 'Source code',
    atCommit: '{ref} at {commit}',
    pools: 'Account pools',
    empty: 'No saved account in this pool.',
    add: 'Save current CLI login',
    switch: 'Use this account',
    forget: 'Forget account',
    active: 'Active',
    refresh: 'Refresh',
    removeTitle: 'Uninstall {name}?',
    removeBody: 'Deletes the plugin\'s folder in Boite\'s data directory, which is everything its install wrote. What the program saved elsewhere, such as its saved logins, stays where it is.',
    switchTitle: 'Change the CLI login?',
    switchBody: 'This changes the provider\'s default CLI login for future turns, including outside Boite. Isolated Boite accounts keep their own login.',
    forgetTitle: 'Forget this saved login?',
    forgetBody: 'Removes this login from the plugin\'s pool.',
    cliScope: 'These are the CLI account pools. They are separate from isolated accounts connected in Providers.',
    addHeading: 'Add from a git URL',
    addHint: 'Paste the https URL of a git repository with a boite-plugin.json at its root. Boite reads the manifest and shows what it would download before anything is installed.',
    urlLabel: 'Repository URL',
    urlPlaceholder: 'https://github.com/owner/repo',
    refLabel: 'Branch, tag or commit',
    refPlaceholder: 'Default branch',
    inspect: 'Read manifest',
    inspecting: 'Reading',
    previewSource: 'Source',
    previewReplaces: 'Replaces',
    previewDownloads: 'Downloads',
    previewDigest: 'SHA-256',
    previewRuns: 'Runs',
    previewPools: 'Account pools',
    trust: 'This program runs with your permissions on the machine hosting your core. Install it only if you trust whoever publishes it.',
    confirmAdd: 'Install {name}',
    refusedTitle: 'Boite refused this plugin',
    refusedFile: 'File',
    refusedField: 'Field',
    refusedExpected: 'Expected',
    dismiss: 'Dismiss',
  },

  time: {
    now: 'now'
  },

  errors: {
    prefix: 'Error',
    activityUnsupported: 'This core does not support goals or loops. Update Boite on {machine}, then reconnect. Your command has not been sent.',
    pullRequestUnsupported: 'Update Boite on the machine hosting this thread to show its pull request. This core does not support pull request lookup yet.',
    noEndpoint: 'No core endpoint could be resolved.',
    connect: 'Could not connect to the core.',
    clipboard: 'The clipboard refused the text.',
    revoked: 'This device was revoked from the desktop app. Open a new pairing link to connect again.',
    pairingLink: 'That is not a pairing link: it needs an http or https address carrying a grant.'
  },

  units: {
    bytes: 'B',
    kilobytes: 'kB',
    megabytes: 'MB',
    gigabytes: 'GB',
    milliseconds: 'ms',
    seconds: 's',
    minutes: 'min',
    hours: 'h',
    tokens: 'tokens'
  },

  common: {
    none: 'none',
    unknown: 'unknown',
    yes: 'yes',
    no: 'no',
    close: 'Close',
    refresh: 'Refresh',
    dismiss: 'Dismiss',
    cancel: 'Cancel',
    confirm: 'Confirm'
  }
} as const;

export type Strings = typeof strings;

/** `fill('New thread in {project}', { project: 'boite' })`. */
export function fill(template: string, values: Record<string, string>): string {
  return template.replace(/\{(\w+)\}/g, (match, key: string) => values[key] ?? match);
}
