/*
 * Le catalogue français, calqué sur `strings.ts`.
 *
 * Le type vient de l'anglais : une clé ajoutée là-bas et pas ici arrête
 * `svelte-check`, et une clé qui manquerait quand même s'affiche en anglais
 * plutôt qu'en chemin pointé (`lib/i18n.svelte.ts`). Les accolades sont des
 * emplacements remplis par `fill`, leur nom ne se traduit pas.
 */

import type { Messages } from './i18n.svelte';

export const fr: Messages = {
  phone: {
    preparing: "L'application prépare encore ses fichiers hors ligne. Rechargez la page et réessayez.",
    settingsOffline: "Les réglages ne sont pas encore téléchargés. Reconnectez-vous et rouvrez les réglages.",
    heading: 'Application mobile', publicUrl: 'Adresse HTTPS publique', urlPlaceholder: 'https://boite.example.com',
    publicUrlHint: "Utilisez l'origine HTTPS configurée sur votre reverse proxy. Les nouveaux liens d'appairage passeront par cette adresse. Le proxy doit transmettre la page et /rpc à ce cœur.",
    install: 'Installer Boite', installed: "Boite tourne comme application installée.",
    installHint: "Sur iPhone, ouvrez Partager dans Safari, puis Sur l'écran d'accueil. Sur Android, utilisez Installer l'application dans le menu du navigateur.",
    httpsRequired: "Cette connexion est en HTTP. Ouvrez Boite en HTTPS pour activer les fichiers hors ligne et les notifications.",
    ownOrigin: "Ouvrez le lien d'appairage de cette machine pour y activer les notifications.",
    pairFirst: "Ouvrez un lien d'appairage d'appareil avant d'activer les notifications.",
    unsupported: "Ce navigateur ne gère pas les notifications push ici. Sur iPhone, ajoutez Boite à l'écran d'accueil et ouvrez-le depuis son icône.",
    pushHint: "Recevoir une notification quand un agent termine, échoue ou attend votre réponse, y compris quand Boite est fermé.",
    enable: 'Activer les notifications', disable: 'Désactiver les notifications', test: 'Envoyer une notification de test',
    enabled: 'Notifications activées pour cet appareil.', testSent: 'Le service push a accepté la notification de test.',
    denied: "Les notifications ont été refusées. Vous pouvez changer ça dans les réglages du navigateur ou de l'appareil.",
    subscriptionFailed: "Le navigateur n'a pas renvoyé un abonnement push complet."
  },
  mobile: {
    settingsDevice: 'Ce téléphone', settingsDeviceHint: 'Préférences enregistrées sur cet appareil.',
    settingsPhone: 'Application et notifications', settingsPhoneHint: 'Installation et alertes de la machine connectée.',
    settingsMachinesHint: 'Connecter, changer ou déconnecter une machine distante.',
    settingsAppearanceHint: 'Thème et couleur pour ce téléphone.',
    settingsRemoteHint: "Les fournisseurs, les projets et l'administration du serveur se gèrent depuis l'application de bureau.",
    settingsBack: 'Retour aux réglages',
    navigation: 'Navigation', threads: 'Conversations', activity: 'Activité', project: 'Choisir un projet',
    activityHint: 'Agents en cours et demandes qui vous attendent.', threadsHint: 'Vos conversations, toutes machines confondues.',
    search: 'Trouver une conversation', unread: 'Non lu', noActivity: "Aucun agent n'attend votre réponse.", noThreads: 'Aucune conversation ne correspond.'
  },
  machines: {
    heading: 'Machines', local: 'Ce PC', projects: 'Projets', recent: 'Récent',
    dynamic: 'Toutes les machines', recentHint: 'Message le plus récent en premier',
    intro: "Connectez des machines pour voir leurs projets et leurs conversations ensemble. Chaque machine exécute ses propres agents sur ses propres fichiers.",
    label: 'Nom de la machine', icon: 'Icône de la machine', icons: { desktop: 'Ordinateur fixe', laptop: 'Portable', server: 'Serveur', rack: 'Baie', cloud: 'Cloud', cpu: 'Processeur' }, link: "Lien d'appairage", add: 'Ajouter une machine', adding: 'Connexion',
    remove: 'Déconnecter', open: 'Ouvrir la machine', invalidUrl: "L'URL d'une machine doit être une adresse HTTP ou HTTPS, sans identifiants, sans requête ni fragment.",
    duplicate: 'Cette machine est déjà connectée.', noPr: 'Pas de PR', refreshPr: 'Actualiser la pull request',
    prUnavailable: 'Pull request indisponible', manual: 'Connecter avec une URL et un jeton',
    filter: 'Filtrer les machines', all: 'Toutes les machines',
    timeout: "La machine n'a pas répondu en 12 secondes. Vérifiez son adresse et ses origines navigateur, puis reconnectez-la.",
    browserOrigins: 'Origines navigateur autorisées',
    browserOriginsHint: "Pour un navigateur ou un téléphone qui regarde plusieurs machines, ajoutez sur chaque machine distante l'origine qui sert Boite. Une origine http(s) exacte par ligne. Les connexions de bureau n'ont besoin d'aucune origine en plus.",
  },
  app: {
    name: 'Boite',
    channelDev: 'Dev',
    channelDevTitle: 'Le canal dev, sur son propre répertoire de données',
    loading: 'Démarrage',
    noEndpointTitle: 'Aucun cœur à joindre',
    noEndpointBody:
      "Ouvrez le lien d'appairage depuis l'application de bureau, ou renseignez l'URL du cœur et son jeton dans les réglages.",
    openSettings: 'Ouvrir les réglages'
  },

  titlebar: {
    minimize: 'Réduire',
    maximize: 'Agrandir',
    restore: 'Restaurer',
    close: 'Fermer',
    quitHold: 'Maintenez Ctrl+Q pour quitter',
    quitHoldHint: 'ou appuyez deux fois'
  },

  connection: {
    machine: 'Machine',
    local: 'Ce PC',
    current: 'Machine actuelle',
    machines: 'machines connectées',
    oneMachine: 'machine connectée',
    issues: 'à vérifier',
    manage: 'Gérer les machines',
    folder: 'Dossier',
    browse: 'Parcourir les dossiers',
    nativeBrowse: "Choisir dans l'explorateur Windows",
    parent: 'Dossier parent',
    emptyFolder: 'Aucun sous-dossier',
    unavailable: 'Connexion impossible',
    idle: 'Non connecté',
    connecting: 'Connexion',
    ready: 'Connecté',
    closed: 'Déconnecté',
    label: 'Connexion'
  },

  threadStatus: {
    idle: 'au repos',
    queued: 'en attente',
    running: 'en cours',
    waiting: 'vous attend',
    error: 'erreur'
  },

  firstRun: {
    heading: 'Ouvrir un projet',
    body: "Choisissez le dossier dans lequel un agent travaillera. Les conversations vivent dedans.",
    deviceBody: "Les projets s'ouvrent depuis l'application où tourne le cœur. Ceux qu'il détient apparaissent ici.",
    pick: 'Choisir un dossier',
    dropHint: "ou déposez un dossier n'importe où dans cette fenêtre",
    typePath: 'Ou saisir le chemin',
    pathPlaceholder: 'Chemin absolu du dossier',
    add: 'Ouvrir'
  },

  drop: {
    title: 'Déposez pour ajouter un projet',
    body: 'Chaque dossier devient un projet. Les fichiers sont refusés.'
  },

  sidebar: {
    search: 'Rechercher une conversation',
    newThread: 'Nouvelle conversation',
    newThreadIn: 'Nouvelle conversation dans {project}',
    addProject: 'Ajouter un projet',
    noProjects: 'Aucun projet pour le moment.',
    noThreads: 'Aucune conversation pour le moment.',
    noMatch: 'Rien ne correspond.',
    unread: 'Non lu',
    collapse: 'Masquer la barre latérale',
    expand: 'Afficher la barre latérale',
    resize: 'Redimensionner la barre latérale, double-clic pour réinitialiser',
    loadTitle: 'Charge en direct',
    settings: 'Réglages',
    projectMenu: 'Actions du projet',
    copyPath: 'Copier le chemin',
    copied: 'Copié',
    importSession: 'Importer une session Claude Code',
    removeProject: 'Retirer de Boite',
    removeProjectTitle: 'Retirer {project} de Boite ?',
    removeProjectBody: 'Ses conversations partent avec lui. Les fichiers sur le disque restent où ils sont.',
    remove: 'Retirer',
    threadMenu: 'Actions de la conversation',
    open: 'Ouvrir',
    rename: 'Renommer',
    retitle: 'Regénérer le titre',
    retitling: "Rédaction d'un titre",
    pin: 'Épingler',
    unpin: 'Désépingler',
    pinned: 'Épinglée',
    archive: 'Archiver',
    draft: 'Nouvelle conversation'
  },

  palette: {
    placeholder: 'Cherchez une conversation, ou tapez une commande',
    threads: 'Conversations',
    commands: 'Commandes',
    empty: 'Rien ne correspond.',
    hint: 'Entrée pour ouvrir, Échap pour fermer',
    newThread: 'Nouvelle conversation',
    addProject: 'Ajouter un projet',
    importSession: 'Importer une session Claude Code',
    settings: 'Ouvrir les réglages',
    appearance: "Réglages d'apparence",
    providers: 'Fournisseurs et comptes',
    pair: 'Appairer un téléphone',
    sidebar: 'Afficher ou masquer la barre latérale',
    panel: 'Afficher ou masquer le panneau',
    trace: 'Afficher la trace',
    pin: 'Épingler cette conversation',
    unpin: 'Désépingler cette conversation',
    rename: 'Renommer cette conversation',
    retitle: 'Regénérer le titre de cette conversation',
    archive: 'Archiver cette conversation',
    themeDark: 'Thème : sombre',
    themeLight: 'Thème : clair',
    themeSystem: 'Thème : système'
  },

  imports: {
    title: 'Importer une session dans {project}',
    intro: "Sessions Claude Code lancées dans ce dossier. L'une d'elles devient une conversation avec son historique, et le tour suivant la continue.",
    loading: 'Recherche des sessions',
    empty: 'Aucune session Claude Code pour ce dossier.',
    imported: 'Importée',
    importing: 'Import en cours',
    close: 'Fermer'
  },

  slash: {
    label: 'Commandes',
    agent: 'Agent',
    app: 'Boite',
    empty: 'Aucune commande ne correspond',
    model: 'Changer de modèle',
    effort: 'Changer le niveau de raisonnement',
    mode: 'Changer le mode de permissions'
  },

  activity: {
    goal: 'Objectif',
    loop: 'Boucle',
    tasks: 'Tâches',
    taskCount: '{done}/{total} tâches',
    showTasks: 'Afficher les tâches',
    goalDescription: 'Continuer à travailler vers un objectif',
    loopDescription: 'Répéter une tâche un nombre de fois ou selon un rythme',
    goalUsage: 'Utilisez /goal suivi d\'un objectif.',
    loopUsage: 'Utilisez /loop 2 prompt pour deux itérations, ou /loop 5m prompt pour un rythme. Entre 1 et 1000 itérations.',
    intervalError: "L'intervalle d'une boucle doit tenir entre 1 seconde et 24 heures.",
    noAttachments: 'Envoyez les images dans un message avant de lancer un objectif ou une boucle.',
    active: 'Active',
    paused: 'En pause',
    complete: 'Terminée',
    pause: 'Mettre en pause',
    resume: 'Reprendre',
    remove: 'Retirer',
    finish: 'Marquer terminée',
    every: 'Toutes les {interval}',
    iterations: '{count} exécutions',
    iteration: 'Itération {count}',
    iterationOf: 'Itération {count} sur {total}',
    history: 'Historique des itérations',
    noHistory: 'Aucune itération terminée pour le moment',
    allTasksDone: 'Toutes les tâches sont terminées',
    waitingTasks: 'En attente de la prochaine tâche',
    stopped: 'Arrêtée',
    running: 'En cours',
    done: 'Terminée',
    error: 'Échec',
    pending: 'À faire',
    in_progress: 'En cours',
    completed: 'Terminée'
  },

  mention: {
    label: 'Fichiers',
    empty: 'Aucun fichier ne correspond',
    more: '{count} de plus, continuez à taper'
  },

  notify: {
    done: 'Terminé',
    failed: 'Échec',
    needsYou: 'Attend votre réponse'
  },

  permissionMode: {
    default: 'Demander',
    acceptEdits: 'Décider seul',
    bypassPermissions: 'Yolo',
    plan: 'Plan',
    dontAsk: 'Tout refuser'
  },

  permissionModeLong: {
    default: "Demander avant chaque appel d'outil",
    acceptEdits: 'Accepter les modifications, demander pour le reste',
    bypassPermissions: 'Tout exécuter sans demander',
    plan: 'Plan seulement, aucune modification',
    dontAsk: 'Refuser tout ce qui demanderait une autorisation'
  },

  thread: {
    contextDetails: 'Contexte',
    contextInput: 'Entrée',
    contextCache: 'Entrée en cache',
    contextOutput: 'Sortie',
    contextUsed: 'Utilisé',
    contextFree: 'Disponible',
    contextNoBreakdown: 'Cet agent ne détaille pas sa consommation.',
    contextNoReading: "Aucune mesure reçue de cet agent pour l'instant.",
    contextMeasured: 'Dernière mesure',
    none: 'Aucune conversation ouverte',
    noneBody: 'Choisissez-en une à gauche, ou lancez-en une nouvelle.',
    trace: 'Trace',
    traceHint: 'Processus lancés par cette conversation',
    cwd: 'Répertoire de travail',
    model: 'Modèle',
    defaultModel: 'Modèle par défaut',
    renamePlaceholder: 'Titre de la conversation',
    startIn: 'Lancer une conversation dans',
    start: 'Lancer une conversation',
    inWorktree: 'dans un worktree',
    inProject: 'dans',
    using: 'avec',
    onEffort: 'en raisonnement {effort}',
    draftMode: {
      default: 'avec demandes d\'autorisation',
      acceptEdits: 'avec les modifications autorisées',
      bypassPermissions: 'avec toutes les permissions',
      plan: 'en mode plan',
      dontAsk: 'avec refus automatique des demandes d\'autorisation'
    },
    changeProject: 'Changer de projet',
    branchHint: 'Travaille dans un worktree sur cette branche',
    contextHint: 'Contexte : {tokens} sur {window} jetons ({percent} %) à la dernière requête',
    contextHintNoWindow: "Contexte : {tokens} jetons à la dernière requête ; l'agent n'a nommé aucune fenêtre"
  },

  chat: {
    accepted: 'Requête acceptée',
    responseStarted: 'Activité reçue',
    working: 'Travaille',
    writing: 'Écrit',
    stopped: 'Arrêté',
    toolCall: '1 appel d\'outil',
    toolCount: '{count} appels d\'outil',
    inputTokens: '{count} jetons en entrée',
    outputTokens: '{count} jetons en sortie',
    you: 'Vous',
    assistant: 'Agent',
    system: 'Système',
    toolInput: 'Entrée',
    toolOutput: 'Sortie',
    toolDocuments: 'Documents',
    documentChip: {
      diff: '{count} diff',
      diffs: '{count} diffs',
      doc: '{count} doc',
      docs: '{count} docs'
    },
    documentImage: "Ce que l'outil a produit",
    imagePart: 'Image envoyée avec le message',
    diffHidden: '{count} lignes inchangées',
    diffAdded: '+{count}',
    diffRemoved: '-{count}',
    noOutput: 'Aucune sortie',
    showAll: 'Tout afficher',
    toolStatus: {
      running: 'en cours',
      done: 'terminé',
      error: 'erreur',
      denied: 'refusé'
    },
    thinking: 'Réflexion',
    thinkingShow: 'Afficher le raisonnement',
    thinkingHide: 'Masquer le raisonnement',
    compaction: 'Contexte compacté, de {pre} à {post} jetons',
    compactionNoPost: 'Contexte compacté depuis {pre} jetons',
    compactionUnknown: 'Contexte compacté',
    compactionManual: 'à la main',
    permissionHeading: 'Veut utiliser',
    allow: 'Autoriser',
    deny: 'Refuser',
    allowed: 'Autorisé',
    denied: 'Refusé',
    questionHeading: 'Vous demande',
    questionTextLabel: 'Votre propre réponse',
    questionTextPlaceholder: 'Écrivez une réponse',
    questionAnswer: 'Répondre',
    questionAnswered: 'Répondu',
    questionCancelled: 'Le tour est terminé avant la réponse',
    streaming: 'écrit',
    jumpToLatest: 'Aller au dernier message',
    loadingOlder: 'Chargement des messages précédents',
    outline: 'Messages de cette conversation',
    messageGroup: 'Parcourir {count} messages',
    earlierMessages: 'Charger les messages précédents',
    goToMessage: 'Aller au message {number} : {text}',
    copy: 'Copier',
    copied: 'Copié',
    error: 'Erreur'
  },

  composer: {
    placeholder: 'Message à {provider} dans {project}',
    placeholderNoProject: "Message à l'agent",
    send: 'Envoyer',
    stop: 'Arrêter',
    queued: 'Envoyé à la fin du tour en cours',
    picker: 'Fournisseur et modèle',
    models: 'Modèles',
    searchModels: 'Rechercher un modèle',
    noModels: 'Aucun modèle ne correspond',
    legacyModels: 'Anciens modèles',
    refreshModels: 'Actualiser les modèles',
    probing: "Lecture des modèles de l'agent",
    notInstalled: 'Pas installé sur cette machine',
    installInSettings: 'Installer dans les réglages',
    reasoning: 'Raisonnement',
    effortTitle: 'Niveau de raisonnement',
    speed: 'Vitesse de réponse',
    standardSpeed: 'Vitesse normale',
    effortHint: 'Faites glisser ou utilisez les flèches pour choisir un niveau.',
    favorites: 'Favoris',
    favorite: 'Ajouter aux favoris',
    unfavorite: 'Retirer des favoris',
    favoritesEmpty: 'Mettez une étoile à un modèle pour le retrouver ici.',
    favoriteUnavailable: "Ce favori n'est plus proposé par le compte. Choisissez un autre modèle.",
    compact: 'Compacter le contexte',
    compactBusy: 'Attendez la fin du tour en cours',
    compactUnavailable: "Cet agent n'a pas annoncé de compactage du contexte",
    compactNoSession: 'Envoyez un message avant de compacter',
    contextUnknown: 'Consommation du contexte non communiquée',
    newBadge: 'nouveau',
    lockedHint: 'Une conversation garde son fournisseur et son compte',
    mode: 'Permissions',
    model: 'Modèle',
    unavailable: 'pas installé',
    noAccount: 'aucun compte',
    noProvider: 'Aucun fournisseur',
    hint: 'Entrée pour envoyer, Maj+Entrée pour une nouvelle ligne',
    worktree: 'Worktree',
    worktreeOff: 'Démarrer dans un worktree git sur sa propre branche',
    worktreeOn: 'Démarre dans un worktree git sur sa propre branche',
    attach: 'Joindre des images',
    editQueued: 'Modifier ce message en attente, ou appuyez sur Haut dans un champ vide',
    attachRemove: 'Retirer {name}',
    attachAlt: 'Image jointe',
    attachUnnamed: "l'image collée",
    attachFormat: '{name} est en {type}, or une image doit être de type {formats}.',
    attachTooLarge: '{name} est trop lourde : une image pèse {max} au maximum.',
    attachTooMany: 'Un tour porte {max} images au maximum, donc {name} a été laissée de côté.',
    attachNoImages: "{provider} n'accepte pas les images : envoyez le message sans elles."
  },

  rightPanel: {
    label: 'Panneau',
    toggle: 'Afficher ou masquer le panneau',
    resize: 'Redimensionner le panneau, double-clic pour réinitialiser',
    maximize: 'Agrandir le panneau',
    restore: 'Restaurer le panneau',
    newSurface: 'Ouvrir une surface',
    scrollLeft: 'Faire défiler les onglets vers la gauche',
    scrollRight: 'Faire défiler les onglets vers la droite',
    close: 'Fermer',
    closeTab: 'Fermer {title}',
    closeOthers: 'Fermer les autres',
    closeToRight: 'Fermer à droite',
    closeAll: 'Tout fermer',
    trace: 'Trace',
    traceHint: 'Processus lancés par cette conversation',
    browser: 'Navigateur',
    browserHint: 'Une page à côté de la conversation',
    desktopOnly: "Seulement dans l'application de bureau",
    ownerOnly: "Seulement dans l'application du propriétaire",
    launcher: 'Ouvrir une surface dans ce panneau',
    untitled: 'Navigateur'
  },

  browser: {
    back: 'Précédent',
    forward: 'Suivant',
    reload: 'Recharger',
    urlPlaceholder: 'Rechercher ou saisir une URL',
    openExternal: 'Ouvrir dans le navigateur du système',
    slotEmpty: "La page s'affiche ici dès que la coque fournit la vue web"
  },

  trace: {
    exact: 'Tous les processus enfants suivis',
    limited: 'Suivi des processus limité',
    finished: 'Terminé',
    parent: 'PID parent',
    cpuTime: 'Temps CPU',
    currentMemory: 'Mémoire actuelle',
    active: 'actifs',
    recorded: 'enregistrés',
    exe: 'Exécutable',
    pid: 'PID',
    started: 'Démarré',
    duration: 'Durée',
    cpu: 'CPU',
    memory: 'Mémoire maximale',
    io: 'E/S',
    exit: 'Sortie',
    live: 'en cours',
    empty: "Cette conversation n'a lancé aucun processus.",
    modeLabel: 'Mode de trace'
  },

  protection: {
    intro: 'Empêcher les agents de vous déranger et décider de ce qu\'ils consomment.',
    quiet: 'Tranquillité',
    limits: 'Limites de ressources',
    tasks: 'Gestionnaire de tâches',
    windows: "La mise au second plan, le son et les limites de ressources s'appliquent sur un hôte Windows.",
  },
  resources: {
    heading: 'Protection',
    empty: "Aucune conversation ne consomme quoi que ce soit pour l'instant.",
    live: 'Processus en cours',
    totals: 'Totaux',
    processes: 'processus',
    killTree: "Tuer l'arborescence",
    killConfirm: 'Tuer tous les processus de cette conversation ?',
    killConfirmYes: 'Tuer',
    killConfirmNo: 'Annuler',
    killed: 'Tué'
  },

  install: {
    heading: 'Installé par Boite',
    action: 'Installer',
    update: 'Mettre à jour',
    retry: 'Réinstaller',
    cancel: 'Annuler',
    remove: 'Supprimer',
    removeTitle: 'Supprimer {provider} ?',
    removeBody: 'Les fichiers téléchargés par Boite partent avec. Il pourra être réinstallé plus tard.',
    removeConfirm: 'Supprimer',
    removeCancel: 'Garder',
    absent: 'Pas installé, {size}',
    verifying: "Vérification de l'archive",
    extracting: 'Décompression',
    upToDate: 'Version {version}',
    updateAvailable: 'Version {installed}, {available} disponible',
    progress: 'Progression du téléchargement'
  },

  accounts: {
    heading: 'Fournisseurs',
    empty: 'Aucun compte pour le moment.',
    add: 'Ajouter un compte',
    provider: 'Fournisseur',
    label: 'Libellé',
    labelPlaceholder: 'Comment vous le reconnaîtrez',
    useDefaultLocation: "Utiliser l'emplacement par défaut du fournisseur (votre vrai login)",
    create: 'Ajouter',
    cancel: 'Annuler',
    check: 'Vérifier',
    identity: 'Identité',
    isolation: "Répertoire d'isolation",
    defaultLocation: 'par défaut du fournisseur',
    login: 'Se connecter',
    loginStarting: 'Attente du CLI du fournisseur',
    loginOpen: 'Ouvrez ce lien pour vous connecter',
    loginInputPlaceholder: 'Collez le code donné par la page',
    loginRedirectPlaceholder: "Collez l'URL de redirection localhost de la page de connexion",
    loginSend: 'Envoyer',
    loginCancel: 'Annuler la connexion',
    remove: 'Supprimer',
    removeTitle: 'Supprimer {account} ?',
    removeBody: "Cela supprime le compte et son répertoire d'isolation. Un compte utilisé par une conversation ne peut pas être supprimé.",
    removeDefaultBody: 'Cela retire le compte de Boite. Le login du fournisseur reste sur cette machine. Un compte utilisé par une conversation ne peut pas être supprimé.',
    status: {
      unknown: 'inconnu',
      ok: 'ok',
      unauthenticated: 'non connecté',
      error: 'erreur'
    }
  },

  usage: {
    heading: 'Consommation',
    note: "Sur un abonnement, ce coût est un équivalent API, pas de l'argent dépensé.",
    thread: 'Conversation',
    input: 'Entrée',
    output: 'Sortie',
    cacheRead: 'Cache lu',
    cacheWrite: 'Cache écrit',
    cost: 'Équivalent API',
    total: 'Total',
    empty: 'Aucun jeton dépensé pour le moment.',
    today: "aujourd'hui"
  },

  settings: {
    heading: 'Réglages',
    modelDefaults: 'Modèles par défaut',
    modelDefaultsHint: 'Modèle et niveau de raisonnement des nouvelles conversations, par fournisseur. Enregistré sur cet appareil. Les conversations existantes gardent leurs choix.',
    modelDefaultUnavailable: "{provider} ne propose pas le modèle par défaut {model} sur ce compte. Choisissez un modèle disponible dans le sélecteur, ou changez le défaut dans les réglages.",
    tabs: {
      general: 'Général',
      appearance: 'Apparence',
      keyboard: 'Clavier',
      accounts: 'Fournisseurs',
      plugins: 'Extensions',
      usage: 'Consommation',
      resources: 'Protection',
      experiments: 'Expérimentations'
    },
    back: 'Retour aux conversations',
    projects: 'Projets',
    projectsHint: 'Clic droit sur un projet dans la barre latérale pour le retirer de Boite.',
    projectsDevice: "Les dossiers s'ajoutent et se retirent depuis l'application où tourne le cœur.",
    appearance: 'Apparence',
    language: 'Langue',
    languageHint: "Enregistrée sur cet appareil. Système suit la langue configurée sur votre machine.",
    languageSystem: 'Système',
    languageNames: { en: 'English', fr: 'Français' },
    theme: 'Thème',
    accent: "Couleur d'accent",
    accentHint: 'Raisonnement, boutons, liens et indicateurs de focus',
    accentCustom: "Couleur d'accent personnalisée",
    accentNames: ['Bleu', 'Violet', 'Rose', 'Orange', 'Ambre', 'Vert', 'Turquoise'],
    themeSystem: 'Système',
    themeDark: 'Sombre',
    themeLight: 'Clair',
    themeGrain: 'Grain',
    experiments: {
      heading: 'Expérimentations',
      intro: "Ce n'est pas fini. Ça peut changer de forme ou disparaître dans une version suivante."
    },
    material: 'Matériau de la fenêtre',
    materialHint: 'Ce que Windows dessine derrière la fenêtre',
    materialAcrylic: 'Acrylique',
    materialMica: 'Mica',
    materialSolid: 'Opaque',
    connection: 'Connexion',
    localCore: "Cette application tourne sur le cœur qu'elle a lancé sur cet ordinateur.",
    coreAt: 'Connecté au cœur à {url}.',
    pairingLink: "Lien d'appairage",
    pairingLinkPlaceholder: 'http://hote:port/?grant=',
    pair: 'Appairer',
    pairHint:
      "Collez un lien émis par l'autre cœur, depuis ses propres réglages ou avec boite-core pair --owner sur la machine où il tourne. La clé qu'il devient reste sur cet ordinateur.",
    useLocal: "Utiliser le cœur de cet ordinateur",
    useLocalHint: 'Les cœurs mémorisés ci-dessous le restent.',
    environments: 'Cœurs mémorisés',
    environmentsHint: "Un cœur appairé ou connecté reste ici. Y revenir ne demande aucun nouveau lien : la clé tient jusqu'à sa révocation là-bas ou son oubli ici.",
    envCurrent: 'actuel',
    envSwitch: 'Basculer',
    envForget: 'Oublier',
    manual: 'URL du cœur et jeton',
    coreUrl: 'URL du cœur',
    token: 'Jeton',
    connect: 'Connecter',
    scheduler: 'Ordonnanceur',
    maxConcurrentTurns: 'Tours simultanés maximum',
    perAccountConcurrency: 'Simultanéité par compte',
    warmProcessMinutes: 'Minutes de processus gardé chaud',
    listenOnLan: "Écouter sur le réseau local pour qu'un téléphone puisse s'appairer",
    listenOnLanHint: "Prend effet au prochain démarrage du cœur, et une option --host ou --lan l'emporte",
    agentCpuCapPercent: 'Plafond CPU de tous les agents, en pourcentage de la machine (0 = aucun, Windows)',
    threadMemoryCapMb: "Plafond mémoire par arborescence de conversation, en Mo (0 = aucun, Windows)",
    background: 'Arrière-plan',
    closeToTray: 'Garder Boite en marche quand la fenêtre se ferme',
    closeToTrayHint: "Désactivé par défaut. Activez pour le réduire dans la zone de notification et laisser les tours continuer. Quitter arrête toujours Boite.",
    notifications: "Me prévenir quand une conversation se termine ou pose une question",
    notificationsHint: "Une bulle pour une conversation que vous ne regardez pas, ou quand Boite n'est pas la fenêtre au premier plan. Cette machine seulement.",
    notificationsDenied: 'Les notifications sont bloquées pour Boite sur ce système ; autorisez-les dans ses réglages.',
    focusGuard: 'Garder les fenêtres des agents en arrière-plan',
    focusGuardHint: "Les fenêtres qu'un agent ouvre passent derrière Boite au lieu de vous voler le focus",
    muteAgents: 'Couper le son des agents',
    muteAgentsHint: "Les sons joués par un processus d'agent n'atteignent jamais vos haut-parleurs",
    save: 'Enregistrer',
    saved: 'Enregistré',
    core: 'Cœur',
    version: 'Version',
    protocol: 'Protocole',
    os: 'Système',
    pid: 'PID',
    dataDir: 'Répertoire de données',
    endpoint: 'Point de connexion',
    noCore: 'Pas connecté à un cœur.',
    pairing: {
      heading: 'Téléphones et appareils',
      intro: "Un lien d'appairage ouvre Boite sur un autre appareil avec une clé à lui. Il sert une fois et tient dix minutes.",
      mint: "Nouveau lien d'appairage",
      copy: 'Copier le lien',
      expires: "Valable une fois, jusqu'à {time}",
      qr: "Le lien d'appairage en QR code",
      scan: 'Scannez le code avec le téléphone, ou ouvrez le lien dessus.',
      lanHint: "Le cœur n'écoute que sur cette machine : activez le réseau local ci-dessus, puis redémarrez-le, avant qu'un téléphone puisse atteindre ce lien.",
      devices: 'Appareils appairés',
      noDevices: 'Aucun appareil appairé pour le moment.',
      thisDevice: 'cet appareil',
      lastSeen: 'vu {when}',
      revoke: 'Révoquer',
      revokeTitle: 'Révoquer cet appareil ?',
      revokeBody: "Il se déconnecte tout de suite et sa clé n'ouvre plus rien. Réappairez-le avec un nouveau lien.",
      paired: "Cet appareil est appairé avec une clé à lui. Les liens d'appairage se créent depuis l'application de bureau.",
      owner: 'Contrôle total',
      ownerHint:
        "Pour un autre de vos ordinateurs : sa clé pilote ce cœur comme vous le faites, comptes, projets et réglages compris. Laissez désactivé pour un téléphone.",
      ownerTag: 'contrôle total',
      pasteOwner: "Collez-le dans Réglages, Général, sur l'autre ordinateur."
    }
  },

  keyboard: {
    heading: 'Raccourcis',
    intro: "Tous les raccourcis auxquels Boite répond. Changez-en un dans le fichier ci-dessous : il est relu dès qu'il est enregistré, sans redémarrage.",
    file: 'Le fichier',
    fileHint:
      'Un objet JSON qui associe un identifiant de commande à un raccourci, de la forme "mod+shift+k", ou null pour retirer une touche. mod vaut Ctrl ici et Cmd sur un Mac. Seules les entrées nommées changent ; les autres gardent leur valeur par défaut.',
    example: 'Exemple',
    command: 'Commande',
    id: 'Identifiant',
    chord: 'Raccourci',
    none: 'aucun',
    custom: 'depuis le fichier',
    problems: 'Refusé',
    problemsHint: "Ces lignes du fichier n'ont pas été appliquées. Corrigez-les et enregistrez ; le reste du fichier est en service.",
    commands: {
      palette: 'Ouvrir la palette de commandes',
      browser: 'Ouvrir la surface navigateur',
      closeSurface: 'Fermer la surface active',
      stash: 'Mettre le message de côté, ou le reprendre',
      sendAndDraft: 'Envoyer et ouvrir une nouvelle conversation',
      pin: 'Épingler ou désépingler cette conversation'
    }
  },

  experiments: {
    themeGrain: {
      title: 'Thème Grain',
      hint: 'Un fond grainé qui passe du gris clair en haut à gauche au noir en bas à droite'
    },
    sessionImport: {
      title: 'Import de session Claude Code',
      hint: 'Transformer une session lancée dans le terminal en conversation, depuis le menu du projet et la palette'
    }
  },

  quotas: {
    trayHeading: 'Consommation',
    trayIntro: "Limites d'abonnement",
    names: { claude: 'Claude', codex: 'Codex', antigravity: 'Antigravity', grok: 'Grok', opencode: 'OpenCode Go' },
    off: 'Désactivé',
    noReading: 'Indisponible',
    notConnected: 'Non connecté',
    autoConnect: 'Utilise votre compte connecté',
    cliSource: 'Compte du CLI Antigravity',
    cliHint: "Utilise le compte connecté via agy sur cet ordinateur. Installez le CLI Antigravity 1.1.11 ou plus récent, connectez-vous une fois, puis activez le suivi ci-dessous. C'est indépendant des comptes Antigravity isolés de Boite.",
    connectHint: 'Connectez {provider} une fois dans Fournisseurs. La consommation apparaît ici toute seule.',
    connect: 'Connecter un compte',
    noReset: 'Heure de réinitialisation non communiquée',
    heading: 'Quotas des fournisseurs',
    intro: "Limites d'abonnement communiquées par vos fournisseurs. C'est distinct des jetons dépensés dans Boite.",
    remaining: '{percent} % restants',
    resets: 'Repart {time}',
    checked: 'Mis à jour {time}',
    stale: 'Dernière lecture réussie',
    empty: "Connectez un fournisseur pour voir ses limites d'abonnement.",
    unsupported: "Ce fournisseur n'expose pas ses quotas d'abonnement ici.",
    disabled: 'Le suivi des quotas est désactivé pour ce compte.',
    loading: 'Lecture des limites du fournisseur',
    monitor: "Suivre les quotas d'abonnement",
    providers: 'Gérer les fournisseurs',
    unavailable: 'Aucune lecture de quota disponible.',
    refresh: 'Actualiser les quotas',
    quit: 'Quitter Boite',
  },
  providerSettings: {
    heading: 'Fournisseurs',
    intro: "Boite exécute les agents installés sur la machine qui héberge votre cœur. Les logins en ligne de commande existants sont détectés tout seuls ; les logins par site web sont distincts.",
    installHint: 'Installez {provider} pour connecter un compte.',
    detectHint: "Après avoir installé un agent, relancez la détection. S'il manque toujours, redémarrez Boite pour rafraîchir son PATH.",
    setup: "Instructions d'installation",
    connect: 'Connecter un compte',
    connectInstalling: "Installation de l'agent. La connexion démarrera à la fin du téléchargement.",
    reinstall: "L'agent géré est installé mais son exécutable manque. Supprimez-le et réinstallez-le.",
    reconnect: 'Reconnecter',
    available: 'Prêt sur cette machine',
    missing: 'Exécutable introuvable',
    executable: 'Exécutable',
    isolated: 'Login Boite',
    default: 'Login CLI',
    defaultHint: 'Utilise votre login CLI existant. Pour vous connecter via Boite, ajoutez un compte séparé au-dessus.',
    isolatedHint: 'Ce login est gardé à part de votre compte en ligne de commande.',
    modelCheck: "Vérifier l'accès et les modèles",
    models: '{count} modèles disponibles',
    refresh: 'Relancer la détection',
  },
  plugins: {
    heading: 'Extensions',
    intro: 'Ajouter des outils à Boite. Chaque extension tourne sur la machine qui héberge votre cœur.',
    description: 'Enregistrer et changer de login CLI Claude, Codex et Antigravity, avec la lecture des quotas de chaque compte enregistré.',
    install: 'Installer',
    installed: 'Installée',
    update: 'Mettre à jour',
    remove: 'Désinstaller',
    installing: 'Téléchargement de la version vérifiée',
    source: 'Code source',
    empty: 'Aucun compte enregistré dans ce pool.',
    add: 'Enregistrer le login CLI actuel',
    switch: 'Utiliser ce compte',
    forget: 'Oublier le compte',
    active: 'Actif',
    refresh: 'Actualiser les comptes enregistrés',
    removeTitle: 'Désinstaller kebacc-switcher ?',
    removeBody: "Retire le binaire de l'extension de Boite. Vos logins enregistrés restent dans kebacc.",
    switchTitle: 'Changer le login CLI ?',
    switchBody: "Cela change le login CLI par défaut du fournisseur pour les tours suivants, y compris hors de Boite. Les comptes Boite isolés gardent le leur.",
    forgetTitle: 'Oublier ce login enregistré ?',
    forgetBody: "Retire ce login du pool de kebacc.",
    cliScope: 'Ce sont les pools de comptes CLI. Ils sont distincts des comptes isolés connectés dans Fournisseurs.',
  },

  time: {
    now: 'à l\'instant'
  },

  errors: {
    prefix: 'Erreur',
    activityUnsupported: "Ce cœur ne gère pas les objectifs ni les boucles. Mettez Boite à jour sur {machine}, puis reconnectez-vous. Votre commande n'a pas été envoyée.",
    pullRequestUnsupported: "Mettez Boite à jour sur la machine qui héberge cette conversation pour afficher sa pull request. Ce cœur ne sait pas encore les chercher.",
    noEndpoint: "Aucun point de connexion n'a pu être résolu.",
    connect: 'Connexion au cœur impossible.',
    clipboard: 'Le presse-papiers a refusé le texte.',
    revoked: "Cet appareil a été révoqué depuis l'application de bureau. Ouvrez un nouveau lien d'appairage pour vous reconnecter.",
    pairingLink: "Ce n'est pas un lien d'appairage : il lui faut une adresse http ou https portant un grant."
  },

  units: {
    bytes: 'o',
    kilobytes: 'ko',
    megabytes: 'Mo',
    gigabytes: 'Go',
    milliseconds: 'ms',
    seconds: 's',
    minutes: 'min',
    hours: 'h',
    tokens: 'jetons'
  },

  common: {
    none: 'aucun',
    unknown: 'inconnu',
    yes: 'oui',
    no: 'non',
    close: 'Fermer',
    refresh: 'Actualiser',
    dismiss: 'Ignorer',
    cancel: 'Annuler',
    confirm: 'Confirmer'
  },

  onboarding: {
    label: 'Prise en main',
    skip: 'Passer',
    back: 'Retour',
    next: 'Suivant',
    done: 'Ouvrir Boite',
    step: 'Étape {index} sur {total}',
    progress: "Aller à l'étape {index} : {title}",
    replay: 'Revoir la présentation',
    replayHint: "Les mêmes écrans qu'au premier lancement. Rien de ce que vous avez réglé n'est défait.",
    changeLater: 'Tout ça se retrouve ensuite dans les réglages.',

    welcome: {
      title: 'Boite fait tourner vos agents',
      body: "Une conversation par tâche, chacune dans un dossier de projet, toutes côte à côte. Les agents tournent sur la machine qui héberge ce cœur, pas dans cette fenêtre : un tour continue pendant que vous faites autre chose.",
      pick: 'Deux choses valent le coup tout de suite.'
    },

    agents: {
      title: "Changer d'agent au milieu d'une conversation",
      body: "La pastille en bas à gauche de la zone de saisie contient tous les fournisseurs que vous avez connectés, leurs comptes et leurs modèles. Changez de modèle en pleine conversation et rien n'est perdu : l'historique reste, et le processus déjà lancé est prévenu au lieu d'être jeté.",
      effort: "La pastille juste à côté règle l'effort de raisonnement, sur l'échelle propre au modèle.",
      locked: 'Une conversation garde le fournisseur et le compte sur lesquels elle a commencé. Le modèle et le raisonnement, eux, changent quand vous voulez.',
      demoModel: 'Claude Sonnet 5',
      demoEffort: 'Élevé',
      demoMode: 'Demander'
    },

    voice: {
      title: 'Parler au lieu de taper',
      body: "Maintenez le micro dans la zone de saisie et parlez. L'enregistrement est transcrit sur la machine qui héberge ce cœur et arrive dans le champ sous forme de texte, que vous relisez avant que quoi que ce soit parte.",
      hint: 'Choisissez un moteur une fois et la dictée marche dans toutes les conversations, sur le téléphone aussi.',
      open: 'Réglages de la voix'
    },

    usage: {
      title: 'Voir ce que vous dépensez',
      body: "Vos fournisseurs indiquent ce qu'il reste de votre abonnement. Boite en dessine une barre par fenêtre, avec l'heure de réinitialisation, dans la zone de notification et sur la page Fournisseurs.",
      tokens: "Les jetons dépensés dans Boite sont comptés à part, dans Réglages, Consommation, avec ce que les mêmes tours auraient coûté sur l'API.",
      monitor: 'Lire les limites de {account}',
      noAccounts: "Aucun compte de fournisseur pour le moment. Connectez-en un et ses limites apparaîtront ici toutes seules.",
      connect: 'Connecter un fournisseur',
      deviceHint: 'Les limites sont lues sur la machine qui héberge le cœur.'
    },

    reach: {
      title: 'Votre téléphone, et vos autres machines',
      phone: 'Sur votre téléphone',
      phoneBody: "Un lien à usage unique, ou le QR code à côté, ouvre Boite sur votre téléphone avec une clé à lui. Les mêmes conversations, et une notification quand un tour se termine ou vous demande quelque chose.",
      pair: 'Appairer un téléphone',
      machines: 'Un autre Boite',
      machinesBody: "Cette application pilote aussi un Boite qui tourne ailleurs, sur un serveur ou un second ordinateur. Connectez-le une fois et ses projets et ses conversations se rangent à côté de ceux d'ici, chaque machine continuant d'exécuter ses propres agents sur ses propres fichiers.",
      connect: 'Connecter une machine',
      deviceHint: "L'appairage et les machines se gèrent depuis l'application où tourne le cœur."
    },

    quiet: {
      title: 'Des agents qui ne vous coupent pas',
      body: "Boite est fait pour tourner pendant que vous travaillez sur autre chose. Voici les interrupteurs qui valent le coup d'être décidés maintenant.",
      windows: 'Les deux derniers ne valent que sur un hôte Windows et sont ignorés ailleurs.',
      deviceHint: 'Le focus et le son sont des réglages de la machine qui héberge le cœur.'
    },

    project: {
      title: 'Ouvrir votre premier projet',
      body: "Un projet, c'est le dossier dans lequel un agent travaille. Les conversations vivent dedans, et un agent ne voit rien en dehors tant que vous ne l'y envoyez pas.",
      opened: '{count} projet ouvert. Vous pouvez en ajouter depuis la barre latérale.',
      openedMany: '{count} projets ouverts. Vous pouvez en ajouter depuis la barre latérale.',
      deviceBody: "Les projets s'ouvrent depuis l'application où tourne le cœur. Ceux qu'il détient apparaissent ici tout seuls."
    }
  }
};
