/*
 * Le catalogue français, calqué sur `strings.en.ts`.
 *
 * Le type vient de l'anglais : une clé inconnue de l'anglais arrête
 * `svelte-check`. Une phrase pas encore traduite peut manquer ici, elle
 * s'affiche alors en anglais (`lib/i18n.svelte.ts`) et passe en nightly, mais
 * `scripts/ci/translations.ts --release` bloque la release tant qu'elle manque.
 * Les accolades sont des emplacements remplis par `fill`, leur nom ne se
 * traduit pas.
 */

import type { Translation } from './i18n.svelte';

export const fr: Translation = {
  agents: {
    runtime: "Modèles et limites",
    brain: "Cerveau",
    routines: "Routines",
    defaultModel: "Modèle par défaut",
    allowedModels: "Modèles autorisés pour cet agent",
    subagents: "Modèles des sous-agents",
    enableSubagents: "Autoriser les sous-agents",
    addModel: "Ajouter un modèle",
    removeRoute: "Retirer ce modèle",
    compactEvery: "Compacter après ce nombre de tours",
    runMinutes: "Minutes maximum par exécution",
    maxSubagents: "Nombre maximum de sous-agents",
    runtimeHint: "Le modèle par défaut doit être autorisé. Les sous-agents ont leur propre liste. Retirer un accès arrête les travaux concernés et les suspend pour vérification.",
    brainHint: "Ce cerveau appartient à cet agent sur sa machine hôte. Instructions et skills survivent aux changements de modèle. La mémoire personnelle reste dans les conversations directes ; les contextes partagés gardent leur mémoire séparée.",
    compactNow: "Compacter ce contexte",
    routineHint: "Fonctionne sur la machine hôte, même cette page fermée. Après une interruption, une seule occurrence est rattrapée. Un travail inachevé empêche les exécutions simultanées.",
    runNow: "Exécuter maintenant",
    schedule: "Planification",
    once: "Une fois",
    interval: "À intervalle régulier",
    daily: "Chaque jour",
    everyMinutes: "Toutes les N minutes",
    localTime: "Date ou heure locale",
    timezone: "Fuseau horaire",
    addRoutine: "Ajouter une routine",
    accountAccess: "Accès aux comptes",
    accountAccessHint: "Choisis les agents autorisés à utiliser chaque compte, y compris via leurs sous-agents. Retirer un accès arrête les exécutions concernées.",
    allAgents: "Tous les agents, actuels et futurs",
    heading: 'Agents', intro: 'Agents persistants, conversations communes et missions en équipe.', back: 'Retour aux conversations',
    profiles: 'Agents', groups: 'Groupes', teams: 'Équipes', missions: 'Missions', attention: 'À examiner',
    list: 'Tous les agents', create: 'Nouveau', edit: 'Modifier', save: 'Enregistrer', cancel: 'Annuler', close: 'Fermer',
    search: 'Rechercher', empty: 'Rien ici pour le moment.', select: 'Sélectionne un élément pour voir son activité.',
    name: 'Nom', domain: 'Rôle', instructions: 'Instructions', identityHint: 'Changer de modèle conserve son identité et sa mémoire.',
    model: 'Modèle et compte', noAccount: 'Ajoute un compte fournisseur dans les réglages avant de créer un agent.', permissions: 'Permissions',
    ask: 'Demander avant les actions', edits: 'Autoriser les modifications', plan: 'Planifier uniquement', full: 'Accès complet', deny: 'Ne pas demander',
    noApprovals: 'Ce fournisseur ne permet pas de valider les outils en direct. Ses permissions de lancement restent applicables. Les demandes de décision restent disponibles.',
    tools: 'Outils de collaboration', messages: 'Messages', memory: 'Mémoire', artifacts: 'Résultats', decisions: 'Décisions',
    members: 'Membres', responsibility: 'Responsabilité', description: 'Description', project: 'Projet', noProject: 'Sans projet',
    team: 'Équipe', noTeam: 'Sans équipe', group: 'Groupe de discussion', noGroup: 'Aucun groupe associé',
    mode: 'Qui répond', mentions: 'Destinataires choisis', round: 'Une réponse par membre', autonomous: 'Prendre la parole à tour de rôle',
    maxTurns: 'Nombre maximum de tours', perAgent: 'Tours par agent', modeHint: 'Chaque nouveau message ouvre un budget. Ses réponses partagent ce budget. Les échanges automatiques cessent à la première limite atteinte.',
    paused: 'En pause', pause: 'Suspendre', resume: 'Reprendre', archive: 'Archiver', active: 'Actif', archived: 'Archivé',
    objective: 'Objectif', expectedResult: 'Résultat attendu', minutes: 'Minutes totales de travail', tokens: 'Limite de jetons, vide si aucune',
    finishMission: 'Terminer la mission', reopenMission: 'Rouvrir la mission',
    conversation: 'Discussion', activity: 'Activité', send: 'Envoyer', message: 'Écrire un message', recipients: 'Destinataires', everyone: 'Suivre la règle du groupe',
    noMessages: 'Commence une conversation. Elle reste séparée des autres groupes et missions de cet agent.', user: 'Toi', noWork: 'Aucune exécution pour le moment.', loadEarlier: 'Afficher les plus anciens',
    openRun: 'Ouvrir cette exécution', requested: 'Demandé', executed: 'Exécuté', noUsage: 'Consommation non communiquée',
    pending: 'En attente', running: 'Au travail', waiting: 'Attend une décision', done: 'Terminé', cancelled: 'Annulé', interrupted: 'Interrompu', error: 'Échec', review: 'À relire', open: 'Ouvert', assigned: 'Attribué', accepted: 'Accepté',
    included: 'Inclus dans cette exécution', processed: 'Traité', failed: 'Échec', limited: 'Limite des échanges atteinte',
    reconcile: 'Vérifier et reprendre', reconcileHint: 'Inspecte les fichiers et le travail effectué. Indique ce qui est terminé et ce qui peut continuer.', reconcileNote: 'Que viens-tu de vérifier ?',
    answer: 'Répondre', answerPlaceholder: 'Ta décision et tes instructions', noAttention: 'Aucune décision ni interruption à examiner.',
    task: 'Tâche', tasks: 'Tâches', addTask: 'Ajouter une tâche', acquire: 'Attribuer', dependencies: 'Attendre ces tâches', approve: 'Accepter le résultat', revise: 'Demander des modifications', reject: 'Refuser', feedback: 'Retour pour la prochaine tentative',
    result: 'Résultat', verification: 'Vérifications déclarées par cet agent', workspace: 'Espace de travail', copyPath: 'Copier le chemin', noResults: 'Les résultats remis apparaîtront ici.',
    resources: 'Ressources', addResource: 'Ajouter une ressource', directory: 'Dossier', url: 'URL', value: 'Valeur', read: 'Lecture', write: 'Écriture',
    resourceHint: 'Ces accès guident le travail. Les permissions du fournisseur contrôlent les actions sur les fichiers.',
    addMemory: 'Ajouter un souvenir', text: 'Texte', scope: 'Portée', sources: 'Sources', ownerMemory: 'Ajouté par toi',
    searchKnowledge: 'Rechercher dans la mémoire et les ressources', expiresAt: 'Expiration facultative', expired: 'Expiré', expireMemory: 'Faire expirer',
    engine: 'Travail en arrière-plan', concurrency: 'Agents simultanés', engineHint: 'Fermer cette page laisse le travail continuer sur le moteur connecté.',
    kebacc: 'Expérience kebacc externe', kebaccHint: 'Utilise le plugin externe kebacc-switcher pour Antigravity CLI. Boite ne change pas ces comptes automatiquement.',
    experimentOff: 'Active cette expérience dans les réglages du moteur.', backgroundSettings: 'Réglages du moteur',
    idle: 'Disponible', offline: 'Chargement impossible. Reconnecte cette machine ou mets son moteur à jour.', retry: 'Réessayer',
    stale: 'Connexion perdue. Voici le dernier état reçu. Le travail peut continuer sur la machine hôte.',
    readOnly: 'Le propriétaire de ce moteur gère sa configuration.', history: 'Historique',
    memberCount: '{count} membres', minutesUnit: 'minutes', status: 'État', settings: 'Réglages', overview: 'Vue d’ensemble', createAction: 'Créer', rolePlaceholder: 'Recherche, développement ou relecture',
    kinds: { profile: 'Agent', group: 'Groupe', team: 'Équipe', mission: 'Mission' },
    kindHints: { profile: 'Un assistant résident avec sa mémoire, son modèle et ses routines.', group: 'Une conversation partagée entre plusieurs agents.', team: 'Des agents avec des rôles qui mènent des missions ensemble.', mission: 'Un objectif découpé en tâches que tu relis.' },
    newTitle: { profile: 'Nouvel agent', group: 'Nouveau groupe', team: 'Nouvelle équipe', mission: 'Nouvelle mission' },
    welcomeTitle: 'Des agents qui continuent de travailler', welcomeBody: 'Ils tournent sur la machine du moteur, retiennent ce qu’ils apprennent et continuent quand cette page est fermée.',
    summary: '{running} au travail · {pending} en attente', idleSummary: 'Rien en cours',
    engineSettings: 'Réglages du moteur', engineSettingsHint: 'La quantité de travail en arrière-plan de ce moteur, et les comptes que ses agents peuvent utiliser.',
    advanced: 'Plus d’options', identity: 'Identité', noMembers: 'Crée d’abord un agent.',
    brainFiles: 'Fichiers du cerveau', procedures: 'Procédures', proceduresHint: 'AGENTS.md dans le dossier du cerveau. Les façons de travailler réutilisables.', notes: 'Notes', notesHint: 'MEMORY.md dans le dossier du cerveau. Ce que cet agent garde d’une conversation à l’autre.',
    contexts: 'Contextes de conversation', memories: 'Souvenirs', sendHint: 'Entrée envoie, Maj+Entrée ajoute une ligne', toEveryone: 'Tout le monde',
    missionMembers: 'Agents de cette mission', dangerZone: 'Arrêter le moteur', dangerHint: 'Arrête tous les agents de ce moteur et déconnecte ses clients.',
    stopEngine: 'Arrêter ce moteur', stopEngineBody: 'Arrête les travaux et déconnecte les clients. Les exécutions commencées demanderont une vérification avant reprise. Rouvre Boite sur la machine hôte pour redémarrer le moteur.',
  },
  previewComments: {
  annotate: 'Référencer un élément',
  picking: 'Sélectionnez un élément dans la page. Échap annule.',
  comment: 'Que faut-il changer ?',
  add: 'Ajouter au message',
  cancel: 'Annuler',
  added: 'Élément ajouté à votre message.',
  unavailable: 'Cet élément est inaccessible. Utilisez l’application de bureau pour les pages d’une autre origine.',
  failed: 'La sélection a échoué. Rechargez la page et réessayez.',
  reveal: 'Montrer cet élément dans l’aperçu',
  remove: 'Retirer la référence à cet élément',
  stale: 'Cet aperçu a changé de page. Rouvrez la page d’origine ou sélectionnez à nouveau l’élément.',
  missing: 'Cet élément n’existe plus dans la page. Sélectionnez-le à nouveau.',
  tooMany: 'Un message peut référencer au maximum 8 éléments de page.',
  activityUnsupported: 'Les références ne sont pas disponibles avec /goal ou /loop. Envoyez un message ordinaire ou retirez les références.',
  stashUnsupported: 'Ce brouillon contient des références et ne peut pas être mis de côté. Envoyez-le ou retirez les références.'
},
  artifacts: { preview: 'Aperçu', download: 'Télécharger', close: 'Fermer l’aperçu', loading: 'Chargement du fichier', unavailable: 'Ce fichier ne peut pas être affiché ici. Téléchargez-le pour l’ouvrir.', failed: 'Impossible d’ouvrir ce fichier', ownerOnly: 'Les liens vers les fichiers locaux nécessitent une connexion propriétaire. Demandez à l’agent de joindre le fichier pour le partager avec cet appareil.' },

  brain: {
    heading: 'Brain', description: 'Les mêmes instructions et skills pour tes agents.',
    folder: 'Dossier du brain', pathHint: 'Chemin du dossier', save: 'Connecter le dossier', browse: 'Parcourir', useFolder: 'Choisir ce dossier',
    enabled: 'Utiliser avec les agents', disconnect: 'Déconnecter', refresh: 'Actualiser', sync: 'Synchroniser', working: 'En cours',
    empty: 'Connecte ton brain', emptyHint: 'Choisis le dossier de tes instructions et skills.',
    change: 'Changer de dossier', cancel: 'Annuler', saveChanges: 'Enregistrer',
    autoPull: 'Pull automatique', onStartup: 'Au démarrage', periodic: 'À intervalle régulier', minutes: 'min',
    globalInstructions: 'AGENTS.md global', globalDetails: 'Harness reliés',
    globalHint: 'Ce brain s\'applique à tous les projets, même hors de Boite. Les fichiers existants sont sauvegardés puis restaurés à la désactivation.',
    linked: 'Relié', existing: 'Déjà relié', blocked: 'À vérifier',
    interval: 'Intervalle du pull en minutes', intervalHint: 'Choisis un nombre entier entre 1 et 1440 minutes.',
    detected: 'Contenu', instructions: 'Instructions', skill: 'Skills', plugin: 'Plugins',
    pluginHint: 'Détectés ici. Installe les plugins depuis leur agent.',
    details: 'Détails de la synchro', noGit: 'Dossier local. Connecte un dépôt Git pour synchroniser entre PC.',
    noUpstream: 'Configure une branche distante dans Git pour activer la synchro.', dirty: 'Enregistre tes changements dans Git avant de synchroniser.',
    counts: '{ahead} à envoyer, {behind} à recevoir', lastSync: 'Dernière synchro', never: 'Pas encore synchronisé',
    upToDate: 'À jour', noEntries: 'Rien de détecté dans cette catégorie.',
    missing: 'Mets Boite à jour sur cette machine pour connecter un brain.',
  },
  "telemetry": {
    "heading": "Confidentialité et statistiques",
    "description": "Les compteurs de base sont activés par défaut. Les statistiques améliorées restent facultatives. Aucun message, nom de projet, chemin, compte ou enregistrement n'est collecté.",
    "basic": "Compteurs anonymes",
    "basicHint": "Compter les installations actives, lancements, conversations et résultats des tours. Les identifiants d'usage changent chaque jour ; un identifiant distinct compte uniquement les installations.",
    "enhanced": "Statistiques améliorées",
    "enhancedHint": "Partager les modèles publics choisis, le niveau de raisonnement, les modes de vitesse et de permission, les durées et les volumes de jetons avec un identifiant aléatoire stable. Les modèles privés sont regroupés sous « autre ». Désactiver demande la suppression du profil et de ses événements.",
    "unconfigured": "Cette version n'a pas de relais statistique configuré. Rien n'est envoyé.",
    "pending": "Suppression en attente. Boite réessaie en arrière-plan. PostHog supprime les événements après acceptation de la demande.",
    "export": "Exporter mes statistiques",
    "retry": "Réessayer la suppression"
  },
  speech: {
    heading: 'Voix', description: 'Dictez dans n\'importe quelle conversation. Relisez le texte avant de l\'envoyer.',
    start: 'Dicter', stop: 'Terminer la dictée', listening: 'Écoute', opening: 'Attente du micro', transcribing: 'Transcription',
    private: 'Sur ce cœur uniquement', cloud: 'Transcrit par votre fournisseur d\'API', retry: 'Relancer la transcription',
    live: 'Aperçu en direct', previewFailed: 'Aperçu en direct en pause. Terminez pour transcrire tout l\'enregistrement.',
    local: 'Local', api: 'API', localHint: 'Whisper tourne sur la machine qui héberge cette conversation. Votre téléphone utilise le même modèle sans le télécharger.',
    apiHint: 'L\'audio part de ce cœur vers le fournisseur que vous choisissez. Les clés restent sur ce cœur.',
    setup: 'La dictée n\'est pas encore configurée sur cette machine. Ouvrez les réglages Voix pour le faire en un clic.', ownerSetup: 'Demandez au propriétaire de configurer la voix sur ce cœur.',
    unsupported: 'La voix demande un Boite plus récent sur {machine}', unsupportedHint: 'Cette machine tourne sur une version de Boite sans moteur vocal. Mettez Boite à jour là-bas, puis rouvrez Voix.',
    unsupportedDictation: 'La dictée demande un Boite plus récent sur {machine}. Mettez Boite à jour là-bas, puis réessayez.',
    notReady: 'Pas encore configurée',
    statusReady: 'Prêt à dicter', statusReadyLocal: 'Appuyez sur le micro à côté d\'Envoyer dans n\'importe quelle conversation. Whisper tourne sur cette machine et l\'audio n\'en sort jamais.',
    statusReadyApi: 'Appuyez sur le micro à côté d\'Envoyer dans n\'importe quelle conversation. {provider} transcrit l\'audio.',
    statusSetup: 'La dictée n\'est pas configurée', statusSetupLocal: 'Un téléchargement d\'environ 200 Mo, le modèle Whisper Small et son moteur. Ensuite la dictée tourne sur cette machine sans aucun compte.',
    statusSetupModel: 'Télécharge le modèle Whisper Small, environ 190 Mo. Cette machine a aussi besoin de whisper-cli dans le PATH, ou de son chemin sous Chemins locaux.',
    statusKey: 'Ajouter une clé d\'API', statusKeyHint: 'Collez une clé {provider} ci-dessous, ou choisissez Local pour dicter sans aucun compte.',
    statusFailed: 'Le téléchargement ne s\'est pas terminé', statusBroken: 'Les réglages Voix sont illisibles', repair: 'Enregistrer pour réparer',
    setUp: 'Configurer la dictée', tryAgain: 'Réessayer', engine: 'Moteur', installed: 'Installé', saveKeys: 'Enregistrer les clés', savePaths: 'Enregistrer les chemins',
    phoneHint: 'La dictée utilise le moteur vocal de la machine connectée.',
    https: 'L\'accès au micro demande HTTPS ou localhost. Ouvrez le lien d\'appairage sécurisé de ce cœur.',
    denied: 'L\'accès au micro a été refusé. Autorisez-le dans les réglages du navigateur ou du système, puis réessayez.',
    noMicrophone: 'Aucun micro trouvé. Branchez-en un et réessayez.', microphoneBusy: 'Le micro est indisponible. Vérifiez qu\'une autre application ne l\'utilise pas.',
    silence: 'Aucune parole détectée. Réessayez plus près du micro.', failed: 'Enregistrement impossible. Réessayez.',
    model: 'Whisper Small', modelHint: 'Multilingue, quantifié. Environ 190 Mo. Chargé seulement pendant la transcription, sur quatre threads processeur au plus.',
    remove: 'Supprimer le téléchargement', ready: 'Prêt', missing: 'Non installé',
    downloading: 'Téléchargement', runtimeHint: 'Installez whisper-cli sur ce cœur ou indiquez son chemin absolu ci-dessous. Le téléchargement du modèle marche sur toutes les plateformes.',
    advanced: 'Chemins locaux', executable: 'Exécutable Whisper', modelPath: 'Fichier du modèle', pathHint: 'Laissez vide pour utiliser le téléchargement géré ou whisper-cli du PATH.',
    provider: 'Fournisseur de transcription', groq: 'Groq', openrouter: 'OpenRouter', groqModel: 'Whisper Large V3 Turbo',
    groqKey: 'Clé d\'API Groq', openrouterKey: 'Clé d\'API OpenRouter', keySaved: 'Clé enregistrée. Laissez vide pour la conserver.', keyEmpty: 'Collez une clé d\'API', clearKey: 'Supprimer la clé',
    fallback: 'Essayer l\'autre fournisseur d\'API si le premier échoue', fallbackHint: 'Demande les deux clés. Le mode local n\'envoie jamais d\'audio à une API.',
    language: 'Langue', languageHint: 'Laissez vide pour la détection automatique, ou saisissez un code à deux lettres comme en ou fr.',
    saved: 'Enregistré', ownerOnly: 'Le propriétaire gère le moteur vocal de ce cœur. Vous pourrez dicter depuis n\'importe quelle conversation une fois qu\'il sera prêt.',
    privacy: 'Les enregistrements restent en mémoire pendant que vous dictez. L\'audio temporaire local est supprimé après la transcription. Rien n\'est envoyé comme message tant que vous n\'appuyez pas sur Envoyer.',
    limit: 'Deux minutes au maximum par dictée. Changer de conversation ou quitter l\'application annule l\'enregistrement.',
  },
  phone: {
    preparing: "L'application prépare encore ses fichiers hors ligne. Rechargez la page et réessayez.",
    settingsOffline: "Les réglages ne sont pas encore téléchargés. Reconnectez-vous et rouvrez les réglages.",
    dialogOffline: "Cette fenêtre n'est pas encore téléchargée. Reconnectez-vous et rouvrez-la.",
    heading: 'Application mobile', publicUrl: 'Adresse HTTPS publique', urlPlaceholder: 'https://boite.example.com',
    publicUrlHint: "Utilisez l'origine HTTPS configurée sur votre reverse proxy. Les nouveaux liens d'appairage passeront par cette adresse. Le proxy doit transmettre la page et /rpc à ce cœur.",
    install: 'Installer Boite', installed: "Boite tourne comme application installée.",
    installHint: "Sur iPhone, ouvrez Partager dans Safari, puis Sur l'écran d'accueil. Sur Android, utilisez Installer l'application dans le menu du navigateur.",
    httpsRequired: "Cette connexion est en HTTP. Ouvrez Boite en HTTPS pour activer les fichiers hors ligne et les notifications.",
    ownOrigin: "Ouvrez le lien d'appairage de cette machine pour y activer les notifications.",
    pairFirst: "Ouvrez un lien d'appairage d'appareil avant d'activer les notifications.",
    unsupported: "Ce navigateur ne gère pas les notifications push ici. Sur iPhone, ajoutez Boite à l'écran d'accueil et ouvrez-le depuis son icône.",
    pushHint: "Recevoir une notification quand un agent termine, échoue ou attend votre réponse, y compris quand Boite est fermé.",
    enable: 'Activer les notifications', disable: 'Désactiver les notifications', test: 'Envoyer une notification de test',
    enabled: 'Notifications activées pour cet appareil.', testSent: 'Le service push a accepté la notification de test.',
    denied: "Les notifications ont été refusées. Vous pouvez changer ça dans les réglages du navigateur ou de l'appareil.",
    subscriptionFailed: "Le navigateur n'a pas renvoyé un abonnement push complet."
  },
  mobile: {
    settingsDevice: 'Ce téléphone', settingsDeviceHint: 'Préférences enregistrées sur cet appareil.',
    settingsPhone: 'Application et notifications', settingsPhoneHint: 'Installation et alertes de la machine connectée.',
    settingsMachinesHint: 'Connecter, changer ou déconnecter une machine distante.',
    settingsAppearanceHint: 'Thème et couleur pour ce téléphone.',
    settingsRemoteHint: "Les fournisseurs, les projets et l'administration du serveur se gèrent depuis l'application de bureau.",
    settingsBack: 'Retour aux réglages',
    navigation: 'Navigation', threads: 'Conversations', activity: 'Activité', project: 'Choisir un projet',
    activityHint: 'Agents en cours et demandes qui vous attendent.', threadsHint: 'Vos conversations, toutes machines confondues.',
    search: 'Trouver une conversation', unread: 'Non lu', noActivity: "Aucun agent n'attend votre réponse.", noThreads: 'Aucune conversation ne correspond.'
  },
  machines: {
    heading: 'Machines', local: 'Ce PC', projects: 'Projets', recent: 'Récent',
    dynamic: 'Toutes les machines', recentHint: 'Message le plus récent en premier',
    intro: "Connectez des machines pour voir leurs projets et leurs conversations ensemble. Chaque machine exécute ses propres agents sur ses propres fichiers.",
    label: 'Nom de la machine', icon: 'Icône de la machine', icons: { desktop: 'Ordinateur fixe', laptop: 'Portable', server: 'Serveur', rack: 'Baie', cloud: 'Cloud', cpu: 'Processeur' }, link: "Lien d'appairage", add: 'Ajouter une machine', adding: 'Connexion', connect: 'Connecter',
    addHint: "Sur l'autre machine, ouvrez Réglages, Général, Téléphones et appareils, créez un lien d'appairage et collez-le ici. Activez le contrôle total là-bas pour gérer ses comptes et ses réglages depuis celle-ci.",
    labelOptional: 'Nom (facultatif)', labelPlaceholder: 'Serveur de build',
    remove: 'Déconnecter', open: 'Ouvrir la machine', invalidUrl: "L'URL d'une machine doit être une adresse HTTP ou HTTPS, sans identifiants, sans requête ni fragment.",
    duplicate: 'Cette machine est déjà connectée.', noPr: 'Pas de PR', refreshPr: 'Actualiser la pull request',
    prUnavailable: 'Pull request indisponible', manual: 'Connecter avec une URL et un jeton',
    filter: 'Filtrer les machines', all: 'Toutes les machines',
    timeout: "La machine n'a pas répondu en 12 secondes. Vérifiez son adresse et ses origines navigateur, puis reconnectez-la.",
    browserOrigins: 'Origines navigateur autorisées',
    browserOriginsHint: "Pour un navigateur ou un téléphone qui regarde plusieurs machines, ajoutez sur chaque machine distante l'origine qui sert Boite. Une origine http(s) exacte par ligne. Les connexions de bureau n'ont besoin d'aucune origine en plus.",
    agentLinks: 'Liens entre agents', agentLinksHint: 'Permettre aux agents de deux machines connectées en propriétaire de se trouver. Chaque cœur échange son adresse et sa clé publique de signature. Aucun jeton propriétaire ni clé privée ne sont partagés.',
    agentLinksRefresh: 'Actualiser les liens', linkAgents: 'Relier les agents', linkedAgents: "Cœurs d'agents reliés", availableAgentLinks: 'Connexions disponibles',
    noAgentLinks: "Aucune autre machine connectée en propriétaire n'est disponible.", unlinkAgent: 'Révoquer sur cette machine',
    reciprocalLink: 'Confiance mutuelle', oneSidedLink: 'Confiance sur cette machine seulement', publicIdentityHint: "Définissez l'adresse HTTPS publique de chaque cœur dans les réglages généraux avant de relier des PC distincts. Les deux cœurs doivent pouvoir se joindre. Le HTTP local ne fonctionne que sur le même PC.",
  },
  app: {
    name: 'Boite',
    nightlyName: 'boite (de nuit)',
    channelDev: 'Dev',
    channelDevTitle: 'Le canal dev, sur son propre répertoire de données',
    loading: 'Démarrage',
    noEndpointTitle: 'Aucun cœur à joindre',
    noEndpointBody:
      "Ouvrez le lien d'appairage depuis l'application de bureau, ou renseignez l'URL du cœur et son jeton dans les réglages.",
    openSettings: 'Ouvrir les réglages'
  },

  titlebar: {
    minimize: 'Réduire',
    maximize: 'Agrandir',
    restore: 'Restaurer',
    close: 'Fermer',
    quitHold: 'Maintenez Ctrl+Q pour quitter',
    quitHoldHint: 'ou appuyez deux fois'
  },

  appUpdate: {
    heading: "Mises à jour de l'application",
    intro: 'Choisissez les versions suivies par cette application de bureau. Boite et Boite Nightly partagent cette installation, vos conversations et vos réglages.',
    unsupported: 'Les mises à jour automatiques sont disponibles dans les versions Windows x64 installées.',
    channel: 'Canal de publication',
    stable: 'Boite',
    nightly: 'Boite Nightly',
    nightlyHint: "Boite Nightly est expérimentale et peut contenir des changements inachevés. Vous pouvez revenir à Boite même si son numéro de version est inférieur.",
    nightlyTitle: 'Cette application suit les versions expérimentales de Boite Nightly',
    installedVersion: 'Version installée',
    installedChannel: 'Canal installé',
    targetVersion: 'Version de mise à jour',
    published: 'Publication',
    idle: "Aucune recherche de mise à jour n'a encore eu lieu.",
    checking: 'Recherche de mises à jour',
    available: 'La version {version} est disponible.',
    downloading: 'Téléchargement de {received} sur {total}',
    downloaded: '{received} téléchargés',
    ready: 'La version {version} est prête à installer.',
    installing: "Démarrage du programme d'installation",
    current: 'Boite est à jour.',
    failed: 'La mise à jour a échoué.',
    lastChecked: 'Vérifié à {time}',
    progress: "Téléchargement de la mise à jour de l'application",
    notes: 'Notes de version',
    retained: 'Changer de canal conserve vos conversations et vos réglages.',
    check: 'Rechercher des mises à jour',
    retry: 'Réessayer',
    download: 'Télécharger',
    install: 'Installer et redémarrer',
    readyAction: 'Installer la mise à jour',
    detailsAction: 'Détails',
    installTitle: 'Installer la mise à jour de Boite ?',
    installBody: "Boite va se fermer et arrêter les tours d'agents en cours sur cet ordinateur. Les tours interrompus ne redémarrent pas automatiquement.",
    readyTitlebar: 'Installer la mise à jour prête',
    detailsTitlebar: 'Ouvrir les détails de la mise à jour'
  },

  connection: {
    machine: 'Machine',
    local: 'Ce PC',
    current: 'Machine actuelle',
    machines: 'machines connectées',
    oneMachine: 'machine connectée',
    issues: 'à vérifier',
    manage: 'Gérer les machines',
    folder: 'Dossier',
    browse: 'Parcourir les dossiers',
    nativeBrowse: "Choisir dans l'explorateur Windows",
    parent: 'Dossier parent',
    emptyFolder: 'Aucun sous-dossier',
    unavailable: 'Connexion impossible',
    idle: 'Non connecté',
    connecting: 'Connexion',
    ready: 'Connecté',
    closed: 'Déconnecté',
    label: 'Connexion'
  },

  threadStatus: {
    idle: 'au repos',
    queued: 'en attente',
    running: 'en cours',
    waiting: 'vous attend',
    error: 'erreur'
  },

  drafts: {
    name: 'Brouillons',
    hint: 'Un dossier par conversation, dans Documents/Boite',
    openFolder: 'Travailler dans un de mes dossiers',
    pickFolder: 'Ouvrir un dossier'
  },
  firstRun: {
    heading: 'Ouvrir un projet',
    deviceBody: "Les projets s'ouvrent depuis l'application où tourne le cœur. Ceux qu'il détient apparaissent ici.",
    pick: 'Choisir un dossier',
    pathPlaceholder: 'Chemin absolu du dossier',
    add: 'Ouvrir'
  },

  connect: {
    button: 'Connecter une IA',
    title: 'Connecter une IA',
    intro: "Boite fonctionne avec un abonnement IA que vous avez déjà. Choisissez-le, Boite installe ce qu'il faut et ouvre sa page de connexion.",
    more: 'Autres agents',
    plan: {
      claude: 'Avec un forfait Claude Pro ou Max',
      codex: 'Avec un forfait ChatGPT'
    },
    otherPlan: 'Avec votre compte {provider}',
    install: 'Installer {provider}',
    installNote: "Télécharge {size}. Rien d'autre ne change sur cet ordinateur.",
    signIn: 'Se connecter à {provider}',
    signInNote: 'Votre navigateur ouvre la page de connexion. Revenez ici une fois connecté.',
    manual: "{provider} s'installe avec son propre installateur. Lancez-le, puis vérifiez à nouveau ici.",
    manualOpen: "Ouvrir la page d'installation",
    external: '{provider} se connecte depuis sa propre fenêtre. Connectez-vous là-bas, puis vérifiez à nouveau.',
    checkAgain: 'Vérifier à nouveau',
    ready: '{provider} est connecté.',
    use: 'Utiliser {provider}',
    back: 'Retour',
    close: 'Fermer',
    device: "Aucune IA n'est encore connectée sur l'ordinateur qui fait tourner Boite. Connectez-en une depuis cet ordinateur.",
    reconnect: 'Se reconnecter',
    signedOut: "{provider} n'est plus connecté"
  },

  drop: {
    title: 'Déposez pour ajouter un projet',
    body: 'Chaque dossier devient un projet. Les fichiers sont refusés.'
  },

  sidebar: {
    search: 'Rechercher une conversation',
    newThread: 'Nouvelle conversation',
    newThreadIn: 'Nouvelle conversation dans {project}',
    addProject: 'Ajouter un projet',
    noProjects: 'Aucun projet pour le moment.',
    noThreads: 'Aucune conversation pour le moment.',
    noMatch: 'Rien ne correspond.',
    unread: 'Non lu',
    collapse: 'Masquer la barre latérale',
    expand: 'Afficher la barre latérale',
    resize: 'Redimensionner la barre latérale, double-clic pour réinitialiser',
    loadTitle: 'Charge en direct',
    settings: 'Réglages',
    projectMenu: 'Actions du projet',
    copyPath: 'Copier le chemin',
    copied: 'Copié',
    importSession: 'Importer une session Claude Code',
    removeProject: 'Retirer de Boite',
    removeProjectTitle: 'Retirer {project} de Boite ?',
    removeProjectBody: 'Ses conversations partent avec lui. Les fichiers sur le disque restent où ils sont.',
    remove: 'Retirer',
    threadMenu: 'Actions de la conversation',
    open: 'Ouvrir',
    rename: 'Renommer',
    retitle: 'Regénérer le titre',
    retitling: "Rédaction d'un titre",
    pin: 'Épingler',
    unpin: 'Désépingler',
    pinned: 'Épinglée',
    archive: 'Archiver',
    draft: 'Nouvelle conversation'
  },

  palette: {
    placeholder: 'Cherchez une conversation, ou tapez une commande',
    terminal: 'Afficher ou masquer le terminal',
    threads: 'Conversations',
    commands: 'Commandes',
    empty: 'Rien ne correspond.',
    hint: 'Entrée pour ouvrir, Échap pour fermer',
    newThread: 'Nouvelle conversation',
    addProject: 'Ajouter un projet',
    importSession: 'Importer une session Claude Code',
    settings: 'Ouvrir les réglages',
    appearance: "Réglages d'apparence",
    providers: 'Fournisseurs et comptes',
    pair: 'Appairer un téléphone',
    sidebar: 'Afficher ou masquer la barre latérale',
    panel: 'Afficher ou masquer le panneau',
    trace: 'Afficher la trace',
    changes: 'Afficher les modifications',
    files: 'Afficher les fichiers',
    tasks: 'Afficher les tâches',
    pin: 'Épingler cette conversation',
    unpin: 'Désépingler cette conversation',
    rename: 'Renommer cette conversation',
    retitle: 'Regénérer le titre de cette conversation',
    archive: 'Archiver cette conversation',
    themeDark: 'Thème : sombre',
    themeLight: 'Thème : clair',
    themeSystem: 'Thème : système'
  },

  imports: {
    title: 'Importer une session dans {project}',
    intro: "Sessions Claude Code lancées dans ce dossier. L'une d'elles devient une conversation avec son historique, et le tour suivant la continue.",
    loading: 'Recherche des sessions',
    empty: 'Aucune session Claude Code pour ce dossier.',
    imported: 'Importée',
    importing: 'Import en cours',
    close: 'Fermer'
  },

  slash: {
    label: 'Commandes',
    agent: 'Agent',
    app: 'Boite',
    empty: 'Aucune commande ne correspond',
    model: 'Changer de modèle',
    effort: 'Changer le niveau de raisonnement',
    mode: 'Changer le mode de permissions'
  },

  activity: {
    goal: 'Objectif',
    loop: 'Boucle',
    tasks: 'Tâches',
    taskCount: '{done}/{total} tâches',
    showTasks: 'Afficher les tâches',
    goalDescription: 'Continuer à travailler vers un objectif',
    loopDescription: 'Répéter une tâche un nombre de fois ou selon un rythme',
    goalUsage: 'Utilisez /goal suivi d\'un objectif.',
    loopUsage: 'Utilisez /loop 2 prompt pour deux itérations, ou /loop 5m prompt pour un rythme. Entre 1 et 1000 itérations.',
    intervalError: "L'intervalle d'une boucle doit tenir entre 1 seconde et 24 heures.",
    noAttachments: 'Envoyez les images dans un message avant de lancer un objectif ou une boucle.',
    active: 'Active',
    paused: 'En pause',
    complete: 'Terminée',
    pause: 'Mettre en pause',
    resume: 'Reprendre',
    remove: 'Retirer',
    finish: 'Marquer terminée',
    every: 'Toutes les {interval}',
    iterations: '{count} exécutions',
    iteration: 'Itération {count}',
    iterationOf: 'Itération {count} sur {total}',
    history: 'Historique des itérations',
    noHistory: 'Aucune itération terminée pour le moment',
    allTasksDone: 'Toutes les tâches sont terminées',
    waitingTasks: 'En attente de la prochaine tâche',
    stopped: 'Arrêtée',
    running: 'En cours',
    done: 'Terminée',
    error: 'Échec',
    pending: 'À faire',
    in_progress: 'En cours',
    completed: 'Terminée'
  },

  mention: {
    label: 'Fichiers',
    empty: 'Aucun fichier ne correspond',
    more: '{count} de plus, continuez à taper'
  },

  notify: {
    done: 'Terminé',
    failed: 'Échec',
    needsYou: 'Attend votre réponse'
  },

  permissionMode: {
    default: 'Demander',
    acceptEdits: 'Modifier librement',
    bypassPermissions: 'Sans confirmation',
    plan: 'Plan',
    dontAsk: 'Tout refuser'
  },

  permissionModeLong: {
    default: 'Lit librement, demande avant de modifier un fichier ou de lancer une commande',
    acceptEdits: 'Modifie les fichiers sans demander, demande avant de lancer une commande',
    bypassPermissions: 'Exécute tout sans demander, partout sur cet ordinateur',
    plan: 'Plan seulement, aucune modification',
    dontAsk: 'Refuser tout ce qui demanderait une autorisation'
  },

  permissionModeCodex: {
    default: 'Ce dossier',
    defaultLong: 'Modifie et lance des commandes dans ce dossier sans demander, demande pour aller au-delà'
  },

  thread: {
    contextDetails: 'Contexte',
    contextInput: 'Entrée',
    contextCache: 'Entrée en cache',
    contextOutput: 'Sortie',
    contextUsed: 'Utilisé',
    contextFree: 'Disponible',
    contextNoBreakdown: 'Cet agent ne détaille pas sa consommation.',
    contextNoReading: "Aucune mesure reçue de cet agent pour l'instant.",
    contextMeasured: 'Dernière mesure',
    cacheTitle: 'Cache de prompt',
    cacheChipWarm: (left: string) => `Cache de prompt chaud, encore environ ${left}`,
    cacheChipMaybe: (most: string) => `Cache de prompt peut-être encore chaud, ${most} au plus`,
    cacheChipCold: 'Cache de prompt froid',
    cacheCold: 'froid',
    cacheLeft: (left: string) => `encore ${left}`,
    cacheMaybe: (left: string) => `peut-être · ${left}`,
    cacheSwitched: 'Modèle ou compte changé.',
    cacheLifetime: 'Durée de vie',
    cacheSourceReported: 'API',
    cacheSourceDocumented: 'doc',
    cacheRange: (lifetime: string, most: string) => `${lifetime} à ${most}`,
    cacheReadLast: 'Lu au dernier tour',
    minutes: (n: number) => `${n} min`,
    hours: (n: number) => `${n} h`,
    none: 'Aucune conversation ouverte',
    noneBody: 'Choisissez-en une à gauche, ou lancez-en une nouvelle.',
    trace: 'Trace',
    traceHint: 'Processus lancés par cette conversation',
    panel: 'Panneau',
    panelHint: "L'établi à côté de cette conversation",
    terminalHint: 'Terminal dans le dossier de cette conversation',
    cwd: 'Répertoire de travail',
    model: 'Modèle',
    defaultModel: 'Modèle par défaut',
    renamePlaceholder: 'Titre de la conversation',
    startIn: 'Lancer une conversation dans',
    start: 'Lancer une conversation',
    inWorktree: 'dans un worktree',
    inProject: 'dans',
    using: 'avec',
    onEffort: 'en raisonnement {effort}',
    draftMode: {
      default: 'avec demandes d\'autorisation',
      acceptEdits: 'avec les modifications autorisées',
      bypassPermissions: 'avec toutes les permissions',
      plan: 'en mode plan',
      dontAsk: 'avec refus automatique des demandes d\'autorisation'
    },
    changeProject: 'Changer de projet',
    branchHint: 'Travaille dans un worktree sur cette branche',
    contextHint: 'Contexte : {tokens} sur {window} jetons ({percent} %) à la dernière requête',
    contextHintNoWindow: "Contexte : {tokens} jetons à la dernière requête ; l'agent n'a nommé aucune fenêtre"
  },

  chat: {
    accepted: 'Requête acceptée',
    responseStarted: 'Activité reçue',
    working: 'Travaille',
    writing: 'Écrit',
    stopped: 'Arrêté',
    toolCall: '1 appel d\'outil',
    toolCount: '{count} appels d\'outil',
    inputTokens: '{count} jetons en entrée',
    outputTokens: '{count} jetons en sortie',
    cacheTokens: '{read} lus depuis le cache, {write} écrits dedans',
    workingFor: 'Travaille depuis {time}',
    workedFor: 'A travaillé {time}',
    finishedAt: 'fini à {time}',
    backgroundRunning: '{what} encore en cours',
    backgroundJoin: ', ',
    backgroundOne: { shell: '{count} shell', agent: '{count} agent', monitor: '{count} moniteur', workflow: '{count} workflow', other: '{count} tâche' },
    backgroundMany: { shell: '{count} shells', agent: '{count} agents', monitor: '{count} moniteurs', workflow: '{count} workflows', other: '{count} tâches' },
    backgroundStop: 'Arrêter l’agent et ce qu’il exécute en arrière-plan',
    backgroundChip: 'en arrière-plan',
    you: 'Vous',
    assistant: 'Agent',
    system: 'Système',
    toolInput: 'Entrée',
    toolOutput: 'Sortie',
    toolDocuments: 'Documents',
    documentChip: {
      diff: '{count} diff',
      diffs: '{count} diffs',
      doc: '{count} doc',
      docs: '{count} docs'
    },
    documentImage: "Ce que l'outil a produit",
    imagePart: 'Image envoyée avec le message',
    diffHidden: '{count} lignes inchangées',
    diffAdded: '+{count}',
    diffRemoved: '-{count}',
    noOutput: 'Aucune sortie',
    showAll: 'Tout afficher',
    toolStatus: {
      running: 'en cours',
      done: 'terminé',
      error: 'erreur',
      denied: 'refusé'
    },
    thinking: 'Réflexion',
    thinkingShow: 'Afficher le raisonnement',
    thinkingHide: 'Masquer le raisonnement',
    compaction: 'Contexte compacté, de {pre} à {post} jetons',
    compactionNoPost: 'Contexte compacté depuis {pre} jetons',
    compactionUnknown: 'Contexte compacté',
    compactionManual: 'à la main',
    permissionAsk: {
      command: 'Lancer une commande',
      edit: 'Modifier {file}',
      editFiles: 'Modifier des fichiers',
      editFolder: 'Écrire dans {folder} à partir de maintenant',
      write: 'Créer ou remplacer {file}',
      read: 'Lire {file}',
      search: 'Chercher {subject} dans les fichiers',
      fetch: 'Ouvrir {subject}',
      web: 'Chercher {subject} sur le web',
      agent: 'Lancer un agent auxiliaire',
      other: 'Utiliser son outil {tool}'
    },
    permissionTechnical: 'Détails techniques',
    turnFiles: 'Fichiers de cette réponse',
    fileCreated: 'Nouveau',
    fileChanged: 'Modifié',
    fileDeleted: 'Supprimé',
    openFile: 'Ouvrir {name}',
    revealFile: 'Afficher dans le dossier',
    revealFailed: "Le dossier n'a pas pu s'ouvrir : {reason}",
    allow: 'Autoriser',
    deny: 'Refuser',
    allowed: 'Autorisé',
    denied: 'Refusé',
    questionHeading: 'Vous demande',
    questionAsyncHeading: 'Vous demande, sans attendre',
    questionAsyncHint: 'L’agent continue. Votre réponse lui parvient pendant ce tour s’il peut la prendre, sinon juste après ; sans réponse, il poursuit avec un choix par défaut.',
    questionTextLabel: 'Votre propre réponse',
    questionTextPlaceholder: 'Écrivez une réponse',
    questionAnswer: 'Répondre',
    questionAnswered: 'Répondu',
    questionCancelled: 'Le tour est terminé avant la réponse',
    streaming: 'écrit',
    jumpToLatest: 'Aller au dernier message',
    loadingOlder: 'Chargement des messages précédents',
    outline: 'Messages de cette conversation',
    messageGroup: 'Parcourir {count} messages',
    earlierMessages: 'Charger les messages précédents',
    outlineEarlier: 'Afficher les messages précédents dans le rail',
    outlineLater: 'Afficher les messages suivants dans le rail',
    goToMessage: 'Aller au message {number} : {text}',
    copy: 'Copier',
    copied: 'Copié',
    error: 'Erreur'
  },

  coordination: {
    options: 'Réglages avancés',
    heading: 'Réglages de communication', off: 'Désactivée', brief: 'Courte', team: 'Équipe',
    summaryOff: 'Les autres agents ne peuvent pas contacter cette conversation.', summaryBrief: 'Passages de relais courts, jusqu’à 6 envois et 2 réveils par heure.',
    summaryTeam: "Coordination d'équipe, jusqu'à 40 envois et 12 réveils par heure.",
    ownerOnly: 'Seul le propriétaire peut modifier la coordination. Cet appareil peut consulter les contacts et les échanges.',
    resources: 'Ressources et responsabilités', resourcesPlaceholder: "Ce que cet agent gère, peut expliquer ou doit éviter",
    remote: 'Entre projets et machines', remoteHint: 'Partager le titre de cette conversation et ses ressources déclarées avec les agents volontaires des autres projets et machines de confiance. Les deux conversations doivent activer ce choix.',
    pause: 'Suspendre la coordination', resume: 'Reprendre la coordination', paused: 'Suspendue',
    sends: '{used} envois sur {limit} cette heure', wakes: '{used} réveils sur {limit} cette heure', receives: "Les destinataires acceptent jusqu'à {limit} messages par heure.",
    directory: 'Contacts autorisés', refresh: 'Actualiser', directoryEmpty: "Aucune conversation volontaire n'est disponible dans ce projet.", unavailable: 'Contacts indisponibles',
    exchanges: 'Échanges entre agents', noExchanges: "Aucun échange entre agents pour le moment.", details: "Afficher l'échange",
    from: 'De {title} sur {machine}', to: 'À {title}', reply: 'Réponse à {id}',
    receivedFrom: 'Reçu de', sentTo: 'Votre agent a envoyé à', incoming: 'Entrant', outgoing: 'Sortant',
    userSentTo: 'Vous avez envoyé à', userMessageVia: 'Message utilisateur via',
    receivedStatus: 'Reçu',
    noReceipt: "Remis signifie transmis à l'agent destinataire. Les protocoles des agents ne fournissent aucun accusé de lecture.",
    warning: 'Avertissement de coordination',
    status: {
      queued: "En attente d'envoi", received: 'Reçu par le cœur destinataire', delivered: "Transmis à l'agent destinataire",
      uncertain: 'Transmission incertaine. Boite ne la réessaiera pas.', expired: 'Expiré', rejected: 'Refusé'
    },
    bubbleStatus: {
      queued: 'En attente', received: 'En attente', delivered: 'Envoyé', uncertain: 'Non confirmé', expired: 'Expiré', rejected: 'Échec'
    }
  },
  delegation: {
    heading: 'Agents',
    panelHint: "Voir les agents",
    parent: 'Fil principal',
    activeAgents: 'Agents actifs',
    loading: 'Chargement des agents',
    loadingTranscript: 'Chargement de la conversation sélectionnée',
    noTranscript: "Cet agent n'a encore rien écrit.",
    configure: "Réglages de l'équipe",
    enabled: 'Autoriser la délégation',
    ownerOnly: "Seul le propriétaire peut lancer des agents ou modifier les réglages.",
    profiles: "Profils",
    addProfile: 'Ajouter un profil',
    profileName: 'Agent {count}',
    profileLabel: 'Profil de l’agent',
    removeProfile: 'Supprimer le profil',
    maxAgents: 'Agents au total',
    maxConcurrent: 'En parallèle',
    maxTurns: 'Tours de l’équipe',
    maxMinutes: 'Minutes par tour',
    pause: 'Suspendre l’équipe',
    resume: 'Reprendre l’équipe',
    launch: 'Lancer un agent',
    launching: 'Lancement',
    taskPlaceholder: "Tâche à confier",
    team: 'Membres de l’équipe',
    empty: 'Aucun agent délégué pour le moment.',
    agentsShort: 'agents',
    turnsShort: 'tours',
    usage: 'Consommation de l’équipe',
    limitReached: "Limite de tours atteinte. Augmentez-la dans les réglages pour continuer.",
    openThread: 'Ouvrir la conversation',
    backToTeam: 'Retour aux agents',
    stop: 'Arrêter',
    stopAll: 'Tout arrêter',
    messagePlaceholder: 'Écrire à cet agent ou le réorienter',
    send: 'Envoyer à l’agent',
    queuedDelivery: "Message en attente.",
    startedOne: '1 agent lancé',
    startedMany: '{count} agents lancés',
    completed: '{done}/{total} terminés',
    failed: '{count} en erreur',
    stopped: '{count} arrêtés',
    elapsed: 'Temps écoulé',
    showTeam: 'Voir les agents',
    doneStatus: 'Terminé',
    stoppedStatus: 'Arrêté'
  },

  composer: {
    switchTitle: 'Passer une conversation de {tokens} jetons à {provider} ?',
    switchBody: "{provider} démarre une nouvelle session et reçoit des extraits du début et des échanges les plus récents, environ 20 000 jetons. Le reste lui est inaccessible. Compacter avant ne change rien.",
    switchConfirm: "Changer d'agent",
    switchCancel: 'Rester avec {provider}',
    cacheTitle: "Reconstruire le cache d'une conversation de {tokens} jetons ?",
    cacheBody: "Le fournisseur garde cette conversation en cache pour le modèle, l'effort de raisonnement et la vitesse actuels. En changer peut faire renvoyer toute la conversation hors cache au prochain tour, une fois, ce qui consomme bien plus de quota qu'un tour ordinaire.",
    cacheConfirm: 'Changer',
    cacheCancel: 'Garder le réglage',
    options: 'Options du message',
    placeholder: 'Message à {provider} dans {project}',
    placeholderNoProject: "Message à l'agent",
    placeholderNew: 'Que voulez-vous faire ?',
    moreOptions: 'Options',
    pin: 'Garder {option} dans la barre',
    send: 'Envoyer',
    stop: 'Arrêter',
    queued: 'Envoyé à la fin du tour en cours',
    picker: 'Fournisseur et modèle',
    models: 'Modèles',
    searchModels: 'Rechercher un modèle',
    noModels: 'Aucun modèle ne correspond',
    legacyModels: 'Anciens modèles',
    refreshModels: 'Actualiser les modèles',
    probing: "Lecture des modèles de l'agent",
    notInstalled: 'Pas installé sur cette machine',
    installInSettings: 'Installer dans les réglages',
    reasoning: 'Raisonnement',
    effortTitle: 'Niveau de raisonnement',
    speed: 'Vitesse de réponse',
    standardSpeed: 'Vitesse normale',
    effortHint: 'Faites glisser ou utilisez les flèches pour choisir un niveau.',
    favorites: 'Favoris',
    favorite: 'Ajouter aux favoris',
    unfavorite: 'Retirer des favoris',
    favoritesEmpty: 'Mettez une étoile à un modèle pour le retrouver ici.',
    favoriteUnavailable: "Ce favori n'est plus proposé par le compte. Choisissez un autre modèle.",
    compact: 'Compacter le contexte',
    compactBusy: 'Attendez la fin du tour en cours',
    compactUnavailable: "Cet agent n'a pas annoncé de compactage du contexte",
    compactNoSession: 'Envoyez un message avant de compacter',
    contextUnknown: 'Consommation du contexte non communiquée',
    newBadge: 'nouveau',
    lockedHint: 'Une conversation garde son fournisseur et son compte',
    mode: 'Permissions',
    model: 'Modèle',
    unavailable: 'pas installé',
    noAccount: 'aucun compte',
    noProvider: 'Aucune IA connectée',
    hint: 'Entrée pour envoyer, Maj+Entrée pour une nouvelle ligne',
    worktree: 'Worktree',
    worktreeOff: 'Démarrer dans un worktree git sur sa propre branche',
    worktreeOn: 'Démarre dans un worktree git sur sa propre branche',
    attach: 'Joindre des fichiers',
    editQueued: 'Modifier ce message en attente, ou appuyez sur Haut dans un champ vide',
    attachReadError: '{name} est illisible.',
    attachRemove: 'Retirer {name}',
    attachAlt: 'Image jointe',
    attachUnnamed: "l'image collée",
    attachFormat: '{name} est en {type}, or une image doit être de type {formats}.',
    attachTooLarge: '{name} est trop lourde : une image pèse {max} au maximum.',
    attachTooMany: 'Un tour porte {max} images au maximum, donc {name} a été laissée de côté.',
    attachTotalTooLarge: "Les fichiers d'un tour pèsent {max} au maximum à eux tous, donc {name} a été laissé de côté.",
    attachNoImages: "{provider} n'accepte pas les images : envoyez le message sans elles."
  },

  rightPanel: {
    label: 'Panneau',
    toggle: 'Afficher ou masquer le panneau',
    resize: 'Redimensionner le panneau, double-clic pour réinitialiser',
    maximize: 'Agrandir le panneau',
    restore: 'Restaurer le panneau',
    newSurface: 'Ouvrir une surface',
    scrollLeft: 'Faire défiler les onglets vers la gauche',
    scrollRight: 'Faire défiler les onglets vers la droite',
    close: 'Fermer',
    closeTab: 'Fermer {title}',
    closeOthers: 'Fermer les autres',
    closeToRight: 'Fermer à droite',
    closeAll: 'Tout fermer',
    trace: 'Trace',
    traceHint: 'Processus lancés par cette conversation',
    browser: 'Navigateur',
    browserHint: 'Une page à côté de la conversation',
    changes: 'Modifications',
    changesHint: "Ce que la copie de travail a et que HEAD n'a pas",
    files: 'Fichiers',
    filesHint: 'Le répertoire de travail de la conversation',
    file: 'Fichier',
    tasks: 'Tâches',
    tasksHint: "L'objectif, les tâches de l'agent et les todos du projet",
    desktopOnly: "Seulement dans l'application de bureau",
    ownerOnly: "Seulement dans l'application du propriétaire",
    launcher: 'Ouvrir une surface dans ce panneau',
    untitled: 'Navigateur'
  },

  changes: {
    clean: 'Copie de travail propre',
    noBranch: 'Aucune branche',
    ahead: '{count} en avance',
    behind: '{count} en retard',
    count: '{count} modifiés',
    oneCount: '1 modifié',
    staged: 'Indexé',
    stagedShort: 'I',
    binary: 'Fichier binaire, rien à montrer ligne par ligne',
    truncated: "Ce fichier a été tronqué : le diff ci-dessous n'est pas le fichier entier.",
    pick: 'Choisissez un fichier pour voir son diff',
    loading: 'Lecture de la copie de travail',
    renamedFrom: 'Renommé depuis {path}',
    status: {
      added: 'Ajouté',
      modified: 'Modifié',
      deleted: 'Supprimé',
      renamed: 'Renommé',
      copied: 'Copié',
      untracked: 'Non suivi',
      conflict: 'Conflit'
    }
  },

  tasks: {
    goalSection: 'Objectif et boucle',
    noActivity: "Aucun objectif ni boucle sur cette conversation",
    nextRun: 'Prochain passage {time}',
    iterations: '{count} itérations',
    agentSection: "Tâches de l'agent",
    noTasks: "L'agent n'a signalé aucune liste de tâches",
    todoSection: 'Todos du projet',
    noTodos: 'Aucun todo sur ce projet',
    addPlaceholder: 'Ajouter un todo',
    add: 'Ajouter',
    awaiting: 'Vous attend',
    awaitingHint: 'Cette carte attend votre confirmation',
    markOpen: 'Remettre à faire',
    markClaimed: 'Marquer comme vous attendant',
    markDone: 'Confirmer que c\'est fait',
    removeTodo: 'Supprimer ce todo',
    collapse: 'Replier cette section',
    expand: 'Déplier cette section'
  },

  files: {
    tree: 'Fichiers du répertoire de travail',
    noRoot: 'Aucun répertoire de travail',
    filter: 'Filtrer',
    filterHint: 'Restreindre les lignes déjà chargées',
    reading: 'Lecture de ce dossier',
    empty: 'Ce dossier est vide',
    noMatch: 'Aucune ligne chargée ne correspond',
    failed: 'Ce dossier est illisible. {reason}',
    capped: 'Seules les {count} premières entrées de ce dossier sont listées.',
    expandRow: 'Déplier ce dossier',
    collapseRow: 'Replier ce dossier',
    openRow: 'Ouvrir ce fichier',
    readFailed: 'Ce fichier est illisible. {reason}',
    writeFailed: "Ce fichier n'a pas pu être enregistré. {reason}",
    readingFile: 'Lecture de ce fichier',
    noFile: 'Cet onglet ne porte aucun chemin',
    truncated: "Ce fichier a été coupé à sa limite de taille : ce qui suit n'est pas le fichier entier et ne peut pas être enregistré.",
    readOnly: "Enregistrer un fichier appartient au propriétaire, celui-ci s'ouvre donc en lecture seule.",
    save: 'Enregistrer',
    saving: 'Enregistrement',
    unsaved: 'Modifications non enregistrées',
    discardOne: 'Fermer {name} sans enregistrer ?',
    discardMany: 'Fermer {count} fichiers sans enregistrer ?',
    discardBody: 'Le texte saisi depuis le dernier enregistrement sera perdu.',
    discardConfirm: 'Fermer sans enregistrer',
    editorLabel: 'Contenu du fichier',
    lineOf: 'Ligne {line}',
    zoomIn: 'Agrandir',
    zoomOut: 'Réduire',
    fit: 'Ajuster',
    actual: '1:1',
    natural: '{width} x {height}',
    picture: "L'image de ce fichier",
    download: 'Télécharger ce fichier',
    binary: 'Rien ici ne se lit comme du texte.'
  },

  browser: {
    back: 'Précédent',
    forward: 'Suivant',
    reload: 'Recharger',
    urlPlaceholder: 'Rechercher ou saisir une URL',
    openExternal: 'Ouvrir dans le navigateur du système',
    slotEmpty: "La page s'affiche ici dès que la coque fournit la vue web"
  },

  terminal: {
    title: 'Terminal',
    hide: 'Masquer le terminal',
    close: 'Fermer le shell',
    resize: 'Redimensionner le terminal'
  },

  trace: {
    exact: 'Tous les processus enfants suivis',
    limited: 'Suivi des processus limité',
    finished: 'Terminé',
    parent: 'PID parent',
    cpuTime: 'Temps CPU',
    currentMemory: 'Mémoire actuelle',
    active: 'actifs',
    recorded: 'enregistrés',
    exe: 'Exécutable',
    pid: 'PID',
    started: 'Démarré',
    duration: 'Durée',
    cpu: 'CPU',
    memory: 'Mémoire maximale',
    io: 'E/S',
    exit: 'Sortie',
    live: 'en cours',
    empty: "Cette conversation n'a lancé aucun processus.",
    modeLabel: 'Mode de trace'
  },

  protection: {
    intro: 'Empêcher les agents de vous déranger et décider de ce qu\'ils consomment.',
    quiet: 'Tranquillité',
    limits: 'Limites de ressources',
    tasks: 'Gestionnaire de tâches',
    windows: "La mise au second plan, le son et les limites de ressources s'appliquent sur un hôte Windows.",
  },
  resources: {
    heading: 'Protection',
    empty: "Aucune conversation ne consomme quoi que ce soit pour l'instant.",
    live: 'Processus en cours',
    totals: 'Totaux',
    processes: 'processus',
    killTree: "Tuer l'arborescence",
    killConfirm: 'Tuer tous les processus de cette conversation ?',
    killConfirmYes: 'Tuer',
    killConfirmNo: 'Annuler',
    killed: 'Tué'
  },

  install: {
    action: 'Installer',
    update: 'Mettre à jour',
    retry: 'Réessayer',
    repair: 'Réinstaller',
    cancel: 'Annuler',
    remove: 'Désinstaller',
    removeTitle: 'Désinstaller {provider} ?',
    removeBody: 'Les fichiers téléchargés par Boite partent avec. Vos comptes restent, et il pourra être réinstallé plus tard.',
    removeConfirm: 'Désinstaller',
    removeCancel: 'Garder',
    absent: 'Pas installé, {size}',
    downloading: 'Téléchargement, {percent}',
    verifying: "Vérification de l'archive",
    extracting: 'Décompression',
    upToDate: 'Installé par Boite, version {version}',
    updateAvailable: 'Version {installed}, {available} disponible',
    progress: 'Progression du téléchargement'
  },

  accounts: {
    heading: 'Fournisseurs',
    login: 'Se connecter',
    loginStarting: 'Démarrage de la connexion',
    loginOpen: 'Ouvrir la page de connexion',
    loginHint: 'Terminez dans votre navigateur. Cette ligne passera prête toute seule.',
    loginInputPlaceholder: 'Collez le code donné par la page, si elle en donne un',
    loginRedirectPlaceholder: "Sur un autre appareil ? Collez l'adresse localhost sur laquelle la page se termine",
    loginSend: 'Envoyer',
    loginCancel: 'Annuler',
    terminalHint: 'Répondez à ses questions dans le terminal, puis fermez-le une fois connecté.',
    terminalDone: 'Fermer le terminal',
    remove: 'Supprimer',
    removeTitle: 'Supprimer {account} ?',
    removeBody: "Cela déconnecte le compte de Boite et supprime ses fichiers. Un compte utilisé par une conversation ne peut pas être supprimé.",
    removeDefaultBody: "Boite cesse d'utiliser ce login. Il reste connecté sur votre ordinateur. Un compte utilisé par une conversation ne peut pas être supprimé.",
    status: {
      unknown: 'inconnu',
      ok: 'ok',
      unauthenticated: 'non connecté',
      error: 'erreur'
    }
  },

  usage: {
    heading: 'Consommation',
    note: "Les coûts sont estimés au tarif API. Sur un abonnement, ce n'est pas une facture.",
    thread: 'Conversation',
    input: 'Entrée',
    output: 'Sortie',
    cacheRead: 'Cache lu',
    cacheWrite: 'Cache écrit',
    cost: 'Estimation au tarif API',
    total: 'Total',
    empty: 'Aucun jeton dépensé pour le moment.',
    today: "aujourd'hui",
    intro: 'Ce que les agents ont dépensé via Boite, par jour, fournisseur et modèle. Les jetons comptent les lectures et les écritures de cache.',
    range: 'Période',
    days: '{days} jours',
    metric: 'Mesure',
    metrics: { tokens: 'Jetons', cost: 'Estimation API', turns: 'Tours' },
    totalOf: {
      tokens: 'Jetons, {days} derniers jours',
      cost: 'Estimation au tarif API, {days} derniers jours',
      turns: 'Tours, {days} derniers jours'
    },
    summary: '{turns} tours · {tokens} jetons · {cost} au tarif API',
    overview: "Vue d'ensemble",
    chart: 'Par jour',
    chartLabel: '{metric} par jour et par fournisseur. Utilisez les flèches pour lire chaque jour.',
    share: '{percent} du total',
    breakdown: 'Détail',
    byModel: 'Par modèle',
    byDay: 'Par jour',
    model: 'Modèle',
    day: 'Jour',
    turns: 'Tours',
    tokens: 'Jetons',
    cache: 'Cache',
    noPrice: 'sans tarif',
    defaultModel: 'Modèle par défaut',
    other: 'Autre',
    threads: 'Conversations les plus gourmandes',
    threadTurns: '{turns} tours',
    untitled: 'Conversation sans titre',
    archived: 'Archivée',
    emptyRange: "Aucun tour terminé sur les {days} derniers jours.",
    unpriced: "{providers} ne donnent aucun tarif, leurs tours n'ajoutent donc rien au coût.",
    unreported: "{count} tours n'ont rapporté aucune consommation. Ils comptent seulement comme des tours.",
    limits: 'Limites',
    limitsIntro: "Fenêtres d'abonnement telles que chaque fournisseur les a rapportées la dernière fois.",
    limitsOwner: "Les limites d'abonnement sont lues sur l'ordinateur qui fait tourner Boite. Ouvrez cette page là-bas pour les voir.",
    limitsEmpty: 'Aucun fournisseur ne rapporte encore de limite. Connectez-en un dans Fournisseurs.',
    notMonitored: 'Non surveillés : {accounts}',
    refresh: 'Actualiser la consommation',
    loading: 'Lecture de la consommation',
    failed: 'Lecture de la consommation impossible : {error}',
    phoneHint: 'Jetons et coût API par jour, fournisseur et modèle sur la machine connectée.'
  },

  settings: {
    heading: 'Réglages',
    modelDefaults: 'Modèles par défaut',
    modelDefaultsHint: 'Modèle et niveau de raisonnement des nouvelles conversations, par fournisseur. Enregistré sur cet appareil. Les conversations existantes gardent leurs choix.',
    modelDefaultUnavailable: "{provider} ne propose pas le modèle par défaut {model} sur ce compte. Choisissez un modèle disponible dans le sélecteur, ou changez le défaut dans les réglages.",
    tabs: {
      general: 'Général',
      appearance: 'Apparence',
      keyboard: 'Clavier',
      accounts: 'Fournisseurs',
      plugins: 'Extensions',
      usage: 'Consommation',
      resources: 'Protection',
      experiments: 'Expérimentations'
    },
    back: 'Retour aux conversations',
    projects: 'Projets',
    projectsHint: 'Clic droit sur un projet dans la barre latérale pour le retirer de Boite.',
    projectsDevice: "Les dossiers s'ajoutent et se retirent depuis l'application où tourne le cœur.",
    language: 'Langue',
    languageHint: "Enregistrée sur cet appareil. Système suit la langue configurée sur votre machine.",
    languageSystem: 'Système',
    languageNames: { en: 'English', fr: 'Français' },
    theme: 'Thème',
    accent: "Couleur d'accent",
    accentHint: 'Raisonnement, boutons, liens et indicateurs de focus',
    accentCustom: "Couleur d'accent personnalisée",
    accentNames: ['Bleu', 'Violet', 'Rose', 'Orange', 'Ambre', 'Vert', 'Turquoise'],
    themeSystem: 'Système',
    themeDark: 'Sombre',
    themeLight: 'Clair',
    themeGrain: 'Grain',
    experiments: {
      intro: "Ce n'est pas fini. Ça peut changer de forme ou disparaître dans une version suivante."
    },
    material: 'Matériau de la fenêtre',
    materialHint: 'Ce que Windows dessine derrière la fenêtre',
    workspace: 'Espace de travail',
    startIn: "L'appli s'ouvre sur",
    startInHint: "Là où une nouvelle conversation attend à l'ouverture de l'appli. Nouvelle conversation commence toujours dans le projet affiché.",
    startDrafts: 'Brouillons',
    startProject: 'Le dernier projet',
    panelStart: "Le panneau latéral s'ouvre sur",
    panelStartHint: "Ce que le panneau montre quand il s'ouvre sans rien dedans.",
    panelLauncher: 'Son menu',
    panelFiles: 'Fichiers',
    panelChanges: 'Modifications',
    materialAcrylic: 'Acrylique',
    materialMica: 'Mica',
    materialSolid: 'Opaque',
    connection: 'Connexion',
    localCore: "Cette application tourne sur le cœur qu'elle a lancé sur cet ordinateur.",
    coreAt: 'Connecté au cœur à {url}.',
    pairingLink: "Lien d'appairage",
    pairingLinkPlaceholder: 'http://hote:port/?grant=',
    pair: 'Appairer',
    pairHint:
      "Collez un lien émis par l'autre cœur, depuis ses propres réglages ou avec boite-core pair --owner sur la machine où il tourne. La clé qu'il devient reste sur cet ordinateur.",
    useLocal: "Utiliser le cœur de cet ordinateur",
    useLocalHint: 'Les cœurs mémorisés ci-dessous le restent.',
    environments: 'Cœurs mémorisés',
    environmentsHint: "Un cœur appairé ou connecté reste ici. Y revenir ne demande aucun nouveau lien : la clé tient jusqu'à sa révocation là-bas ou son oubli ici.",
    envCurrent: 'actuel',
    envSwitch: 'Basculer',
    envForget: 'Oublier',
    manual: 'URL du cœur et jeton',
    coreUrl: 'URL du cœur',
    token: 'Jeton',
    connect: 'Connecter',
    scheduler: 'Ordonnanceur',
    maxConcurrentTurns: 'Tours simultanés maximum',
    perAccountConcurrency: 'Simultanéité par compte',
    warmProcessMinutes: 'Minutes de processus gardé chaud',
    listenOnLan: "Écouter sur le réseau local pour qu'un téléphone puisse s'appairer",
    listenOnLanHint: "Prend effet au prochain démarrage du cœur, et une option --host ou --lan l'emporte",
    agentCpuCapPercent: 'Plafond CPU de tous les agents, en pourcentage de la machine (0 = aucun, Windows)',
    threadMemoryCapMb: "Plafond mémoire par arborescence de conversation, en Mo (0 = aucun, Windows)",
    background: 'Arrière-plan',
    closeToTray: 'Garder Boite en marche quand la fenêtre se ferme',
    closeToTrayHint: "Désactivé par défaut. Activez pour le réduire dans la zone de notification et laisser les tours continuer. Quitter arrête toujours Boite.",
    notifications: "Me prévenir quand une conversation se termine ou pose une question",
    notificationsHint: "Une bulle pour une conversation que vous ne regardez pas, ou quand Boite n'est pas la fenêtre au premier plan. Cette machine seulement.",
    notificationsDenied: 'Les notifications sont bloquées pour Boite sur ce système ; autorisez-les dans ses réglages.',
    focusGuard: 'Garder les fenêtres des agents en arrière-plan',
    focusGuardHint: "Les fenêtres qu'un agent ouvre passent derrière Boite au lieu de vous voler le focus",
    muteAgents: 'Couper le son des agents',
    muteAgentsHint: "Les sons joués par un processus d'agent n'atteignent jamais vos haut-parleurs",
    reapOrphans: 'Arrêter ce que les agents laissent tourner',
    reapOrphansHint: "Dix secondes après un tour, un processus dont le parent est sorti est arrêté, comme ceux qu'une commande interrompue laisse derrière elle. Windows seulement.",
    asyncQuestions: 'Laisser les agents poser des questions sans s’arrêter',
    asyncQuestionsHint: 'Les agents sans questions asynchrones propres apprennent `boite ask` au début d’une session. Codex pose ses questions ainsi nativement.',
    save: 'Enregistrer',
    saved: 'Enregistré',
    core: 'Cœur',
    version: 'Version',
    protocol: 'Protocole',
    os: 'Système',
    pid: 'PID',
    dataDir: 'Répertoire de données',
    endpoint: 'Point de connexion',
    noCore: 'Pas connecté à un cœur.',
    pairing: {
      heading: 'Téléphones et appareils',
      intro: "Un lien d'appairage ouvre Boite sur un autre appareil avec une clé à lui. Il sert une fois et tient dix minutes.",
      mint: "Nouveau lien d'appairage",
      copy: 'Copier le lien',
      expires: "Valable une fois, jusqu'à {time}",
      qr: "Le lien d'appairage en QR code",
      scan: 'Scannez le code avec le téléphone, ou ouvrez le lien dessus.',
      lanHint: "Le cœur n'écoute que sur cette machine : activez le réseau local dans Ordonnanceur, plus bas, puis redémarrez-le, avant qu'un téléphone puisse atteindre ce lien.",
      devices: 'Appareils appairés',
      noDevices: 'Aucun appareil appairé pour le moment.',
      thisDevice: 'cet appareil',
      lastSeen: 'vu {when}',
      revoke: 'Révoquer',
      revokeTitle: 'Révoquer cet appareil ?',
      revokeBody: "Il se déconnecte tout de suite et sa clé n'ouvre plus rien. Réappairez-le avec un nouveau lien.",
      paired: "Cet appareil est appairé avec une clé à lui. Les liens d'appairage se créent depuis l'application de bureau.",
      owner: 'Contrôle total',
      ownerHint:
        "Pour un autre de vos ordinateurs : sa clé pilote ce cœur comme vous le faites, comptes, projets et réglages compris. Laissez désactivé pour un téléphone.",
      ownerTag: 'contrôle total',
      pasteOwner: "Collez-le dans Réglages, Général, sur l'autre ordinateur."
    }
  },

  keyboard: {
    heading: 'Raccourcis',
    intro: "Cliquez sur un raccourci et appuyez sur les touches que vous voulez à la place. Le changement s'applique aussitôt, sur toutes les fenêtres de cette machine.",
    search: 'Filtrer les commandes',
    groups: { general: 'Général', surfaces: 'Panneau latéral', thread: 'Conversation et message', theme: 'Thème' },
    record: 'Appuyez sur les touches',
    change: 'Changer le raccourci',
    reset: 'Revenir au défaut',
    resetAll: 'Tout réinitialiser',
    clear: 'Retirer le raccourci',
    conflict: '{chord} lance déjà "{command}". Le déplacer ici ?',
    replace: 'Le déplacer ici',
    needsModifier: "Tenez Ctrl, Alt ou Win avec la touche. Une touche seule, ou avec Maj seulement, c'est de la frappe.",
    noMatch: 'Aucune commande ne correspond.',
    file: 'Modifier le fichier à la main',
    fileHint:
      'Un objet JSON qui associe un identifiant de commande à un raccourci, de la forme "mod+shift+k", ou null pour retirer une touche. mod vaut Ctrl ici et Cmd sur un Mac. Seules les entrées nommées changent ; les autres gardent leur valeur par défaut.',
    example: 'Exemple',
    command: 'Commande',
    id: 'Identifiant',
    chord: 'Raccourci',
    none: 'Non défini',
    custom: 'modifié',
    problems: 'Refusé',
    problemsHint: "Ces lignes du fichier n'ont pas été appliquées. Corrigez-les et enregistrez ; le reste du fichier est en service.",
    commands: {
      palette: 'Ouvrir la palette de commandes',
      browser: 'Ouvrir la surface navigateur',
      changes: 'Ouvrir la surface des modifications',
      files: "Ouvrir l'arbre des fichiers",
      tasks: 'Ouvrir la surface des tâches',
      closeSurface: 'Fermer la surface active',
      stash: 'Mettre le message de côté, ou le reprendre',
      sendAndDraft: 'Envoyer et ouvrir une nouvelle conversation',
      pin: 'Épingler ou désépingler cette conversation'
    }
  },

  experiments: {
    chatArtifacts: { title: 'Fichiers et aperçus dans le chat', hint: 'Ouvrir les liens de fichiers et afficher les fichiers envoyés par un agent dans la conversation' },
    previewComments: { title: 'Commentaires sur les aperçus', hint: 'Sélectionner un élément dans le navigateur intégré et l’ajouter au brouillon de la conversation' },
    themeGrain: {
      title: 'Thème Grain',
      hint: 'Un fond grainé qui passe du gris clair en haut à gauche au noir en bas à droite'
    },
    sessionImport: {
      title: 'Import de session Claude Code',
      hint: 'Transformer une session lancée dans le terminal en conversation, depuis le menu du projet et la palette'
    },
    promptCache: {
      title: 'Minuteur du cache de prompt',
      hint: 'Une horloge à côté de la jauge de contexte, qui décompte le temps pendant lequel le provider garde la conversation en cache'
    }
  },

  quotas: {
    trayHeading: 'Consommation',
    trayIntro: "Limites d'abonnement",
    names: { claude: 'Claude', codex: 'Codex', antigravity: 'Antigravity', grok: 'Grok', opencode: 'OpenCode Go' },
    off: 'Désactivé',
    noReading: 'Indisponible',
    notConnected: 'Non connecté',
    autoConnect: 'Utilise votre compte connecté',
    cliSource: 'Compte du CLI Antigravity',
    cliHint: "Utilise le compte connecté via agy sur cet ordinateur. Installez le CLI Antigravity 1.1.11 ou plus récent, connectez-vous une fois, puis activez le suivi ci-dessous. C'est indépendant des comptes Antigravity isolés de Boite.",
    connectHint: 'Connectez {provider} une fois dans Fournisseurs. La consommation apparaît ici toute seule.',
    connect: 'Connecter un compte',
    noReset: 'Heure de réinitialisation non communiquée',
    heading: 'Quotas des fournisseurs',
    intro: "Limites d'abonnement communiquées par vos fournisseurs. C'est distinct des jetons dépensés dans Boite.",
    remaining: '{percent} % restants',
    resets: 'Repart {time}',
    checked: 'Mis à jour {time}',
    stale: 'Dernière lecture réussie',
    empty: "Connectez un fournisseur pour voir ses limites d'abonnement.",
    unsupported: "Ce fournisseur n'expose pas ses quotas d'abonnement ici.",
    disabled: 'Le suivi des quotas est désactivé pour ce compte.',
    loading: 'Lecture des limites du fournisseur',
    monitor: "Suivre les quotas d'abonnement",
    providers: 'Gérer les fournisseurs',
    unavailable: 'Aucune lecture de quota disponible.',
    refresh: 'Actualiser les quotas',
    quit: 'Quitter Boite',
  },
  harnessUpdates: {
    heading: 'Mises à jour des agents',
    intro: 'Chaque machine vérifie ses agents toutes les six heures et les met à jour là où ils tournent.',
    auto: 'Mettre les agents à jour automatiquement',
    autoHint: "Cette machine met un agent à jour lorsqu'aucune de ses conversations ne tourne et que personne n'est connecté",
    check: 'Vérifier maintenant', checking: 'Vérification',
    available: (name: string, version: string) => `${name} ${version} est disponible`,
    availableShort: 'Mise à jour disponible',
    installed: (version: string) => `Version installée : ${version}`,
    on: (machine: string) => `Sur ${machine}`,
    update: 'Mettre à jour', skip: 'Ignorer', retry: 'Réessayer',
    updating: (name: string) => `Mise à jour de ${name}`,
    failed: (name: string) => `La mise à jour de ${name} a échoué`,
    upToDate: 'À jour', unknown: 'Vérifie lui-même', runUpdater: 'Lancer sa mise à jour',
    skipped: (version: string) => `${version} ignorée`,
    unskip: 'Proposer à nouveau', none: "Aucun agent sur cette machine ne possède de programme de mise à jour que Boite peut lancer.",
    route: { managed: 'Installé par Boite', self: 'Votre installation' }
  },
  providerSettings: {
    heading: 'Fournisseurs',
    intro: "Installez un agent, connectez-vous, c'est tout. Un agent déjà connecté sur cet ordinateur est repris tout seul.",
    step: {
      installing: 'Installation',
      install: 'Pas installé',
      repair: 'Des fichiers installés manquent',
      manual: 'Pas installé',
      'signing-in': 'Connexion',
      'sign-in': 'Pas connecté',
      external: 'Pas connecté',
      ready: 'Prêt'
    },
    readyMore: '{identity} et {count} autres',
    accountsCount: '{count} comptes',
    thenSignIn: 'La connexion démarre à la fin du téléchargement.',
    manualHint: '{provider} vient avec son propre installateur. Lancez-le, puis revenez : Boite le trouve tout seul.',
    externalHint: '{provider} se connecte depuis sa propre application. Connectez-vous là-bas, puis vérifiez à nouveau.',
    setup: "Instructions d'installation",
    refresh: 'Vérifier à nouveau',
    details: 'Détails',
    isolated: 'Connecté via Boite',
    default: 'Votre login en ligne de commande',
    reconnect: 'Se reconnecter',
    check: 'Vérifier',
    models: '{count} modèles disponibles',
    addAccount: 'Ajouter un autre compte',
    useCli: 'Utiliser mon login en ligne de commande',
    executable: 'Lancé depuis',
    accounts: 'Comptes',
    noAccounts: 'Aucun compte pour le moment.',
    installation: 'Installation',
    version: 'Version'
  },
  plugins: {
    heading: 'Extensions',
    intro: "Les extensions ajoutent des fonctions à Boite. Chacune est un programme qui tourne sur la machine hébergeant votre cœur, téléchargé en https et vérifié contre le SHA-256 publié par son manifeste.",
    installedHeading: 'Installées',
    installedEmpty: "Aucune extension installée. Installez-en une recommandée, ou ajoutez-en une depuis une URL git.",
    recommendedHeading: 'Recommandées',
    recommendedAllInstalled: 'Toutes les extensions recommandées sont installées.',
    recommendedBy: 'Recommandée par Boite',
    install: 'Installer',
    update: 'Mettre à jour vers {version}',
    retry: 'Réessayer',
    reinstall: 'Réinstaller',
    remove: 'Désinstaller',
    stateInstalled: 'Installée',
    stateAvailable: 'Pas installée',
    stateInstalling: 'Téléchargement et vérification',
    stateError: "L'installation a échoué",
    stateRejected: 'Refusée par Boite',
    updateAvailable: '{version} disponible',
    source: 'Code source',
    atCommit: '{ref} au commit {commit}',
    pools: 'Pools de comptes',
    empty: 'Aucun compte enregistré dans ce pool.',
    add: 'Enregistrer le login CLI actuel',
    switch: 'Utiliser ce compte',
    forget: 'Oublier le compte',
    active: 'Actif',
    refresh: 'Actualiser',
    removeTitle: 'Désinstaller {name} ?',
    removeBody: "Supprime le dossier de l'extension dans le répertoire de données de Boite, c'est-à-dire tout ce que son installation a écrit. Ce que le programme a enregistré ailleurs, ses logins par exemple, reste en place.",
    switchTitle: 'Changer le login CLI ?',
    switchBody: "Cela change le login CLI par défaut du fournisseur pour les tours suivants, y compris hors de Boite. Les comptes Boite isolés gardent le leur.",
    forgetTitle: 'Oublier ce login enregistré ?',
    forgetBody: "Retire ce login du pool de l'extension.",
    cliScope: 'Ce sont les pools de comptes CLI. Ils sont distincts des comptes isolés connectés dans Fournisseurs.',
    addHeading: 'Ajouter depuis une URL git',
    addHint: "Collez l'URL https d'un dépôt git avec un boite-plugin.json à sa racine. Boite lit le manifeste et montre ce qu'il téléchargerait avant que quoi que ce soit ne soit installé.",
    urlLabel: 'URL du dépôt',
    urlPlaceholder: 'https://github.com/owner/repo',
    refLabel: 'Branche, tag ou commit',
    refPlaceholder: 'Branche par défaut',
    inspect: 'Lire le manifeste',
    inspecting: 'Lecture',
    previewSource: 'Source',
    previewReplaces: 'Remplace',
    previewDownloads: 'Télécharge',
    previewDigest: 'SHA-256',
    previewRuns: 'Exécute',
    previewPools: 'Pools de comptes',
    trust: "Ce programme tourne avec vos permissions sur la machine qui héberge votre cœur. Ne l'installez que si vous faites confiance à qui le publie.",
    confirmAdd: 'Installer {name}',
    refusedTitle: 'Boite a refusé cette extension',
    refusedFile: 'Fichier',
    refusedField: 'Champ',
    refusedExpected: 'Attendu',
    dismiss: 'Ignorer',
  },

  time: {
    now: 'à l\'instant'
  },

  errors: {
    prefix: 'Erreur',
    activityUnsupported: "Ce cœur ne gère pas les objectifs ni les boucles. Mettez Boite à jour sur {machine}, puis reconnectez-vous. Votre commande n'a pas été envoyée.",
    pullRequestUnsupported: "Mettez Boite à jour sur la machine qui héberge cette conversation pour afficher sa pull request. Ce cœur ne sait pas encore les chercher.",
    noEndpoint: "Aucun point de connexion n'a pu être résolu.",
    connect: 'Connexion au cœur impossible.',
    clipboard: 'Le presse-papiers a refusé le texte.',
    revoked: "Cet appareil a été révoqué depuis l'application de bureau. Ouvrez un nouveau lien d'appairage pour vous reconnecter.",
    pairingLink: "Ce n'est pas un lien d'appairage : il lui faut une adresse http ou https portant un grant."
  },

  units: {
    bytes: 'o',
    kilobytes: 'ko',
    megabytes: 'Mo',
    gigabytes: 'Go',
    milliseconds: 'ms',
    seconds: 's',
    minutes: 'min',
    hours: 'h',
    tokens: 'jetons'
  },

  common: {
    none: 'aucun',
    unknown: 'inconnu',
    yes: 'oui',
    no: 'non',
    close: 'Fermer',
    moreInfo: 'À propos : {topic}',
    refresh: 'Actualiser',
    dismiss: 'Ignorer',
    cancel: 'Annuler',
    confirm: 'Confirmer'
  },

  onboarding: {
    privacy: {
      title: 'VENDEZ VOTRE ÂME À BOITE !',
      intro: "Boite compte quelques statistiques d'utilisation anonymes pour savoir quoi corriger en premier. Vos messages, fichiers et comptes ne quittent jamais votre machine, l'application marche pareil dans tous les cas, et vous pouvez changer d'avis quand vous voulez dans les réglages.",
      question: 'Marché conclu ?',
      video: 'Mème Trade Offer',
      basic: 'NON ! Ça suffit',
      basicDefault: '(par défaut)',
      basicHint: "Des compteurs d'installations actives, de lancements, de conversations et de résultats des tours. Les identifiants d'usage changent chaque jour. Aucun profil.",
      deal: 'MARCHÉ CONCLU',
      dealHint: "Ajoute les modèles publics choisis, le niveau de raisonnement, les modes de vitesse et de permission, les durées et les volumes de jetons, sous un identifiant aléatoire stable. Les modèles privés comptent comme « autre ». Ça aide beaucoup. Merci !",
      optOut: 'Si vous ne voulez VRAIMENT pas aider Boite, Réglages > Général > Confidentialité et statistiques désactive tout. :c',
      doc: 'Ce qui est collecté'
    },
    demo: {
      pause: 'Pause', play: 'Rejouer', resume: 'Reprendre',
      record: 'Cliquez sur le micro', speak: 'Dictez votre message', review: "Relisez avant d'envoyer",
      listening: 'Écoute en cours', draft: 'Votre brouillon', localLabel: 'Sur cet ordinateur',
      chooseAgent: "Choisissez l'agent suivant", handoff: 'Codex reprend la conversation', checked: 'Libellés vérifiés. Contraste amélioré.', nextMessage: 'Écrire à Codex',
      before: 'Avant', after: 'Après', buttonBefore: 'Envoyer', buttonAfter: 'Envoyer le message', changedFile: 'ContactForm.svelte', changesReady: 'Deux lignes modifiées',
      background: 'En cours en arrière-plan', writing: 'Préparer le lancement de demain', notes: 'Notes', noteOne: 'Relire le formulaire de contact', noteTwo: 'Publier le portfolio',
      taskResult: 'Formulaire prêt', loginResult: 'Connexion réparée', testsResult: 'Tests réussis', hoverTray: "Survolez l'icône Boite",
      conversation: "Changer d'agent", voice: 'Dicter', panel: 'Voir les modifications',
      task: 'Créer mon portfolio', secondTask: 'Réparer la connexion', thirdTask: 'Écrire les tests', working: 'En cours', request: 'Ajoute un formulaire de contact', answer: 'Le formulaire est prêt.', followup: "Vérifie maintenant l'accessibilité", continued: 'Même conversation. Même historique.',
      voiceWords: 'Rends les boutons plus lisibles', voiceHint: 'Parlez, relisez le brouillon, puis envoyez.',
      changes: 'Modifications', reviewed: 'Relisez les changements à côté du chat.',
      usageLabel: 'Claude', window: 'Limite sur 5 h', used: '24 % utilisés', reset: 'Réinitialisation dans 2 h 10', tray: "Dans la barre des tâches, près de l'horloge", trayHint: "Survolez l'icône Boite pour voir vos limites sans ouvrir l'application.",
      desktop: 'Votre ordinateur', phone: 'Votre téléphone', synced: 'La même conversation', reachHint: "Après un appairage par QR code, suivez vos agents sur votre téléphone. Votre ordinateur continue de les faire tourner.",
      notification: 'Formulaire de contact terminé', quietBody: "Vos agents travaillent sans prendre votre écran ni vos haut-parleurs.",
      installVoice: 'Installer la dictée locale', downloadVoice: 'Environ 200 Mo. Le son reste sur cet ordinateur.', installingVoice: 'Téléchargement du moteur vocal', cancelVoice: 'Annuler le téléchargement', readyVoice: 'La dictée est prête. Utilisez le micro du champ de message.', retryVoice: 'Réessayer la configuration vocale',
      workspaceBody: 'Cliquez sur une démo pour la voir en action.',
    },
    label: 'Prise en main',
    skip: 'Passer',
    back: 'Retour',
    next: 'Suivant',
    done: 'À moi de boiter',
    step: 'Étape {index} sur {total}',
    progress: "Aller à l'étape {index} : {title}",
    replay: 'Revoir la présentation',
    replayHint: "Les mêmes écrans qu'au premier lancement. Rien de ce que vous avez réglé n'est défait.",
    changeLater: 'Tout ça se retrouve dans les réglages.',

    profile: {
      title: "D'abord, lequel êtes-vous ?",
      everyday: "Je ne suis pas dev ! Ne m'embrouillez pas avec du code et des commandes !",
      everydayHint: "Une nouvelle conversation attend dans Documents/Boite jusqu'à ce que vous lui donniez un dossier, la barre reste simple et l'agent demande avant d'agir.",
      developer: 'Je suis dev, mettez-moi la totale.',
      developerHint: "L'appli s'ouvre sur votre dernier projet, l'effort et le worktree restent dans la barre, le panneau s'ouvre sur les modifications.",
      later: "Rien n'est retiré, dans un cas comme dans l'autre. Le menu Options du champ de message et les réglages changent tout ça."
    },

    welcome: {
      title: 'Boite fait tourner vos agents',
      body: 'Une conversation par tâche. Les agents continuent pendant que vous faites autre chose.'
    },

    agents: {
      title: 'Une conversation qui suit votre travail',
      body: "Changez d'agent, dictez un message, relisez le résultat. Sans changer de conversation.",
      demoModel: 'Claude Sonnet 5',
      demoEffort: 'Élevé',
      demoMode: 'Demander'
    },

    voice: {
      title: 'Parler au lieu de taper',
      body: "Appuyez sur le micro et parlez. Vous relisez le texte avant qu'il parte.",
      open: 'Réglages de la voix',
      reading: 'Lecture du moteur vocal'
    },

    panel: {
      title: 'Le panneau à côté de la conversation',
      body: 'Modifications, fichiers, tâches et navigateur, à une touche.',
      open: 'Raccourcis clavier',
      noKey: 'aucune touche'
    },

    usage: {
      title: "Voir ce qu'il vous reste",
      body: "Voyez quel abonnement se remplit et quand il se réinitialise, même avec Boite en arrière-plan.",
      monitor: 'Lire les limites de {account}',
      noAccounts: 'Aucun fournisseur connecté pour le moment.',
      connect: 'Connecter un fournisseur',
      deviceHint: 'Les limites sont lues sur la machine qui héberge le cœur.'
    },

    reach: {
      title: 'Éloignez-vous. Gardez le fil.',
      phone: 'Sur votre téléphone',
      phoneBody: 'Scannez un QR code et votre téléphone retrouve les mêmes conversations, avec les notifications.',
      pair: 'Appairer un téléphone',
      machines: 'Un autre Boite',
      machinesBody: 'Pilotez depuis cette application un Boite qui tourne sur un serveur ou un autre ordinateur.',
      connect: 'Connecter une machine',
      deviceHint: "L'appairage et les machines se gèrent depuis l'application où tourne le cœur."
    },

    quiet: {
      title: 'Des agents qui ne vous coupent pas',
      deviceHint: 'Le focus et le son sont des réglages de la machine qui héberge le cœur.'
    },

    project: {
      title: 'Ouvrir votre premier projet',
      body: 'Le dossier dans lequel un agent travaille.',
      opened: '{count} projet ouvert.',
      openedMany: '{count} projets ouverts.',
      deviceBody: "Les projets s'ouvrent depuis l'application où tourne le cœur."
    }
  }
};
