import { accentHex, colorTools, detailTokens, normalizeHex, paletteTokens, parseColorState, type ColorState, type Palette, type PaletteDetails, type ColorRole } from './color-math';
export { parseColorState } from './color-math';

export type ColorMode = 'dark' | 'light';
export type PaletteId = 'default' | 'oled' | 'catppuccin' | 'tokyo-night' | 'nord' | 'gruvbox' | 'amethyst';
export const PALETTES: PaletteId[] = ['default', 'oled', 'catppuccin', 'tokyo-night', 'nord', 'gruvbox', 'amethyst'];
export const COLORS_KEY = 'boite.theme-colors.v1';
export const COLORS_EVENT = 'boite-colors-changed';
let volatile: ColorState | undefined;
function state(): ColorState {
  if (volatile) return parseColorState(volatile);
  try { return parseColorState(JSON.parse(localStorage.getItem(COLORS_KEY) ?? 'null')); }
  catch { return { version: 1 }; }
}
export function colorMode(): ColorMode { return document.documentElement.dataset.theme === 'light' ? 'light' : 'dark'; }
function hue(): number {
  try {
    const raw = localStorage.getItem('boite.accent-hue');
    const value = raw === null ? 260 : Number(raw);
    return Number.isFinite(value) && value >= 0 && value <= 360 ? value : 260;
  } catch { return 260; }
}
export function presetPalette(id: PaletteId, mode: ColorMode): Palette {
  if (id === 'oled') mode = 'dark';
  const css = getComputedStyle(document.documentElement);
  const role = (name: ColorRole) => normalizeHex(css.getPropertyValue(`--palette-${mode}-${id}-${name}`).trim()) ?? '';
  const details: PaletteDetails = {};
  for (const key of Object.keys(detailTokens) as (keyof PaletteDetails)[]) {
    const suffix = key === 'surfaceLow' ? 'surface-low' : key === 'surfaceHigh' ? 'surface-high' : detailTokens[key].slice('--color-'.length);
    const value = normalizeHex(css.getPropertyValue(`--palette-${mode}-${id}-${suffix}`).trim());
    if (value) details[key] = value;
  }
  return { background: role('background'), frame: role('frame'), surface: role('surface'), foreground: role('foreground'), accent: id === 'default' ? accentHex(hue()) : role('accent'), ...(Object.keys(details).length ? { details } : {}) };
}
export function readPalette(mode = colorMode()): Palette {
  const saved = state()[mode];
  return saved ? { ...saved, accent: saved.accent ?? accentHex(hue()) } : presetPalette('default', mode);
}
export function hasCustomColors(mode = colorMode()): boolean { return !!state()[mode]; }
const TOKEN_NAMES = ['--color-background', '--color-frame', '--color-surface-2', '--color-foreground', '--color-on-foreground', '--color-accent', '--color-accent-ink', '--color-reasoning-on', '--accent-hue', '--color-danger-hover', '--color-on-danger', ...Object.values(detailTokens)];
export function applyColors(mode = colorMode()): void {
  const root = document.documentElement;
  for (const name of TOKEN_NAMES) root.style.removeProperty(name);
  root.style.setProperty('--accent-hue', String(hue()));
  const p = state()[mode];
  if (!p) {
    const base = root.dataset.theme === 'grain' ? getComputedStyle(root).getPropertyValue('--palette-grain-theme-color').trim() : presetPalette('default', mode).background;
    if (base) document.querySelector('meta[name="theme-color"]')?.setAttribute('content', base);
    return;
  }
  for (const [name, value] of Object.entries(paletteTokens(p))) root.style.setProperty(name, value);
  document.querySelector('meta[name="theme-color"]')?.setAttribute('content', p.background);
}
function save(next: ColorState): void {
  try { localStorage.setItem(COLORS_KEY, JSON.stringify(next)); volatile = undefined; }
  catch { volatile = next; }
  applyColors();
  window.dispatchEvent(new Event(COLORS_EVENT));
}
export function setPalette(mode: ColorMode, palette: Palette): void {
  const valid = parseColorState({ version: 1, [mode]: palette })[mode];
  if (valid) save({ ...state(), [mode]: valid });
}
export function resetColors(mode = colorMode()): void {
  const next = state();
  delete next[mode];
  save(next);
}
export function resetAccentColor(): void {
  const next = state();
  const p = next[colorMode()];
  if (p) { delete p.accent; if (p.details) delete p.details.accentSoft; save(next); }
}
export function startColors(): () => void {
  const onstorage = (event: StorageEvent) => {
    if (event.key !== COLORS_KEY && event.key !== null) return;
    volatile = undefined;
    applyColors();
    window.dispatchEvent(new Event(COLORS_EVENT));
  };
  window.addEventListener('storage', onstorage);
  return () => window.removeEventListener('storage', onstorage);
}

/** Generated by Vite for both dev and production, ahead of styles and modules. */
export function colorsBootScript(): string {
  return `try {
    var colorTools = (${colorTools.toString()})();
    var savedColors = colorTools.parseColorState(JSON.parse(localStorage.getItem('${COLORS_KEY}') || 'null'));
    var palette = savedColors[document.documentElement.dataset.theme === 'light' ? 'light' : 'dark'];
    if (palette) {
      var tokens = colorTools.paletteTokens(palette);
      Object.keys(tokens).forEach(function(name) { document.documentElement.style.setProperty(name, tokens[name]); });
      document.querySelector('meta[name="theme-color"]')?.setAttribute('content', palette.background);
    }
  } catch (e) {}`;
}
