import { afterAll, beforeAll, expect, test } from 'bun:test';
import { join } from 'node:path';
import { BrowserPage, freePort } from './lib/cdp.ts';
import { startUi } from './lib/ui.ts';

let server: Awaited<ReturnType<typeof startUi>>;
let page: BrowserPage;
const id = (name: string) => `[data-testid="${name}"]`;
async function capture(name: string) {
  await page.evaluate(`Promise.all([document.fonts.ready, ...document.getAnimations().filter(a => a.effect?.getTiming().iterations !== Infinity).map(a => a.finished.catch(() => {}))])`);
  await page.screenshot(join(import.meta.dir, '.artifacts', name));
}
beforeAll(async () => {
  const port = await freePort();
  server = await startUi(port);
  page = await BrowserPage.launch({ url: `http://127.0.0.1:${port}/?fake=1&open=recent` });
  await page.waitFor(`document.querySelector('${id('nav-settings')}')`);
}, 30_000);
afterAll(async () => { await page?.close(); await server?.close(); }, 15_000);

test('configure, inspect, synchronize and disconnect a brain at desktop and phone widths', async () => {
  await page.send('Emulation.setDeviceMetricsOverride', { width: 1400, height: 1100, deviceScaleFactor: 1, mobile: false });
  await page.click(id('nav-settings'));
  await page.click(id('settings-tab-brain'));
  await page.waitFor(`document.querySelector('${id('brain-page')}')?.getAttribute('aria-busy') === 'false'`);
  expect(await page.evaluate(`document.querySelector('${id('brain-page')}').textContent`)).toContain('Connect your brain');
  await capture('brain-empty.png');
  await page.type(id('brain-path'), '/work/shared-brain');
  await page.click(id('brain-save'));
  await page.waitFor(`document.querySelectorAll('${id('brain-entry')}').length === 1`);
  expect(await page.evaluate(`document.querySelector('${id('brain-path')}')`)).toBeNull();
  await page.click(id('brain-global'));
  await page.waitFor(`document.querySelector('${id('brain-global')}')?.checked === true && !document.querySelector('${id('brain-global')}').disabled`);
  expect(await page.evaluate(`document.querySelector('${id('brain-links')}').textContent`)).toContain('7/7');
  await page.click(id('brain-startup'));
  await page.waitFor(`document.querySelector('${id('brain-startup')}')?.checked === true && !document.querySelector('${id('brain-startup')}').disabled`);
  await page.click(id('brain-periodic'));
  await page.waitFor(`document.querySelector('${id('brain-interval')}')?.value === '15' && !document.querySelector('${id('brain-interval')}').disabled`);
  await page.evaluate(`const field = document.querySelector('${id('brain-interval')}'); field.value = '30'; field.dispatchEvent(new Event('change', { bubbles: true }))`);
  await page.waitFor(`document.querySelector('${id('brain-interval')}')?.value === '30' && !document.querySelector('${id('brain-interval')}').disabled`);
  await page.click(id('brain-category-skill'));
  expect(await page.evaluate(`document.querySelector('${id('brain-inventory')}').textContent`)).toContain('code-review');
  await page.click(`${id('brain-entry')} summary`);
  expect(await page.evaluate(`document.querySelector('${id('brain-entry')}').open`)).toBe(true);
  await page.click(id('brain-category-plugin'));
  expect(await page.evaluate(`document.querySelector('${id('brain-inventory')}').textContent`)).toContain('Install plugins through their agent');
  await page.click(id('brain-category-instructions'));
  await capture('brain-desktop.png');
  await page.click(id('brain-sync'));
  await page.waitFor(`document.querySelector('${id('brain-last-sync')}')?.textContent.includes('Last synchronized')`);
  await page.click(id('brain-enabled'));
  await page.waitFor(`document.querySelector('${id('brain-enabled')}')?.checked === false && document.querySelector('${id('brain-page')}')?.getAttribute('aria-busy') === 'false'`);
  await page.click(id('brain-refresh'));
  await page.waitFor(`document.querySelector('${id('brain-page')}')?.getAttribute('aria-busy') === 'false'`);
  expect(await page.evaluate(`document.querySelector('${id('brain-enabled')}').checked`)).toBe(false);
  expect(await page.evaluate(`document.querySelector('${id('brain-links')}')`)).toBeNull();
  expect(await page.evaluate(`document.querySelector('${id('brain-startup')}').checked`)).toBe(true);
  expect(await page.evaluate(`document.querySelector('${id('brain-interval')}').value`)).toBe('30');
  await page.click(id('brain-enabled'));
  await page.waitFor(`document.querySelector('${id('brain-enabled')}')?.checked === true && document.querySelector('${id('brain-page')}')?.getAttribute('aria-busy') === 'false'`);
  expect(await page.evaluate(`document.querySelector('${id('brain-links')}').textContent`)).toContain('7/7');
  await page.evaluate(`localStorage.setItem('boite.locale', 'fr'); location.reload()`);
  await page.waitFor(`document.querySelector('${id('nav-settings')}')`);
  await page.click(id('nav-settings'));
  await page.click(id('settings-tab-brain'));
  await page.waitFor(`document.querySelector('${id('brain-page')}')?.getAttribute('aria-busy') === 'false'`);
  await page.type(id('brain-path'), '/work/shared-brain');
  await page.click(id('brain-save'));
  await page.waitFor(`document.querySelector('${id('brain-sync')}')`);
  expect(await page.evaluate(`document.querySelector('${id('brain-sync')}').textContent`)).toContain('Synchroniser');
  await page.click(id('brain-global'));
  await page.waitFor(`document.querySelector('${id('brain-global')}')?.checked === true && !document.querySelector('${id('brain-global')}').disabled`);
  await page.click(id('brain-startup'));
  await page.waitFor(`document.querySelector('${id('brain-startup')}')?.checked === true && !document.querySelector('${id('brain-startup')}').disabled`);
  await page.click(id('brain-periodic'));
  await page.waitFor(`document.querySelector('${id('brain-interval')}')?.value === '15' && !document.querySelector('${id('brain-interval')}').disabled`);
  await capture('brain-desktop-fr.png');
  await page.send('Emulation.setDeviceMetricsOverride', { width: 390, height: 844, deviceScaleFactor: 1, mobile: true });
  await page.waitFor(`document.querySelector('${id('brain-inventory')}')`);
  expect(await page.evaluate('document.documentElement.scrollWidth <= 390')).toBe(true);
  await capture('brain-phone.png');
  await page.click(id('brain-change'));
  await page.click(id('brain-disconnect'));
  await page.waitFor(`document.querySelector('${id('brain-inventory')}') === null`);
  expect(await page.evaluate(`document.querySelector('${id('brain-path')}').value`)).toBe('');
  await page.type(id('brain-path'), 'relative');
  await page.click(id('brain-save'));
  await page.waitFor(`document.querySelector('${id('brain-error')}')`);
  expect(await page.evaluate(`document.querySelector('${id('brain-error')}').textContent`)).toContain('absolute');
  await capture('brain-phone-error.png');
}, 30_000);

test('the hooks card and a hook line in the thread at desktop and phone widths', async () => {
  const origin = await page.evaluate<string>('location.origin');
  const text = (selector: string) => page.evaluate<string>(`document.querySelector(${JSON.stringify(selector)})?.textContent.replace(/\\s+/g, ' ').trim() ?? ''`);
  const show = (selector: string, block: 'start' | 'center' | 'end') => page.evaluate(`document.querySelector(${JSON.stringify(selector)}).scrollIntoView({ block: '${block}' })`);
  await page.evaluate(`localStorage.removeItem('boite.locale')`);
  // Navigate before leaving the phone layout: the last test ends on the phone
  // settings overlay, whose history.back() on a resize cancels a pending navigation.
  await page.navigate(`${origin}/?fake=1&open=recent`);
  await page.send('Emulation.setDeviceMetricsOverride', { width: 1280, height: 900, deviceScaleFactor: 1, mobile: false });
  // The seeded thread ends on a turn its own PostToolUse hook stopped.
  await page.waitFor(`document.querySelector('${id('hook-part')}')`);
  expect(await page.evaluate(`document.querySelector('${id('hook-part')}').dataset.outcome`)).toBe('stopped');
  expect(await text(id('hook-part'))).toBe('A hook stopped the turn: Lint failed in src/descriptors.ts. Stopping here so you can look. PostToolUse');
  await show(id('hook-part'), 'center');
  await capture('hook-part-desktop.png');
  await page.click(id('nav-settings'));
  await page.click(id('settings-tab-brain'));
  // Shown with no brain folder connected: hooks are the agents' own, not the brain's.
  await page.waitFor(`document.querySelectorAll('${id('hooks-provider')}').length === 5 && document.querySelector('${id('hooks-recent')}')`);
  expect(await text(`${id('hooks-provider')}[data-provider="codex"] ${id('hooks-issue')}`)).toContain('Work does not get config.toml');
  expect(await text(id('hooks-without'))).toBe('Antigravity and Echo do not run hooks.');
  expect(await page.evaluate(`document.querySelectorAll('${id('hooks-run')}').length`)).toBe(5);
  await page.click(`${id('hooks-provider')}[data-provider="claude"] summary`);
  await page.waitFor(`document.querySelector('${id('hooks-provider')}[data-provider="claude"] details').open`);
  expect(await text(`${id('hooks-provider')}[data-provider="claude"] .detail`)).toContain('Shared with 1 separate account');
  await show(id('hooks-card'), 'start');
  await capture('brain-hooks-desktop.png');
  await page.send('Emulation.setDeviceMetricsOverride', { width: 390, height: 844, deviceScaleFactor: 1, mobile: true });
  await page.waitFor(`document.querySelector('${id('hooks-card')}')`);
  expect(await page.evaluate('document.documentElement.scrollWidth <= 390')).toBe(true);
  await show(id('hooks-card'), 'start');
  await capture('brain-hooks-phone.png');
  await show(id('hooks-recent'), 'end');
  await capture('brain-hooks-phone-recent.png');
  await page.navigate(`${origin}/?fake=1&open=recent`);
  await page.waitFor(`document.querySelector('${id('hook-part')}')`);
  expect(await page.evaluate('document.documentElement.scrollWidth <= 390')).toBe(true);
  await show(id('hook-part'), 'center');
  await capture('hook-part-phone.png');
  await page.evaluate(`localStorage.setItem('boite.locale', 'fr')`);
  await page.navigate(`${origin}/?fake=1&open=recent`);
  await page.send('Emulation.setDeviceMetricsOverride', { width: 1280, height: 900, deviceScaleFactor: 1, mobile: false });
  await page.click(id('nav-settings'));
  await page.click(id('settings-tab-brain'));
  await page.waitFor(`document.querySelectorAll('${id('hooks-provider')}').length === 5 && document.querySelector('${id('hooks-recent')}')`);
  expect(await text(`${id('hooks-provider')}[data-provider="claude"] ${id('hooks-counters')}`)).toBe('412 exécutions · 2 bloquées · 1 en échec');
  await show(id('hooks-card'), 'start');
  await capture('brain-hooks-desktop-fr.png');
  await page.evaluate(`localStorage.removeItem('boite.locale')`);
}, 30_000);
