import { afterAll, beforeAll, expect, test } from 'bun:test';
import { join } from 'node:path';
import { BrowserPage, freePort } from './lib/cdp';
import { startDevUi } from './lib/ui.ts';
let server: { close(): Promise<void> };
let page: BrowserPage;
beforeAll(async () => {
  const port = await freePort();
  server = await startDevUi(port);
  page = await BrowserPage.launch({url:`http://127.0.0.1:${port}/?fake=1&open=recent`,windowSize:{width:1300,height:850}});
  await page.waitFor(`document.querySelector('[data-thread-id]')`);
}, 90000);
afterAll(async () => { await page?.close(); await server?.close(); }, 15_000);

async function update(code: string) {
  await page.evaluate(`(async () => { const {workspace} = await import('/src/lib/workspace.svelte.ts'); const store = workspace.active; const thread = store.openThread; ${code} })()`);
}
async function capture(name: string) {
  await page.evaluate(`Promise.all(document.getAnimations().filter(a => a.effect?.getTiming().iterations !== Infinity).map(a => a.finished.catch(() => {})))`);
  await page.screenshot(join(import.meta.dir,'.artifacts',name + '.png'));
}
test('typing dots cover silent and buffered replies, yield to visible activity, and receipts follow actual activity', async () => {
  await update(`window.__answer = JSON.parse(JSON.stringify(thread.messages.at(-1)));`);
  await update(`thread.messages = thread.messages.filter(m => m.role === 'user'); const turn = thread.turns[0]; turn.status = 'running'; turn.startedAt = Date.now(); turn.finishedAt = null; thread.status = 'running';`);
  await page.waitFor(`document.querySelector('[data-testid="turn-summary"][data-status="running"]')`);
  expect(await page.evaluate(`document.querySelector('.author') === null`)).toBe(true);
  expect(await page.evaluate(`document.querySelectorAll('.receipts .received').length`)).toBe(1);
  expect(await page.evaluate(`document.querySelector('[data-testid="turn-elapsed"]').textContent`)).toMatch(/^Working for \d+s$/);
  expect(await page.evaluate(`document.querySelector('[data-testid="turn-finished-at"]') === null`)).toBe(true);
  expect(await page.evaluate(`document.querySelector('[data-testid="turn-summary"]').getBoundingClientRect().left < document.querySelector('.bubble').getBoundingClientRect().left`)).toBe(true);
  expect(await page.evaluate(`document.querySelectorAll('[data-testid="typing-indicator"]').length`)).toBe(1);
  expect(await page.evaluate(`document.querySelectorAll('[data-testid="typing-dot"]').length`)).toBe(3);
  expect(await page.evaluate(`document.querySelector('[data-testid="typing-indicator"]').getAttribute('aria-label')`)).toBe('Writing');
  expect(await page.evaluate(`document.querySelector('.reply-pending').textContent.trim()`)).toBe('');
  await update(`thread.turns[0].status = 'queued'; thread.status = 'queued';`);
  await page.waitFor(`!document.querySelector('[data-testid="typing-indicator"]')`);
  await update(`thread.turns[0].status = 'running'; thread.status = 'running'; store.connection = 'closed';`);
  expect(await page.evaluate(`document.querySelector('[data-testid="typing-indicator"]') === null`)).toBe(true);
  await update(`store.connection = 'ready';`);
  await page.waitFor(`document.querySelector('[data-testid="typing-indicator"]')`);
  await page.send('Emulation.setEmulatedMedia', {features:[{name:'prefers-reduced-motion',value:'reduce'}]});
  expect(await page.evaluate(`getComputedStyle(document.querySelector('[data-testid="typing-dot"]')).animationName`)).toBe('none');
  await page.send('Emulation.setEmulatedMedia', {features:[{name:'prefers-reduced-motion',value:'no-preference'}]});
  await page.evaluate(`document.documentElement.dataset.motion = 'reduced'`);
  expect(await page.evaluate(`getComputedStyle(document.querySelector('[data-testid="typing-dot"]')).animationName`)).toBe('none');
  await page.evaluate(`delete document.documentElement.dataset.motion`);
  await page.evaluate(`Object.defineProperty(document,'hidden',{value:true,configurable:true}); document.dispatchEvent(new Event('visibilitychange'));`);
  await page.waitFor(`getComputedStyle(document.querySelector('[data-testid="typing-dot"]')).animationPlayState === 'paused'`);
  await page.evaluate(`delete document.hidden; document.dispatchEvent(new Event('visibilitychange'));`);
  await capture('quiet-chat-waiting');
  await update(`const answer = window.__answer; answer.parts = [{type:'text',text:''}]; answer.state = 'streaming'; thread.messages.push(answer);`);
  await page.waitFor(`document.querySelector('[data-role="assistant"] [data-testid="typing-indicator"]')`);
  expect(await page.evaluate(`document.querySelectorAll('[data-testid="typing-indicator"]').length`)).toBe(1);
  await update(`thread.messages.at(-1).parts[0].text = 'A complete answer.';`);
  await page.waitFor(`document.querySelectorAll('.receipts .received').length === 2`);
  expect(await page.evaluate(`document.querySelector('[data-testid="paragraph"]') === null`)).toBe(true);
  expect(await page.evaluate(`document.querySelectorAll('[data-testid="typing-indicator"]').length`)).toBe(1);
  await page.send('Emulation.setDeviceMetricsOverride',{width:390,height:844,deviceScaleFactor:1,mobile:true});
  await page.send('Emulation.setTouchEmulationEnabled',{enabled:true});
  await capture('quiet-chat-typing-phone');
  expect(await page.evaluate(`(() => { const bubble = document.querySelector('.answer-bubble').getBoundingClientRect(), composer = document.querySelector('[data-testid="composer"]').getBoundingClientRect(); return bubble.left >= 0 && bubble.right <= innerWidth && bubble.bottom <= composer.top; })()`)).toBe(true);
  await page.send('Emulation.setDeviceMetricsOverride',{width:1300,height:850,deviceScaleFactor:1,mobile:false});
  await page.send('Emulation.setTouchEmulationEnabled',{enabled:false});
  await update(`thread.messages.at(-1).parts[0].text += '\\n\\nStill writing';`);
  await page.waitFor(`document.querySelector('[data-testid="paragraph"]')`);
  expect(await page.evaluate(`document.querySelectorAll('[data-testid="typing-indicator"]').length`)).toBe(1);
  expect(await page.evaluate(`document.querySelector('.answer-bubble').textContent.includes('Still writing')`)).toBe(false);
  await update(`thread.messages.push({...thread.messages[0],id:'typing-steer',createdAt:Date.now(),parts:[{type:'text',text:'Check the phone layout too.'}]});`);
  await page.waitFor(`document.querySelector('.reply-pending [data-testid="typing-indicator"]')`);
  expect(await page.evaluate(`document.querySelectorAll('[data-testid="typing-indicator"]').length`)).toBe(1);
  await update(`thread.messages.pop();`);
  await page.waitFor(`document.querySelector('.answer-bubble [data-testid="typing-indicator"]')`);
  await update(`thread.status = 'waiting';`);
  await page.waitFor(`!document.querySelector('[data-testid="typing-indicator"]')`);
  await update(`thread.status = 'running'; thread.messages.at(-1).parts.push({type:'tool',toolId:'typing-tool',name:'Read',input:{file_path:'src/app.css'},output:null,status:'running'});`);
  await page.waitFor(`document.querySelector('[data-kind="tool"]')`);
  expect(await page.evaluate(`document.querySelector('[data-testid="typing-indicator"]') === null`)).toBe(true);
  await update(`thread.messages.push({...thread.messages[0],id:'tool-steer',createdAt:Date.now(),parts:[{type:'text',text:'Keep checking the layout.'}]});`);
  expect(await page.evaluate(`document.querySelector('[data-testid="typing-indicator"]') === null`)).toBe(true);
  await capture('quiet-chat-tool-steering');
  await update(`thread.messages.at(-2).parts.at(-1).status = 'done';`);
  await page.waitFor(`document.querySelector('.reply-pending [data-testid="typing-indicator"]')`);
  await update(`thread.messages.pop();`);
  await update(`thread.messages.at(-1).parts.at(-1).status = 'done';`);
  await page.waitFor(`document.querySelector('.reply-pending [data-testid="typing-indicator"]')`);
  await update(`thread.messages.at(-1).parts.push({type:'thinking',text:'Checking the result',startedAt:Date.now()});`);
  // Reasoning right after a call folds into that call's line, which says it is thinking.
  await page.waitFor(`document.querySelector('[data-testid="tool-group"][data-live="true"] [data-testid="tool-group-label"]')?.textContent === 'Thinking'`);
  expect(await page.evaluate(`document.querySelector('[data-testid="thinking-part"]') === null`)).toBe(true);
  expect(await page.evaluate(`document.querySelector('[data-testid="typing-indicator"]') === null`)).toBe(true);
  await update(`thread.messages.push({...thread.messages[0],id:'thinking-steer',createdAt:Date.now(),parts:[{type:'text',text:'Check the desktop too.'}]});`);
  expect(await page.evaluate(`document.querySelector('[data-testid="tool-group"][data-live="true"] .shimmer') !== null`)).toBe(true);
  expect(await page.evaluate(`document.querySelector('[data-testid="typing-indicator"]') === null`)).toBe(true);
  await capture('quiet-chat-thinking-steering');
  await page.send('Emulation.setDeviceMetricsOverride',{width:390,height:844,deviceScaleFactor:1,mobile:true});
  await capture('quiet-chat-thinking-steering-phone');
  expect(await page.evaluate(`document.querySelector('[data-testid="typing-indicator"]') === null`)).toBe(true);
  await page.send('Emulation.setDeviceMetricsOverride',{width:1300,height:850,deviceScaleFactor:1,mobile:false});
  await update(`thread.messages.at(-2).parts.at(-1).finishedAt = Date.now();`);
  await page.waitFor(`document.querySelector('.reply-pending [data-testid="typing-indicator"]')`);
  await update(`thread.messages.pop();`);
  await update(`thread.messages.at(-1).parts = [{type:'text',text:'A complete answer.'}];`);
  await page.waitFor(`document.querySelectorAll('.receipts .received').length === 2`);
  await update(`thread.turns[0].status = 'stopped'; thread.status = 'idle';`);
  await page.waitFor(`!document.querySelector('[data-testid="typing-indicator"]')`);
  await update(`const turn = thread.turns[0]; turn.status = 'done'; turn.finishedAt = turn.startedAt + 3800; thread.status = 'idle'; thread.messages.at(-1).state = 'complete';`);
  await page.waitFor(`document.querySelector('[data-testid="turn-summary"]').dataset.status === 'done'`);
  expect(await page.evaluate(`document.querySelector('[data-testid="typing-indicator"]') === null`)).toBe(true);
  expect(await page.evaluate(`document.querySelector('[data-testid="turn-elapsed"]').textContent`)).toBe('Worked for 3s');
  expect(await page.evaluate(`document.querySelector('[data-testid="turn-finished-at"]').textContent`)).toMatch(/^done \d{1,2}:\d{2}/);
  expect(await page.evaluate(`document.querySelector('[data-testid="turn-tokens"]').textContent`)).toContain('tokens');
  await capture('quiet-chat-done');
}, 30000);
test('context opens on hover, shows exact segments, and compaction needs its own click', async () => {
  await update(`thread.context = {tokens:31000,window:200000,at:Date.now(),breakdown:{input:18000,cache:10000,output:3000}}; thread.sessionId = 'test-session'; window.__compactCalls = 0; store.compact = async () => {window.__compactCalls++;};`);
  await page.evaluate(`document.querySelector('[data-testid="context-meter"]').dispatchEvent(new MouseEvent('mouseenter'))`);
  await page.waitFor(`document.querySelector('[data-testid="context-popup"]')`);
  expect(await page.evaluate(`window.__compactCalls`)).toBe(0);
  expect(await page.evaluate(`document.querySelectorAll('[data-testid="context-popup"] .bar span').length`)).toBe(3);
  expect(await page.evaluate(`document.querySelector('[data-testid="context-popup"]').textContent.includes((31000).toLocaleString())`)).toBe(true);
  await capture('quiet-context-desktop');
  await page.send('Emulation.setDeviceMetricsOverride',{width:390,height:844,deviceScaleFactor:1,mobile:true});
  await capture('quiet-context-phone');
  expect(await page.evaluate(`(() => {const r = document.querySelector('[data-testid="context-popup"]').getBoundingClientRect(); return r.left >= 0 && r.right <= innerWidth;})()`)).toBe(true);
  await page.evaluate(`document.documentElement.dataset.theme = 'light'`);
  await capture('quiet-context-light');
  await page.click('[data-testid="context-compact"]');
  await page.waitFor(`!document.querySelector('[data-testid="context-popup"]')`);
  expect(await page.evaluate(`window.__compactCalls`)).toBe(1);
}, 30000);

test('compaction stays distinct on desktop and phone, then yields to normal work', async () => {
  await update(`
    window.__compactionAnswer = JSON.parse(JSON.stringify(thread.messages.find(m=>m.role==='assistant')));
    const turn = thread.turns[0];
    turn.status = 'running'; turn.startedAt = Date.now() - 9000; turn.finishedAt = null; turn.usage = null;
    turn.execution = {...turn.execution, operation:'compact', automatic:true};
    thread.status = 'running'; thread.background = [];
    thread.messages = [{...thread.messages[0],role:'system',parts:[{type:'text',text:'Automatic compaction'}]}];
    thread.progress = null;
  `);
  await page.waitFor(`document.querySelector('[data-testid="turn-summary"].compacting')`);
  for (const phone of [false, true]) {
    await page.send('Emulation.setDeviceMetricsOverride', {width:phone?390:1280,height:phone?844:900,deviceScaleFactor:1,mobile:phone});
    expect(await page.evaluate(`document.querySelector('[data-testid="turn-summary"]').getAttribute('aria-label')`)).toBe('Compacting conversation');
    expect(await page.evaluate(`document.querySelector('[data-testid="compaction-elapsed"]').textContent`)).toMatch(/^Elapsed: \d+s$/);
    expect(await page.evaluate(`document.querySelector('[data-testid="typing-indicator"], [data-testid="turn-elapsed"], [role="progressbar"]') === null`)).toBe(true);
    expect(await page.evaluate(`(() => {const r=document.querySelector('[data-testid="turn-summary"]').getBoundingClientRect(); return r.left>=0 && r.right<=innerWidth;})()`)).toBe(true);
    await capture(phone ? 'compaction-phone' : 'compaction-desktop');
  }
  await update(`thread.turns[0].status='done'; thread.turns[0].finishedAt=thread.turns[0].startedAt+11000; thread.status='idle';`);
  await page.waitFor(`!document.querySelector('[data-testid="turn-summary"].compacting')`);
  expect(await page.evaluate(`document.querySelector('[data-testid="turn-elapsed"]').textContent`)).toBe('Compacted in 11s');
  await update(`
    const turn=thread.turns[0]; delete turn.execution.operation; turn.status='running'; turn.startedAt=Date.now()-120000; turn.finishedAt=null; thread.status='running';
    thread.progress={turnId:turn.id,phase:'compacting',detail:null,at:Date.now(),providerAt:Date.now()};
    thread.messages[0].role='user'; thread.messages[0].parts=[{type:'text',text:'Continue checking the layout.'}];
    thread.messages.push({...window.__compactionAnswer,state:'streaming',parts:[{type:'text',text:'A finished paragraph.\\n\\nAn unfinished paragraph'}]});
  `);
  await page.waitFor(`document.querySelector('[data-testid="turn-summary"].compacting')`);
  expect(await page.evaluate(`document.querySelector('[data-testid="typing-indicator"], [data-testid="compaction-elapsed"], [data-testid="turn-provider-signal"]') === null`)).toBe(true);
  await update(`thread.progress.phase='working';`);
  await page.waitFor(`!document.querySelector('[data-testid="turn-summary"].compacting') && document.querySelector('[data-testid="typing-indicator"]')`);
  expect(await page.evaluate(`document.querySelector('[data-testid="turn-elapsed"]').textContent`)).toMatch(/^Working for /);
  await update(`thread.turns[0].status='done';thread.turns[0].finishedAt=Date.now();thread.messages.at(-1).state='complete';thread.status='idle';thread.progress=null;`);
}, 30000);
