import { afterAll, beforeAll, expect, test } from 'bun:test';
import { join } from 'node:path';
import { createRequire } from 'node:module';
import { BrowserPage, freePort } from './lib/cdp.ts';
const uiRequire = createRequire(join(import.meta.dir, '../../packages/ui/package.json'));
const { createServer } = await import(uiRequire.resolve('vite'));
let server: { listen(): Promise<unknown>; close(): Promise<void> };
let page: BrowserPage;
let url: string;
async function capture(name: string) {
  await page.evaluate(`Promise.all([document.fonts.ready, ...document.getAnimations().filter(a => a.effect?.getTiming().iterations !== Infinity).map(a => a.finished.catch(() => {}))])`);
  await page.screenshot(join(import.meta.dir, '.artifacts', name));
}
beforeAll(async () => {
  const port = await freePort();
  server = await createServer({ root: join(import.meta.dir, '../../packages/ui'), server: { host: '127.0.0.1', port, strictPort: true }, clearScreen: false });
  await server.listen(); url = `http://127.0.0.1:${port}/?fake=1`;
  page = await BrowserPage.launch({ url });
  await page.waitFor(`document.querySelector('[data-testid=composer-picker]')`);
});
afterAll(async () => { await page?.close(); await server?.close(); });

test('favorites survive reload, reasoning has discrete stops, and the context ring compacts', async () => {
  await page.click('[data-testid=composer-picker]');
  await page.click('[data-provider=claude]');
  await page.waitFor(`document.querySelector('[data-favorite-model="claude-fable-5-1"]')`);
  await capture('models-ranked.png');
  await page.click('[data-favorite-model="claude-fable-5-1"]');
  await page.click('[data-provider=favorites]');
  await page.waitFor(`document.querySelectorAll('[data-testid=favorite-model]').length === 1`);
  await capture('models-favorites.png');
  await page.navigate(url);
  await page.waitFor(`document.querySelector('[data-testid=composer-picker]')`);
  await page.click('[data-testid=composer-picker]');
  await page.waitFor(`document.querySelectorAll('[data-testid=favorite-model]').length === 1`);
  await page.click('[data-testid=favorite-model]');
  await page.waitFor(`document.querySelector('[data-testid=composer-picker]')?.textContent.includes('Fable')`);
  await page.click('[data-testid=composer-effort]');
  await page.waitFor(`document.querySelector('[data-testid=effort-track]')`);
  await page.evaluate(`document.querySelector('[data-testid=effort-track]').dispatchEvent(new KeyboardEvent('keydown', { key:'End', bubbles:true }))`);
  await page.waitFor(`document.querySelector('[data-testid=effort-track]')?.getAttribute('aria-valuenow') === '5'`);
  await capture('reasoning-notches.png');
  await page.send('Emulation.setDeviceMetricsOverride', { width: 390, height: 844, deviceScaleFactor: 1, mobile: true });
  await capture('reasoning-phone.png');
  const bounds = await page.evaluate<{ left: number; right: number }>(`(() => { const r = document.querySelector('[data-testid=composer-effort-menu]').getBoundingClientRect(); return { left:r.left, right:r.right }; })()`);
  expect(bounds.left).toBeGreaterThanOrEqual(0); expect(bounds.right).toBeLessThanOrEqual(390);
  await page.evaluate(`document.dispatchEvent(new PointerEvent('pointerdown', { bubbles:true }))`);
  await page.click('[data-testid=composer-picker]');
  await page.waitFor(`document.querySelector('[data-testid=favorite-model]')`);
  await capture('favorites-phone.png');
  await page.send('Emulation.clearDeviceMetricsOverride', {});
  await page.navigate(url);
  await page.waitFor(`document.querySelector('[data-testid=context-compact]') && !document.querySelector('[data-testid=context-compact]').disabled`);
  await capture('context-compact-before.png');
  await page.click('[data-testid=context-compact]');
  await page.waitFor(`document.querySelector('[data-testid=compaction-part][data-trigger=manual]')`);
  await page.waitFor(`document.querySelector('[data-testid=context-meter]')?.title.includes('7,8k') || document.querySelector('[data-testid=context-meter]')?.title.includes('7.8k') || document.querySelector('[data-testid=context-meter]')?.title.includes('8k')`);
  await capture('context-compact-after.png');
  await page.click('[data-testid=composer-picker]');
  await page.waitFor(`document.querySelector('[data-testid=favorite-model]')`);
  await page.click('[aria-label="Remove from favorites"]');
  await page.waitFor(`document.querySelector('[data-testid=favorites-empty]')`);
  expect(await page.evaluate(`JSON.parse(localStorage.getItem('boite.model-favorites.v1')).length`)).toBe(0);
}, 30_000);
