import { afterAll, beforeAll, expect, test } from 'bun:test';
import { join } from 'node:path';
import { createRequire } from 'node:module';
import { BrowserPage, freePort } from './lib/cdp.ts';
const uiRequire = createRequire(join(import.meta.dir, '../../packages/ui/package.json'));
const { createServer } = await import(uiRequire.resolve('vite'));
let server: { listen(): Promise<unknown>; close(): Promise<void> };
let page: BrowserPage;
beforeAll(async () => {
  const port = await freePort();
  server = await createServer({ root: join(import.meta.dir, '../../packages/ui'), server: { host: '127.0.0.1', port, strictPort: true }, clearScreen: false });
  await server.listen();
  page = await BrowserPage.launch({ url: `http://127.0.0.1:${port}/?fake=1&open=recent`, showTour: true });
  await page.send('Emulation.setDeviceMetricsOverride', { width: 1400, height: 1000, deviceScaleFactor: 1, mobile: false });
  await page.waitFor(`document.querySelector('[data-testid="nav-settings"]')`);
}, 30_000);
afterAll(async () => { await page?.close(); await server?.close(); });
const card = '[data-testid="telemetry-settings"]';
test('owner controls consent on desktop and phone; captures both layouts', async () => {
  await page.waitFor(`document.querySelector('[data-testid="onboarding-next"]')`);
  await page.click('[data-testid="onboarding-next"]');
  await page.waitFor(`document.querySelector('${card} input')`);
  expect(await page.evaluate(`Array.from(document.querySelectorAll('${card} input')).map(x => x.checked)`)).toEqual([true, false]);
  await page.evaluate(`Promise.all([document.fonts.ready, ...document.getAnimations().filter(a => a.effect?.getTiming().iterations !== Infinity).map(a => a.finished.catch(() => {}))])`);
  await page.screenshot(join(import.meta.dir, '.artifacts/onboarding-telemetry-desktop.png'));
  await page.send('Emulation.setDeviceMetricsOverride', { width: 390, height: 844, deviceScaleFactor: 1, mobile: true });
  await page.click('[data-testid="onboarding-dot-welcome"]');
  await page.click('[data-testid="onboarding-locale-fr"]');
  await page.click('[data-testid="onboarding-next"]');
  await page.waitFor(`document.querySelector('${card} input')`);
  await page.evaluate(`Promise.all([document.fonts.ready, ...document.getAnimations().filter(a => a.effect?.getTiming().iterations !== Infinity).map(a => a.finished.catch(() => {}))])`);
  expect(await page.evaluate('document.documentElement.scrollWidth <= innerWidth')).toBe(true);
  await page.screenshot(join(import.meta.dir, '.artifacts/onboarding-telemetry-phone-fr.png'));
  await page.click('[data-testid="onboarding-skip"]');
  await page.waitFor(`!document.querySelector('[data-testid="onboarding"]')`);
  await page.send('Emulation.setDeviceMetricsOverride', { width: 1400, height: 1000, deviceScaleFactor: 1, mobile: false });
  await page.click('[data-testid="nav-settings"]');
  await page.waitFor(`document.querySelector('${card} input')`);
  expect(await page.evaluate(`Array.from(document.querySelectorAll('${card} input')).map(x => x.checked)`)).toEqual([true, false]);
  await page.click(`${card} input`);
  await page.waitFor(`!document.querySelector('${card} input').checked`);
  await page.evaluate(`document.querySelectorAll('${card} input')[1].click()`);
  await page.waitFor(`document.querySelectorAll('${card} input')[1].checked`);
  await page.evaluate(`document.querySelector('${card}').scrollIntoView(); document.fonts.ready`);
  await page.evaluate(`Promise.all(document.getAnimations().filter(a => a.effect?.getTiming().iterations !== Infinity).map(a => a.finished.catch(() => {})))`);
  await page.screenshot(join(import.meta.dir, '.artifacts/telemetry-desktop.png'));
  await page.send('Emulation.setDeviceMetricsOverride', { width: 390, height: 844, deviceScaleFactor: 1, mobile: true });
  await page.waitFor(`document.querySelector('[data-testid="mobile-settings-phone"]')`);
  await page.click('[data-testid="mobile-settings-phone"]');
  await page.waitFor(`document.querySelector('${card} input')`);
  await page.evaluate(`document.querySelector('${card}').scrollIntoView(); document.fonts.ready`);
  expect(await page.evaluate('document.documentElement.scrollWidth <= innerWidth')).toBe(true);
  await page.screenshot(join(import.meta.dir, '.artifacts/telemetry-phone.png'));
  await page.click(`${card} input`);
  await page.waitFor(`Array.from(document.querySelectorAll('${card} input')).every(x => !x.checked)`);
}, 30_000);
