//! The opening prompt of a restarted orchestrator session.
//!
//! The harness session is disposable and the chat history is not (the
//! `orchestrator_messages` table survives everything). When a session is
//! restarted — past its age ceiling, after a compaction, or because the user
//! asked for a fresh one — the new session opens on this briefing rather than
//! on an empty prompt, so the orchestrator does not greet the user as a
//! stranger. Generated by Boite, never improvised by the agent: what the agent
//! writes is its answer, not its own memory.

use crate::model::Thread;
use crate::store::Store;

/// How many chat lines a briefing replays by default.
pub const DEFAULT_MESSAGES: usize = 30;

/// Builds the briefing for one scope.
///
/// Plain text, harness-neutral: it travels as the opening prompt of whatever
/// CLI the user picked. English, like every string an agent reads.
pub fn briefing(store: &Store, scope: Option<&str>, messages: usize) -> Result<String, String> {
    let mut out = String::from(
        "Your session was restarted. You are the workspace orchestrator; \
         this is what Boite kept for you.\n",
    );
    match scope {
        Some(project) => out.push_str(&format!("Your scope: project {project}.\n")),
        None => out.push_str("Your scope: the whole workspace.\n"),
    }

    let threads = store.load_threads()?;
    let alive: Vec<&Thread> = threads
        .iter()
        .filter(|t| t.settled_at.is_none())
        .filter(|t| scope.is_none_or(|p| t.project_id == p))
        .collect();
    out.push_str(&format!("\nLive threads ({}):\n", alive.len()));
    for t in &alive {
        let name = t.title.as_deref().unwrap_or(&t.label);
        let role = t.role.as_deref().unwrap_or("worker");
        out.push_str(&format!(
            "- {} [{}] {} status={}\n",
            t.id, role, name, t.status
        ));
    }

    // Bounded by the ring the table itself is not: a briefing reads at most a
    // ring's worth of history, which is already far past what it replays.
    let lines = store.orchestrator_messages(scope, None, crate::pulse::RING_CAP as usize)?;
    let tail = lines.len().saturating_sub(messages);
    out.push_str(&format!(
        "\nRecent conversation ({} of {} lines):\n",
        lines.len() - tail,
        lines.len()
    ));
    for line in &lines[tail..] {
        let role = line["role"].as_str().unwrap_or("?");
        let text = line["text"].as_str().unwrap_or("");
        out.push_str(&format!("{role}: {text}\n"));
    }
    Ok(out)
}

#[cfg(test)]
mod tests {
    use super::*;

    fn scratch(name: &str) -> Store {
        let path = std::env::temp_dir().join(format!(
            "boite-briefing-{}-{name}.db",
            std::process::id()
        ));
        let _ = std::fs::remove_file(&path);
        Store::open(&path).unwrap()
    }

    /// The briefing replays the tail of the durable history, not the whole of
    /// it, and names the scope so a project orchestrator does not wake up
    /// believing it owns the workspace.
    #[test]
    fn a_briefing_carries_the_tail_of_the_history_and_its_scope() {
        let store = scratch("tail");
        for i in 0..5 {
            store
                .add_orchestrator_message(None, "user", &format!("line {i}"), None, None, i)
                .unwrap();
        }
        let text = briefing(&store, None, 2).unwrap();
        assert!(text.contains("the whole workspace"));
        assert!(text.contains("line 4"));
        assert!(text.contains("2 of 5 lines"));
        assert!(!text.contains("line 0"), "the head is not replayed");

        let scoped = briefing(&store, Some("p1"), 2).unwrap();
        assert!(scoped.contains("project p1"));
    }
}
